/*
 * spacewasm.h — C API for the SpaceWasm WebAssembly interpreter.
 * Generated by cbindgen
 */

#ifndef SPACEWASM_H
#define SPACEWASM_H

#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>

/*
 Operation status returned by most `spacewasm_*` functions.
 [`spacewasm_status_t::SPACEWASM_OK`] (0) means success.

 Variants are glob-re-exported below so they can be named unqualified within
 this crate (e.g. `status::SPACEWASM_OK`).
 */
enum spacewasm_status_t
#if defined(__cplusplus) || __STDC_VERSION__ >= 202311L
  : int32_t
#endif // defined(__cplusplus) || __STDC_VERSION__ >= 202311L
 {
    SPACEWASM_OK = 0,
    SPACEWASM_ERR_NULL_ARG = 1,
    SPACEWASM_ERR_BAD_ARG = 2,
    SPACEWASM_ERR_BAD_UTF8 = 3,
    SPACEWASM_ERR_NAME_TOO_LONG = 4,
    SPACEWASM_ERR_BAD_SIGNATURE = 5,
    SPACEWASM_ERR_CAPACITY = 6,
    SPACEWASM_ERR_NOT_FOUND = 7,
    SPACEWASM_ERR_WRONG_STATE = 8,
    SPACEWASM_ERR_ALLOC_FAILED = 16,
    SPACEWASM_ERR_OUT_OF_MEMORY = 17,
    SPACEWASM_ERR_PAGE_TOO_SMALL = 18,
    SPACEWASM_ERR_MEM_OUT_OF_BOUNDS = 32,
    SPACEWASM_ERR_PARAM_LEN_MISMATCH = 48,
    SPACEWASM_ERR_PARAM_TYPE_MISMATCH = 49,
    SPACEWASM_ERR_STACK_OVERFLOW = 50,
    SPACEWASM_ERR_PARSE = 64,
    SPACEWASM_ERR_STREAM = 80,
};
#ifndef __cplusplus
#if __STDC_VERSION__ >= 202311L
typedef enum spacewasm_status_t spacewasm_status_t;
#else
typedef int32_t spacewasm_status_t;
#endif // __STDC_VERSION__ >= 202311L
#endif // __cplusplus

/*
 Result of a C host function call.
 */
enum spacewasm_hostcall_result_t
#if defined(__cplusplus) || __STDC_VERSION__ >= 202311L
  : int32_t
#endif // defined(__cplusplus) || __STDC_VERSION__ >= 202311L
 {
    /*
     Continue; populate `out_result` if the function has a result type.
     */
    SPACEWASM_CONTINUE = 0,
    /*
     Trap the interpreter.
     */
    SPACEWASM_TRAP = 1,
    /*
     Pause the interpreter (cooperative yield).
     */
    SPACEWASM_PAUSE = 2,
};
#ifndef __cplusplus
#if __STDC_VERSION__ >= 202311L
typedef enum spacewasm_hostcall_result_t spacewasm_hostcall_result_t;
#else
typedef int32_t spacewasm_hostcall_result_t;
#endif // __STDC_VERSION__ >= 202311L
#endif // __cplusplus

/*
 FFI-safe value type tag. Matches the ordering of [`spacewasm::ValType`].
 */
enum spacewasm_valtype_t
#if defined(__cplusplus) || __STDC_VERSION__ >= 202311L
  : uint8_t
#endif // defined(__cplusplus) || __STDC_VERSION__ >= 202311L
 {
    SPACEWASM_I32 = 0,
    SPACEWASM_I64 = 1,
    SPACEWASM_F32 = 2,
    SPACEWASM_F64 = 3,
};
#ifndef __cplusplus
#if __STDC_VERSION__ >= 202311L
typedef enum spacewasm_valtype_t spacewasm_valtype_t;
#else
typedef uint8_t spacewasm_valtype_t;
#endif // __STDC_VERSION__ >= 202311L
#endif // __cplusplus

/*
 Outcome of a [`spacewasm_read_fn_t`] call, written by the callback.
 */
enum spacewasm_read_result_t
#if defined(__cplusplus) || __STDC_VERSION__ >= 202311L
  : int32_t
#endif // defined(__cplusplus) || __STDC_VERSION__ >= 202311L
 {
    /*
     A chunk of `*out_len` bytes was written to the buffer. `out_len == 0`
     also signals end-of-stream.
     */
    SPACEWASM_READ_OK = 0,
    /*
     End of stream; no more bytes.
     */
    SPACEWASM_READ_EOF = 1,
    /*
     An I/O error occurred; loading fails with `SPACEWASM_ERR_STREAM`.
     */
    SPACEWASM_READ_ERROR = 2,
};
#ifndef __cplusplus
#if __STDC_VERSION__ >= 202311L
typedef enum spacewasm_read_result_t spacewasm_read_result_t;
#else
typedef int32_t spacewasm_read_result_t;
#endif // __STDC_VERSION__ >= 202311L
#endif // __cplusplus

/*
 Outcome of a call to `spacewasm_engine_run` / `spacewasm_engine_run_to_completion`.
 */
enum spacewasm_run_status_t
#if defined(__cplusplus) || __STDC_VERSION__ >= 202311L
  : int32_t
#endif // defined(__cplusplus) || __STDC_VERSION__ >= 202311L
 {
    SPACEWASM_RUN_FINISHED = 0,
    SPACEWASM_RUN_OUT_OF_FUEL = 1,
    SPACEWASM_RUN_PAUSE = 2,
    SPACEWASM_RUN_TRAP = 3,
    SPACEWASM_RUN_READER_ERROR = 4,
};
#ifndef __cplusplus
#if __STDC_VERSION__ >= 202311L
typedef enum spacewasm_run_status_t spacewasm_run_status_t;
#else
typedef int32_t spacewasm_run_status_t;
#endif // __STDC_VERSION__ >= 202311L
#endif // __cplusplus

/*
 Reason accompanying a trap (`out_trap`). Mirrors [`spacewasm::TrapReason`],
 with an extra [`SPACEWASM_TRAP_NONE`] (`-1`) written when no trap occurred.
 */
enum spacewasm_trap_t
#if defined(__cplusplus) || __STDC_VERSION__ >= 202311L
  : int32_t
#endif // defined(__cplusplus) || __STDC_VERSION__ >= 202311L
 {
    /*
     No trap occurred (the run finished, paused, or ran out of fuel).
     */
    SPACEWASM_TRAP_NONE = -1,
    /*
     Triggered by an `unreachable` instruction.
     */
    SPACEWASM_TRAP_UNREACHABLE = 0,
    /*
     A host function noted an unrecoverable failure.
     */
    SPACEWASM_TRAP_HOST = 1,
    /*
     Integer or floating-point division by zero.
     */
    SPACEWASM_TRAP_DIVIDE_BY_ZERO = 2,
    /*
     An indirect call index was out of the table's range.
     */
    SPACEWASM_TRAP_INVALID_TABLE_INDEX = 3,
    /*
     The function type in an indirect call did not match the pointer's type.
     */
    SPACEWASM_TRAP_INVALID_TABLE_FUNCTION_TYPE = 4,
    /*
     An indirect call referenced an uninitialized table element.
     */
    SPACEWASM_TRAP_UNINITIALIZED_TABLE_ELEMENT = 5,
    /*
     An imported global could not be read.
     */
    SPACEWASM_TRAP_GLOBAL_GET_FAILED = 6,
    /*
     An imported global could not be set.
     */
    SPACEWASM_TRAP_GLOBAL_SET_FAILED = 7,
    /*
     A memory allocation (e.g. `memory.grow`) ran out of memory.
     */
    SPACEWASM_TRAP_OUT_OF_MEMORY = 8,
    /*
     `memory.grow` failed because a host function holds the memory.
     */
    SPACEWASM_TRAP_MEMORY_REF_NOT_UNIQUE = 9,
    /*
     A memory operation was out of bounds.
     */
    SPACEWASM_TRAP_MEMORY_OUT_OF_BOUNDS = 10,
    /*
     Ran out of stack space.
     */
    SPACEWASM_TRAP_STACK_OVERFLOW = 11,
    /*
     The result of an operation was unrepresentable (e.g. converting Inf).
     */
    SPACEWASM_TRAP_UNREPRESENTABLE_RESULT = 12,
    /*
     Signed division caused integer overflow.
     */
    SPACEWASM_TRAP_INTEGER_OVERFLOW = 13,
    /*
     Attempted to convert NaN to an integer.
     */
    SPACEWASM_TRAP_BAD_CONVERSION_TO_INTEGER = 14,
};
#ifndef __cplusplus
#if __STDC_VERSION__ >= 202311L
typedef enum spacewasm_trap_t spacewasm_trap_t;
#else
typedef int32_t spacewasm_trap_t;
#endif // __STDC_VERSION__ >= 202311L
#endif // __cplusplus

typedef struct spacewasm_host_module_t spacewasm_host_module_t;

/*
 Opaque guest linear-memory allocator handle (`spacewasm_allocator_t`), owning
 a reference-counted [`WasmMemoryAllocator`] built from C callbacks.
 */
typedef struct spacewasm_allocator_t spacewasm_allocator_t;

/*
 SpaceWasm store handle (`spacewasm_store_t`).

 Owns the core [`Engine`] (which owns the store and execution state) and the
 persistent [`CodeBuilder`] that accumulates compiled text across successive
 module loads. The interpreter reads code directly from the builder's pages,
 so no separate copy is kept.
 */
typedef struct spacewasm_store_t spacewasm_store_t;

/*
 Allocate `size` bytes aligned to `align`. Return NULL on failure.
 */
typedef uint8_t *(*spacewasm_alloc_fn_t)(void *userdata, size_t size, size_t align);

/*
 Resize the `old_size`-byte allocation at `ptr` (alignment `align`) to
 `new_size` bytes, moving the contents if needed. Return NULL on failure.
 */
typedef uint8_t *(*spacewasm_realloc_fn_t)(void *userdata,
                                           uint8_t *ptr,
                                           size_t old_size,
                                           size_t new_size,
                                           size_t align);

/*
 Free the `size`-byte allocation at `ptr` (alignment `align`).
 */
typedef void (*spacewasm_dealloc_fn_t)(void *userdata, uint8_t *ptr, size_t size, size_t align);

typedef struct spacewasm_host_t {
    struct spacewasm_host_module_t *ptr;
    uint32_t capacity;
    uint32_t len;
} spacewasm_host_t;

/*
 Opaque handle passed to C host callbacks, wrapping a borrowed core
 [`Engine`]. Valid only for the duration of the call.
 */
typedef struct spacewasm_caller_t {

} spacewasm_caller_t;

/*
 FFI-safe union of the four WebAssembly 1.0 value payloads.
 */
typedef union spacewasm_value_payload_t {
    int32_t i32_;
    int64_t i64_;
    float f32_;
    double f64_;
} spacewasm_value_payload_t;

/*
 FFI-safe tagged value. `tag` selects the active `u` field.
 */
typedef struct spacewasm_value_t {
    spacewasm_valtype_t tag;
    union spacewasm_value_payload_t u;
} spacewasm_value_t;

/*
 Callback signature for a host function implemented in C. `caller` is an
 opaque handle for `spacewasm_mem_*`; write `out_result` iff returning a value.
 */
typedef spacewasm_hostcall_result_t (*spacewasm_host_fn_t)(struct spacewasm_caller_t *caller,
                                                           void *userdata,
                                                           const struct spacewasm_value_t *params,
                                                           size_t n_params,
                                                           struct spacewasm_value_t *out_result);

/*
 C callback that supplies the next chunk of a Wasm module. The callback owns
 the buffer: it sets `*out_buf` to point at the next chunk and `*out_len` to
 its length (0 == EOF). The chunk must stay valid until the next call to the
 callback (or until loading completes).
 */
typedef spacewasm_read_result_t (*spacewasm_read_fn_t)(void *userdata,
                                                       const uint8_t **out_buf,
                                                       size_t *out_len);

/*
 FFI-safe mirror of [`spacewasm::CompilerOptions`], controlling how guest
 modules loaded onto a store are compiled. Passed to [`spacewasm_store_new`].
 */
typedef struct spacewasm_compiler_options_t {
    /*
     Allow compiling `memory.grow` instructions. When `false`, a module using
     `memory.grow` is rejected at load time.
     */
    bool allow_memory_grow;
    /*
     Maximum number of iterations to resolve during a control-flow backpatch.
     Bounds compile time on pathological modules at the cost of rejecting some
     valid programs. Set to 0 for unlimited iterations.
     */
    uint32_t max_backpatch_iterations;
    /*
     Maximum number of compiled code pages allowed across all modules loaded
     onto the store.
     */
    uint32_t max_code_pages;
} spacewasm_compiler_options_t;

/*
 Allocate `size` bytes aligned to `align`. Return NULL on failure. Per page allocation.
 */
typedef uint8_t *(*spacewasm_global_alloc_fn_t)(void *userdata, size_t size, size_t align);

/*
 Free the `size`-byte allocation at `ptr` (alignment `align`). Per page deallocation.
 */
typedef void (*spacewasm_global_dealloc_fn_t)(void *userdata,
                                              uint8_t *ptr,
                                              size_t size,
                                              size_t align);

typedef struct spacewasm_memory_statistics_t {
    int32_t total_bytes;
    int32_t pad_bytes;
} spacewasm_memory_statistics_t;



#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/*
 Global allocator statistics. Independent of the interpreter configuration,
 so it takes no const-generic parameters.
 */
spacewasm_memory_statistics_t spacewasm_memory_statistics(void);

/*
 Create a guest linear-memory allocator from three C callbacks, returning an
 opaque handle (or null if any callback is null or allocation fails). The
 handle is passed to [`spacewasm_store_load_module`] and must be released with
 [`spacewasm_allocator_destroy`]. `userdata` is passed to every callback.
 */
struct spacewasm_allocator_t *spacewasm_allocator_new(spacewasm_alloc_fn_t alloc,
                                                      spacewasm_realloc_fn_t realloc,
                                                      spacewasm_dealloc_fn_t dealloc,
                                                      void *userdata);

/*
 Destroy an allocator handle. No-op on null. Any loaded module keeps its own
 reference to the underlying allocator, so destroying the handle after loading
 is safe.

 # Safety
 `allocator` must be a live handle from [`spacewasm_allocator_new`], not
 already destroyed.
 */
void spacewasm_allocator_destroy(struct spacewasm_allocator_t *allocator);

/*
 Create a new host module vector of max_host_module size

 # Safety
 `host` must be live
 */
spacewasm_status_t spacewasm_host_new(uint32_t len, struct spacewasm_host_t *dest);

/*
 Add a host module named `name` sized for `max_functions` functions and `max_globals` globals
 writing its index to `out_idx` (if non-null).

 # Safety
 `host` must be live; all C strings valid and NUL-terminated.
 */
spacewasm_status_t spacewasm_add_host_module(struct spacewasm_host_t *host,
                                             const char *name,
                                             uint32_t max_functions,
                                             uint32_t max_globals,
                                             uint32_t *out_idx);

/*
 Register a host function `name` in host module `module_idx`, with parameter
 and return signatures given by `params_sig`/`returns_sig` and implemented by
 callback `f` (passed `userdata` on each call).

 # Safety
 `host` must be live; all C strings valid and NUL-terminated.
 */
spacewasm_status_t spacewasm_add_host_function(struct spacewasm_host_t *host,
                                               uint32_t module_idx,
                                               const char *name,
                                               const char *params_sig,
                                               const char *returns_sig,
                                               spacewasm_host_fn_t f,
                                               void *userdata);

/*
 Load a guest module named `name` onto an existing store by streaming its
 bytes through the `read` callback. The callback owns the buffer backing each
 chunk (see [`spacewasm_read_fn_t`]). This does not run the module's start
 function; use [`spacewasm_store_module_needs_start`] and
 [`spacewasm_store_run_start`] for that. `allocator` supplies the guest linear
 memory (see [`spacewasm_allocator_new`]). Writes the new module's index to
 `out_module_idx` (if non-null). May be called repeatedly to load several
 modules onto the same store.

 # Safety
 `store` and `allocator` must be live handles; `read` a valid callback;
 `out_module_idx` null or valid.
 */
spacewasm_status_t spacewasm_store_load_module(struct spacewasm_store_t *store,
                                               const char *name,
                                               spacewasm_read_fn_t read,
                                               void *read_userdata,
                                               struct spacewasm_allocator_t *allocator,
                                               uint32_t *out_module_idx);

/*
 Consume the host module vector `host` and finish it into a store handle,
 written to `out_store`. The store is sized with a `stack_size`-byte guest
 stack, room for `max_modules` guest modules (≤ 256), and compiles guest
 modules according to `options` (code-page budget, `memory.grow` support,
 backpatch bound). No guest module is loaded yet; use
 [`spacewasm_store_load_module`] to load one or more.

 `host` may be null to create a store with no host modules. The host vector
 is always consumed (its handle must not be used or destroyed afterwards),
 whether or not the store is created successfully.

 # Safety
 `host` must be null or a live handle from [`spacewasm_host_new`], not already
 consumed/destroyed; `out_store` must be a valid pointer.
 */
spacewasm_status_t spacewasm_store_new(struct spacewasm_host_t *host,
                                       size_t stack_size,
                                       uint32_t max_modules,
                                       struct spacewasm_compiler_options_t options,
                                       struct spacewasm_store_t **out_store);

/*
 Destroy a host vector that was never consumed into a store. No-op on null.

 # Safety
 `host` must be a live handle, not already consumed/destroyed.
 */
void spacewasm_host_destroy(struct spacewasm_host_t *host);

/*
 Look up the exported function named `name` in module `module_idx` and write
 its index to `out_index`.

 # Safety
 `store` must be live; `name` valid; `out_index` valid.
 */
spacewasm_status_t spacewasm_store_find_export_func(struct spacewasm_store_t *store,
                                                    uint32_t module_idx,
                                                    const char *name,
                                                    uint32_t *out_index);

/*
 Report whether module `module_idx` declares a start function that should be
 run (via [`spacewasm_store_run_start`]) before the module is used, writing
 the answer to `out_needs_start`.

 # Safety
 `store` must be live; `out_needs_start` valid.
 */
spacewasm_status_t spacewasm_store_module_needs_start(struct spacewasm_store_t *store,
                                                      uint32_t module_idx,
                                                      bool *out_needs_start);

/*
 Run the start function of module `module_idx` (if any) for up to `fuel`
 instructions, writing any trap to `out_trap`. Returns whether the start
 function finished, trapped, paused, or ran out of fuel. A module with no
 start function returns [`spacewasm_run_status_t::SPACEWASM_RUN_FINISHED`]
 immediately. If it runs out of fuel, call again to resume.

 # Safety
 `store` must be live; `out_trap` null or valid.
 */
spacewasm_run_status_t spacewasm_store_run_start(struct spacewasm_store_t *store,
                                                 uint32_t module_idx,
                                                 size_t fuel,
                                                 spacewasm_trap_t *out_trap);

/*
 Set up a call to exported function `func_index` of module `module_idx` with
 the `n` arguments in `params`. Does not run the function; drive execution
 with [`spacewasm_store_run`].

 # Safety
 `store` must be live; `params` valid for `n` entries.
 */
spacewasm_status_t spacewasm_store_invoke(struct spacewasm_store_t *store,
                                          uint32_t module_idx,
                                          uint32_t func_index,
                                          const struct spacewasm_value_t *params,
                                          size_t n);

/*
 Run the pending invocation for up to `fuel` units of work, writing any trap
 to `out_trap`. Returns whether the call finished, trapped, or ran out of fuel.

 # Safety
 `store` must be live; `out_trap` null or valid.
 */
spacewasm_run_status_t spacewasm_store_run(struct spacewasm_store_t *store,
                                           size_t fuel,
                                           spacewasm_trap_t *out_trap);

/*
 Run the pending invocation to completion, slicing execution into
 `fuel_per_slice` chunks (0 for unbounded), writing any trap to `out_trap`.

 # Safety
 `store` must be live; `out_trap` null or valid.
 */
spacewasm_run_status_t spacewasm_store_run_to_completion(struct spacewasm_store_t *store,
                                                         size_t fuel_per_slice,
                                                         spacewasm_trap_t *out_trap);

/*
 Fetch the result of the last completed call, coerced to `expected`, into
 `out`.

 # Safety
 `store` must be live; `out` valid.
 */
spacewasm_status_t spacewasm_store_get_result(struct spacewasm_store_t *store,
                                              spacewasm_valtype_t expected,
                                              struct spacewasm_value_t *out);

/*
 Destroy a store and free its resources. No-op on null.

 # Safety
 `store` must be a live handle, not already destroyed.
 */
void spacewasm_store_destroy(struct spacewasm_store_t *store);

/*
 Read `len` bytes of guest linear memory starting at `addr` into `dst`.
 Intended for use from within a host function.

 # Safety
 `caller` must be a live caller handle; `dst` valid for `len`.
 */
spacewasm_status_t spacewasm_mem_read(struct spacewasm_caller_t *caller,
                                      uint32_t addr,
                                      uint8_t *dst,
                                      size_t len);

/*
 Write `len` bytes from `src` into guest linear memory starting at `addr`.
 Intended for use from within a host function.

 # Safety
 `caller` must be a live caller handle; `src` valid for `len`.
 */
spacewasm_status_t spacewasm_mem_write(struct spacewasm_caller_t *caller,
                                       uint32_t addr,
                                       const uint8_t *src,
                                       size_t len);

/*
 Write the current size of guest linear memory, in pages, to `out_pages`.

 # Safety
 `caller` must be a live caller handle; `out_pages` valid.
 */
spacewasm_status_t spacewasm_mem_size(struct spacewasm_caller_t *caller, uint32_t *out_pages);

/*
 Handle a spacewasm Rust panic. This function should not return

 # Arguments

 * `filename`: Filename where panic occurred (not null terminated)
 * `filename_len`: Length of filename (could be 0)
 * `line`: Line number where panic occured
 * `msg`: Panic message if it could be extracted (not null terminated)
 * `len`: Length of panic message (zero if empty)

 returns: !
 */
extern void spacewasm_panic(const uint8_t *filename,
                            size_t filename_len,
                            uint32_t line,
                            const uint8_t *msg,
                            size_t len);

/*
 Stub for the exception-handling personality routine. The precompiled `core`
 is built for unwinding and references `rust_eh_personality` even though we
 compile with `panic = "abort"`, so a C consumer linking the staticlib would
 otherwise see an undefined symbol. Under `panic = "abort"` it is never
 actually invoked; providing it here keeps the archive self-contained.
 */
void rust_eh_personality(void);

/*
 Install the process-wide heap allocator backing the interpreter.
 `alloc`/`dealloc` are called at *page* granularity.

 # Safety
 `alloc`/`dealloc` must remain valid for the lifetime of the process and
 honor the requested size/alignment. `userdata` must outlive all allocations.
 */
int32_t spacewasm_set_global_allocator(spacewasm_global_alloc_fn_t alloc,
                                       spacewasm_global_dealloc_fn_t dealloc,
                                       void *userdata);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* SPACEWASM_H */
