#!/bin/bash

# Exit when any command fails
set -e
set -x

# Change to GitHub workspace
cd "$GITHUB_WORKSPACE"

export FPRIME_DIR="$GITHUB_WORKSPACE/gps-tutotial/fprime)"

export SCRIPT_DIR="${FPRIME_DIR}/ci"
. "${SCRIPT_DIR}/helpers.bash"

export LOG_DIR="${FPRIME_DIR}/.github/actions/tutorial/ci-logs-$(date +"%Y-%m-%dT%H%M%S")"
mkdir -p "${LOG_DIR}"

# Move to GpsApp directory
cd gps-tutorial/GpsApp

# Build GpsApp
fprime-util generate
fprime-util build

# Log
archive_logs