@ the number of sequences successfully completed
telemetry SequencesSucceeded: U64 update always

@ the number of statements dispatched total
telemetry StatementsDispatched: U64 update always

@ the number of statements that failed to dispatch or execute
telemetry StatementsFailed: U64 update always

@ the number of sequences that failed to validate or execute, or were cancelled
telemetry SequencesFailed: U64 update always