#!/bin/sh -e

cd `dirname $0`

include_paths="
-I$FPRIME
-I$FPRIME/STest
-I$FPRIME/build-fprime-automatic-native-ut
-I$FPRIME/build-fprime-automatic-native-ut/F-Prime
-I$FPRIME/build-fprime-automatic-native-ut/F-Prime/default
-I$FPRIME/cmake/platform/unix
-I$FPRIME/default
-I$FPRIME/googletest/googletest
-I$FPRIME/googletest/googletest/include
"

cpp_lib_files="
$FPRIME/Fw/Types/Assert.cpp
$FPRIME/Fw/Types/Serializable.cpp
$FPRIME/Fw/Types/StringBase.cpp
$FPRIME/Fw/Types/StringUtils.cpp
$FPRIME/Fw/Types/snprintf_format.cpp
$FPRIME/STest/STest/Pick/Pick.cpp
$FPRIME/STest/STest/Pick/Pick_default.cpp
$FPRIME/STest/STest/Random/Random.cpp
$FPRIME/build-fprime-automatic-native-ut/F-Prime/Fw/Types/SuccessEnumAc.cpp
$FPRIME/googletest/googletest/src/gtest-all.cc
"

cpp_module_files="
test/ut/DataStructuresTestMain.cpp
test/ut/RedBlackTreeSetOrMapImplTest.cpp
test/ut/STest/RedBlackTreeSetOrMapImplTestRules.cpp
"

cpp_files="$cpp_lib_files $cpp_module_files"

c_files="
$FPRIME/STest/STest/Random/bsd_random.c
"

common_flags="
    -pedantic
    -Wall
    -Wextra
    -Wconversion
    -Wdouble-promotion
    -Wshadow
    -Werror
    -Wno-unused-parameter
    -Wno-vla
    -g
"

cpp_flags="
    --std=c++11
    -Wold-style-cast
    $common_flags
"

c_flags="
    --std=c99
    $common_flags
"

for file in $cpp_files
do
  base=`basename $file`
  g++ -c $cpp_flags $include_paths $file -o $base.o
done

for file in $c_files
do
  base=`basename $file`
  gcc -c $c_flags $include_paths $file -o $base.o
done

get_o_files()
{
  for file in $cpp_files $c_files
  do
    echo `basename $file`.o
  done
}

g++ `get_o_files` -o exe
