#!/bin/sh -e

files=`find ../../build-fprime-automatic-native-ut -name "$1"`
dest_dir=""
for file in $files
do
  dir=`dirname $file`
  if test -n "$dest_dir" && ! test "$dest_dir" = "$dir"
  then
    echo "inconsistent directories ($dest_dir vs. $dir)" 1>&2
    exit 1
  fi
  dest_dir=$dir
done
for file in $files
do
  base=`basename $file`
  if test -f $base
  then
    echo "putting $dest_dir/$base"
    cp $base $dest_dir
  fi
done
