// ======================================================================
// \title  AGTestBase.cpp
// \author Generated by fpp-to-cpp
// \brief  cpp file for A component Google Test harness base class
// ======================================================================

#include "FppTest/topology/components/A/AGTestBase.hpp"

namespace FppTest {

  // ----------------------------------------------------------------------
  // Construction and destruction
  // ----------------------------------------------------------------------

  AGTestBase ::
    AGTestBase(
        const char* const compName,
        const U32 maxHistorySize
    ) :
      ATesterBase(compName, maxHistorySize)
  {

  }

  AGTestBase ::
    ~AGTestBase()
  {

  }

  // ----------------------------------------------------------------------
  // From ports
  // ----------------------------------------------------------------------

  void AGTestBase ::
    assertFromPortHistory_size(
        const char* const __callSiteFileName,
        const U32 __callSiteLineNumber,
        const U32 size
    ) const
  {
    ASSERT_EQ(size, this->fromPortHistorySize)
      << "\n"
      << __callSiteFileName << ":" << __callSiteLineNumber << "\n"
      << "  Value:    Total size of all from port histories\n"
      << "  Expected: " << size << "\n"
      << "  Actual:   " << this->fromPortHistorySize << "\n";
  }

  void AGTestBase ::
    assert_from_dataOut_size(
        const char* const __callSiteFileName,
        const U32 __callSiteLineNumber,
        const U32 size
    ) const
  {
    ASSERT_EQ(size, this->fromPortHistory_dataOut->size())
      << "\n"
      << __callSiteFileName << ":" << __callSiteLineNumber << "\n"
      << "  Value:    Size of history for dataOut\n"
      << "  Expected: " << size << "\n"
      << "  Actual:   " << this->fromPortHistory_dataOut->size() << "\n";
  }

}
