#ifndef __BUFFERMANAGERCOMPONENTIMPLCFG_HPP__
#define __BUFFERMANAGERCOMPONENTIMPLCFG_HPP__

#include <Fw/FPrimeBasicTypes.hpp>

namespace Svc {
static const U16 BUFFERMGR_MAX_NUM_BINS = 10;
}

#endif  // __BUFFERMANAGERCOMPONENTIMPLCFG_HPP__
