##############
# Configuration file for LGTM.com
# Currently only needed for cpp code since python and js works by default
#
# @author: Hunter Paulson
# @modified: 2020-07-15
##############


path_classifiers:
    test:
      - "/Gds/test"
      - "/Fw/Python/test"
    docs:
      - "/docs"
queries:
    # Not excluding any results right now because we want to be alerted for all issues and fixes
    # In the future we may exclude depreciated code like ptf/ and Gds/src/wxgui/
    # - exclude:          
extraction:
    cpp:
        prepare:    
            packages:
                - "python3"
                - "python3-pip"
                - "python3-venv"
        after_prepare:
            # setup the venv and install packages
            - "python3 -m venv ./fprime-venv"
            - ". ./fprime-venv/bin/activate" 
            - "pip install ./Fw/Python"
            - "pip install ./Gds"
        configure:   
            command:
        before_index:
            - "fprime-util generate"
        index:   
            build_command:
                - "fprime-util build --all"
