repos:
  - repo: local
    hooks:
      - id: fprime-util-format
        name: Format Changed C++ Code (clang-format)
        entry: fprime-util
        language: system
        files: \.(c|h|cpp|hpp)$
        pass_filenames: true
        args: ["format", "-f"]
