site_name: F Prime
site_url: https://fprime.jpl.nasa.gov/
repo_url: https://github.com/nasa/fprime
repo_name: nasa/fprime
docs_dir: docs/ # using ./fprime/ as the root directory to host all source files in the website
site_dir: site
edit_uri: edit/devel/ # for "Edit Source" button (see content.action.edit)

exclude_docs: |
  Autocoders/
  ci/
  googletest/

theme:
  name: material # enables the material theme, DO NOT CHANGE
  language: en
  logo: assets/images/logo-fprime-jpl.svg
  favicon: assets/images/favicon.svg
  custom_dir: overrides # external directory
  icon:
    annotation: material/information-slab-circle  # custom icon for annotations

  features:
    - navigation.tabs # enables tabs
    - navigation.top # enables back to top button
    - navigation.tabs.sticky # makes tabs sticky
    # - navigation.expand # expands all navigation links with dropdowns by default
    # - navigation.sections # enables section dividers in the navigation
    - navigation.footer # enables previous/next page navigation links by the footer
    - navigation.instant # instant loading
    - navigation.indexes # enables overview pages for sections
    - navigation.tracking # URL in the address bar is automatically updated with the active anchor as highlighted in the table of contents
    - content.code.copy # enable code copy for all code blocks
    - content.code.annotate # enable code annotations for all code blocks
    - content.tooltips # replaces the browser's rendering logic for title attribute with tooltips (for content, header, navigation)
    - content.tabs.link # all content tabs across the whole documentation site will be linked and switch to the same label when the user clicks on a tab
    - content.action.edit # display a "Edit Source" button on the top right of the page

  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: custom
      accent: custom
      toggle:
        icon: material/lightbulb-on
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: custom
      toggle:
        icon: material/lightbulb-off
        name: Switch to light mode



# Adds extra settings
extra:
  version:
      provider: mike
      alias: true
  homepage: https://fprime.jpl.nasa.gov/ # Forces homepage link not to include versioning info



# Link to custom css
extra_css:
  - overrides/assets/stylesheets/extra.css

# Adds material for mkdocs plugins
plugins:
  - search # enables search, included in Zensical
  # - awesome-nav: not supported by Zensical because it has improved nav capabilities
  - mike: # included in Zensical
      # symlink are not allowed in GH Pages so if website needs to be deployed on GH Pages, use `copy` instead
      # see https://github.blog/changelog/2023-02-21-github-pages-deprecating-symlinks-in-non-actions-builds/
      alias_type: symlink
      canonical_version: latest


markdown_extensions: 
  - toc:
      toc_depth: 2
  - attr_list # allows to add HTML attributes and CSS classes to almost every Markdown inline- and block-level element with a special syntax
  - md_in_html # allows for writing Markdown inside of HTML
  - tables # enables markdown tables
  # enables syntax highlighting on code blocks and inline code blocks
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  # adds support for admonitions/call-outs
  - admonition
  - pymdownx.details
  - github-callouts # enables GitHub-style Markdown alerts (e.g. > [!NOTE])
  # enables the use of definition lists and tasks lists
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  # enables abbreviations and allows to build a simple project-wide glossary, sourcing definitions from a central location.
  - abbr
  - pymdownx.snippets
  # enables tabs
  - pymdownx.tabbed:
      alternate_style: true


# Custom navigation is set in the fprime/.nav.yml file
# Must keep a copy of just the tutorials nav here to let multirepo know to import them, this does not act as a nav
nav:
  - Home: https://fprime.jpl.nasa.gov/
  - Documentation: index.md
  - Getting Started with F Prime:
    - Getting Started with F Prime: getting-started/index.md
    - F´ Features: getting-started/features.md
    - Installing F´: getting-started/installing-fprime.md
  - How-To:
    - How-To: how-to/index.md
    - Dev:
      - Generate Data Products: how-to/dev/data-products.md
      - Define State Machines in F Prime: how-to/dev/define-state-machines.md
      - Develop a Device Driver: how-to/dev/develop-device-driver.md
      - Develop an F´ Library: how-to/dev/develop-fprime-libraries.md
      - Develop a Subtopology: how-to/dev/develop-subtopologies.md
      - Implement a Radio Manager Component: how-to/dev/implement-radio-manager.md
      - Develop Components in Python: how-to/dev/python-development.md
    - Integrate:
      - Implement a Framing Protocol: how-to/integrate/custom-framing.md
      - Implement an OS Abstraction Layer: how-to/integrate/implement-osal.md
      - Integrate a Third-Party Library: how-to/integrate/integrate-external-libraries.md
      - Porting to new platforms: how-to/integrate/porting-guide.md
    - Ops:
      - Create Ground-Derived Channels in F Prime GDS: how-to/ops/derive-channels-on-ground.md
      - Develop a GDS Plugin: how-to/ops/develop-gds-plugins.md
      - Load Parameters in Batch: how-to/ops/prm-write-how-to.md
    - Test:
      - Write Rule-Based Tests for F Prime Components: how-to/test/rule-based-testing.md
      - Test-Driven Development in F Prime (F´): how-to/test/test-driven-development.md
  - Reference:
    - Reference: reference/index.md
    - Communication Adapter Interface: reference/communication-adapter-interface.md
    - FPP JSON Dictionary Specification: reference/fpp-json-dict.md
    - F Prime Translation Guide: reference/fprime-translations.md
    - GDS Plugins:
      - Communication Plugin: reference/gds-plugins/communications.md
      - Data Handler Plugin: reference/gds-plugins/data-handler.md
      - Framing Plugin: reference/gds-plugins/framing.md
      - App Plugin: reference/gds-plugins/gds-app.md
      - GDS Function Plugin: reference/gds-plugins/gds-function.md
    - Nomenclature: reference/nomenclature.md
    - F´ Numerical Types: reference/numerical-types.md
    - System Functional Documentation:
      - System Functional Documentation: reference/system-functional/index.md
      - Buffer Management Functionality: reference/system-functional/buffer-management.md
      - CCSDS Protocol Functionality: reference/system-functional/ccsds-protocol.md
      - Command Dispatch Functionality: reference/system-functional/command-dispatch.md
      - Communication Stack Functionality: reference/system-functional/communication.md
      - Data Products Functionality: reference/system-functional/data-products.md
      - Dictionary Capabilities: reference/system-functional/dictionary.md
      - Event Management Functionality: reference/system-functional/event-management.md
      - File Management Functionality: reference/system-functional/file-management.md
      - Framework Functionality: reference/system-functional/framework.md
      - Hardware Driver Functionality: reference/system-functional/hardware-drivers.md
      - Health Monitoring Functionality: reference/system-functional/health-monitoring.md
      - Operating System Abstraction Layer (OSAL): reference/system-functional/osal.md
      - Parameter Management Functionality: reference/system-functional/parameters.md
      - Rate Group Scheduling Functionality: reference/system-functional/rate-group-scheduling.md
      - Sequencing Functionality: reference/system-functional/sequencing.md
      - CDH Core Subtopology: reference/system-functional/subtopology-cdh-core.md
      - ComCcsds Subtopology: reference/system-functional/subtopology-com-ccsds.md
      - ComFprime Subtopology: reference/system-functional/subtopology-com-fprime.md
      - ComLoggerTee Subtopology: reference/system-functional/subtopology-com-logger-tee.md
      - Data Products Subtopology: reference/system-functional/subtopology-data-products.md
      - File Handling Subtopology: reference/system-functional/subtopology-file-handling.md
      - System Services Functionality: reference/system-functional/system-services.md
      - Telemetry Channel Storage Functionality: reference/system-functional/telemetry-chan.md
      - Telemetry Packetizer Functionality: reference/system-functional/telemetry-packetizer.md
      - Time Services Functionality: reference/system-functional/time-services.md
  - Tutorials:
    - Tutorials Index: tutorials/index.md
    - Hello World: tutorials/tutorials-hello-world/docs/hello-world.md
    - LED Blinker: tutorials/tutorials-led-blinker/docs/led-blinker.md
    - MathComponent: tutorials/tutorials-math-component/docs/math-component.md
    - Cross-Compilation Setup: tutorials/cross-compilation.md
    - Arduino LED Blinker: tutorials/tutorials-arduino-led-blinker/docs/arduino-led-blinker.md
  - User Manual:
    - User Manual: user-manual/index.md
    - Build System:
      - F´ CMake Build System: user-manual/build-system/01-cmake-intro.md
      - CMake API Reference: user-manual/build-system/cmake-api.md
      - CMake Customization: user-manual/build-system/cmake-customization.md
      - CMake Implementations: user-manual/build-system/cmake-implementations.md
      - F´ and CMake Platforms: user-manual/build-system/cmake-platforms.md
      - Targets: user-manual/build-system/cmake-targets.md
      - CMake Toolchain Files: user-manual/build-system/cmake-toolchains.md
      - CMake Build System Unit Tests: user-manual/build-system/cmake-uts.md
      - '`settings.ini`: Build Settings Configuration': user-manual/build-system/settings.md
    - Design Patterns:
      - Application-Manager-Driver Architecture: user-manual/design-patterns/app-man-drv.md
      - Common Port Design Patterns: user-manual/design-patterns/common-port-patterns.md
      - Health Checking Pattern: user-manual/design-patterns/health-checking.md
      - A Quick Look at the Hub Pattern: user-manual/design-patterns/hub-pattern.md
      - The Manager/Worker Pattern: user-manual/design-patterns/manager-worker.md
      - Rate Groups and Timeliness: user-manual/design-patterns/rate-group.md
      - Subtopologies: user-manual/design-patterns/subtopologies.md
    - Framework:
      - Asserts in F: user-manual/framework/assert.md
      - F´ Autocoded Functions and Component Classes: user-manual/framework/autocoded-functions.md
      - Constructing the F´ Topology: user-manual/framework/building-topology.md
      - Selecting Component, Port, and Command Kinds: user-manual/framework/component-and-port-selection.md
      - Configuring F´: user-manual/framework/configuring-fprime.md
      - Data Products: user-manual/framework/data-products.md
      - Ground Interface Architecture and Customization: user-manual/framework/ground-interface.md
      - Memory Management:
        - Memory Management: user-manual/framework/memory-management/index.md
        - Buffer Pools with Svc.BufferManager: user-manual/framework/memory-management/buffer-pool.md
        - Memory Allocation with Fw::MemAllocator: user-manual/framework/memory-management/memory-allocation.md
      - F´ on Baremetal Systems: user-manual/framework/run-baremetal.md
      - F´ on Multi-Core Systems: user-manual/framework/run-multi-core.md
      - State Machines: user-manual/framework/state-machines.md
      - Supported Platforms: user-manual/framework/supported-platforms.md
    - GDS:
      - The F´ GDS CLI: user-manual/gds/gds-cli.md
      - The GDS Dashboard: user-manual/gds/gds-custom-dashboards.md
      - GDS Dashboard Component Reference: user-manual/gds/gds-dashboard-reference.md
      - GDS Developer's Guide: user-manual/gds/gds-dev-guide.md
      - GDS Integration Test API: user-manual/gds/gds-test-api-guide.md
      - Reusable Integration Tests: user-manual/gds/reusable-integration-tests.md
      - Sequencing In F´: user-manual/gds/seqgen.md
    - Overview:
      - Introduction To F´: user-manual/overview/01-full-intro.md
      - F´ Software Architecture: user-manual/overview/02-fprime-architecture.md
      - 'Core Constructs: Ports, Components, and Topologies': user-manual/overview/03-port-comp-top.md
      - 'Data Constructs: Commands, Events, Channels, and Parameters': user-manual/overview/04-cmd-evt-chn-prm.md
      - Data Structures and Types: user-manual/overview/05-enum-arr-ser.md
      - F´ Development Process: user-manual/overview/development-practice.md
      - The F´ Ground Data System: user-manual/overview/gds-introduction.md
      - Projects and Deployments: user-manual/overview/proj-dep.md
      - A Tour of the Source Tree: user-manual/overview/source-tree.md
      - Unit Testing in F´: user-manual/overview/unit-testing.md
    - Security:
      - Software Bill Of Materials Generation: user-manual/security/software-bill-of-materials.md
# watch: # if this path changes, a full site rebuild is triggered, but this is causing zensical serve to stall
#   - /

validation: # warning messages at build time
  unresolved_references: false
  unresolved_footnotes: false
  unused_definitions: false
  unused_footnotes: false
  shadowed_definitions: false
  shadowed_footnotes: false
  invalid_links: false
  invalid_link_anchors: false