; Deployment UTs only: framework and autocoder UTs run in the framework CI jobs
; For more information: https://fprime.jpl.nasa.gov/latest/docs/user-manual/framework/settings/
[fprime]
framework_path: ..
project_root: .
default_cmake_options: FPRIME_ENABLE_FRAMEWORK_UTS=OFF
    FPRIME_ENABLE_AUTOCODER_UTS=OFF
