#!/bin/sh

# ----------------------------------------------------------------------
# Codegen/Cpp/banner
# Emit banner
# ----------------------------------------------------------------------

echo '// ====================================================================== 
// \\title  '$1'
// \\author '$2'
// \\brief  '$3'
//
// \\copyright
// Copyright (C) '`date "+%Y"`' California Institute of Technology.
// ALL RIGHTS RESERVED.  United States Government Sponsorship
// acknowledged. Any commercial use must be negotiated with the Office
// of Technology Transfer at the California Institute of Technology.
// 
// This software may be subject to U.S. export control laws and
// regulations.  By accepting this document, the user agrees to comply
// with all U.S. export laws and regulations.  User has the
// responsibility to obtain export licenses, or other export authority
// as may be required before exporting such information to foreign
// countries or providing access to foreign persons.
// ======================================================================'
