#!/bin/sh

# ---------------------------------------------------------------------- 
# runtest_DARWIN
# ---------------------------------------------------------------------- 

cd ${BUILD_ROOT}/Fw/SerializableFile/test/ut
echo "Running ${BUILD_ROOT}/Fw/SerializableFile/test/ut/$1/test_ut"
${BUILD_ROOT}/Fw/SerializableFile/test/ut/$1/test_ut
