@startuml

participant activeComm order 1
participant deframer order 2
participant buffMgr order 3
participant fileUplink order 4

activate activeComm

activeComm -> buffMgr: Allocate frame buffer FB
buffMgr --> activeComm: Return FB

activeComm -> activeComm: Fill FB with framed data
activeComm -> deframer: Send FB [framedIn]

deframer -> buffMgr: Allocate packet buffer PB [bufferAllocate]
buffMgr --> deframer: Return PB

deframer -> deframer: Deframe FB into PB
deframer ->> fileUplink: Send PB [bufferOut]

deframer -> buffMgr: Deallocate FB [framedDeallocate]
buffMgr --> deframer

deframer --> activeComm

deactivate activeComm

activate fileUplink
fileUplink -> buffMgr: Deallocate PB
buffMgr --> fileUplink
deactivate fileUplink

@enduml
