@startuml

participant rateGroup order 1
participant passiveComm order 2
participant deframer order 3
participant buffMgr order 4
participant fileUplink order 5

activate rateGroup

rateGroup -> deframer: Send schedule tick [schedIn]

deframer -> passiveComm: Poll for data [framedPoll]
passiveComm --> deframer: Return status

deframer -> buffMgr: Allocate packet buffer PB [bufferAllocate]
buffMgr --> deframer: Return PB

deframer -> deframer: Deframe data into PB
deframer ->> fileUplink: Send PB [bufferOut]

deframer --> rateGroup

deactivate rateGroup

activate fileUplink
fileUplink -> buffMgr: Deallocate PB
buffMgr --> fileUplink
deactivate fileUplink

@enduml
