@startuml

participant rateGroup order 1
participant passiveComm order 2
participant deframer order 3
participant buffMgr order 4
participant cmdDisp order 5

activate rateGroup

rateGroup -> deframer: Send schedule tick [schedIn]

deframer -> passiveComm: Poll for data [framedPoll]

alt Data available

  deframer -> buffMgr: Allocate packet buffer PB [bufferAllocate]
  deframer -> deframer: Deframe data into PB
  deframer -> deframer: Copy PB into a command packet C
  deframer ->> cmdDisp: Send C [comOut]
  deframer -> buffMgr: Deallocate PB [bufferDeallocate]

deactivate rateGroup

  activate cmdDisp
  cmdDisp -> deframer: Send cmd response [cmdResponseIn]
  deactivate cmdDisp

end

@enduml
