collect_cnt = tlm("INST HEALTH_STATUS COLLECTS")
cmd("INST COLLECT with DURATION 11, TYPE NORMAL")
cmd_no_range_check("INST COLLECT with DURATION 11, TYPE NORMAL")
cmd_no_hazardous_check("INST COLLECT with DURATION 11, TYPE NORMAL")
cmd_no_checks("INST COLLECT with DURATION 11, TYPE NORMAL")
wait_check("INST HEALTH_STATUS COLLECTS == #{collect_cnt + 2}", 10)
cmd("INST CLEAR")
cmd_no_range_check("INST CLEAR")
cmd_no_hazardous_check("INST CLEAR")
cmd_no_checks("INST CLEAR")
puts tlm("INST HEALTH_STATUS COLLECTS")
