cmd("INST ABORT")
cmd_no_range_check("INST COLLECT with TYPE NORMAL, TEMP 100")
cmd_no_hazardous_check("INST CLEAR")
cmd_no_checks("INST COLLECT with TYPE SPECIAL, TEMP 100.0")
cmd_raw("INST ABORT")
cmd_raw_no_range_check("INST COLLECT with TYPE 0, TEMP 100")
cmd_raw_no_hazardous_check("INST CLEAR")
cmd_raw_no_checks("INST COLLECT with TYPE 1, TEMP 100.0")
check("INST ADCS BIASX == 100")
check_formatted("INST ADCS BIASX == 100")
check_with_units("INST ADCS BIASX == 100")
check_raw("INST ADCS BIASX == 100")
check_tolerance("INST ADCS BIASX", 5, 0.5)
check_tolerance_raw("INST ADCS BIASX", 5, 0.5)
check_expression("true == false")
wait
wait 5
wait("INST ADCS BIASX > 100", 5)
wait_raw("INST ADCS BIASX > 100", 5)
wait_tolerance("INST ADCS BIASX", 5, 0.5, 5)
wait_tolerance_raw("INST ADCS BIASX", 5, 0.5, 5)
wait_expression("true == false", 5)
wait_packet("INST","ADCS", 2, 5)
wait_check("INST ADCS BIASX == 100", 5)
wait_check_raw("INST ADCS BIASX == 100", 5)
wait_check_tolerance("INST ADCS BIASX", 5, 0.5, 5)
wait_check_tolerance_raw("INST ADCS BIASX", 5, 0.5, 5)
wait_check_expression("true == false", 5)
wait_check_packet("INST","ADCS", 2, 5)
