@ A serial async input port
async input port serialAsync: [3] serial

@ A serial async input port with queue full behavior and priority
async input port serialAsyncAssert: serial assert

@ A serial async input port with queue full behavior and priority
async input port serialAsyncBlockPriority: serial priority 10 block

@ A serial async input port with queue full behavior and priority
async input port serialAsyncDropPriority: serial priority 5 drop
