locate port Drv.ByteStreamPoll at "ByteStreamDriverModel/ByteStreamDriverModel.fpp"
locate port Drv.ByteStreamRecv at "ByteStreamDriverModel/ByteStreamDriverModel.fpp"
locate port Drv.ByteStreamSend at "ByteStreamDriverModel/ByteStreamDriverModel.fpp"
locate port Drv.DataBuffer at "DataTypes/DataTypes.fpp"
locate type Drv.DataBuffer at "DataTypes/DataTypes.fpp"
locate type Drv.PollStatus at "ByteStreamDriverModel/ByteStreamDriverModel.fpp"
locate type Drv.RecvStatus at "ByteStreamDriverModel/ByteStreamDriverModel.fpp"
locate type Drv.SendStatus at "ByteStreamDriverModel/ByteStreamDriverModel.fpp"
