#!/bin/sh -e

awk '/<a href="/ {
  n = split($0, fields, /<a href="#/)
  for (i = 2; i <= n; ++i) {
    field = fields[i]
    sub(/^#/, "", field)
    sub(/".*/, "", field)
    print field
  }
}' | sort | uniq
