#!/bin/sh

# ---------------------------------------------------------------------- 
# runtest_DARWIN
# ---------------------------------------------------------------------- 

cd ${BUILD_ROOT}/Svc/ComLogger/test/ut
echo "Running ${BUILD_ROOT}/Svc/ComLogger/test/ut/$1/test_ut"
${BUILD_ROOT}/Svc/ComLogger/test/ut/$1/test_ut
