#!/bin/bash

# Grab the removal file from the first argument
REMOVE_FILE="$1"

# Nab the program as the first argument, and shift it away
PROGRAM="$2"
shift
shift

# Run the wrapped program with the properly wrapped remaining arguments
"${PROGRAM}" "$@"
RET="$?"
if (( $RET != 0 ))
then
    rm -f "${REMOVE_FILE}"
fi
exit $RET
