.TH NCSL "L COSI" 12/10/04
.UC
.SH NAME
ncsl - count number of lines of code in a C program
.SH SYNOPSIS
.B ncsl
[
.I options
]
.B [ file ]*
.SH DESCRIPTION
.I Ncsl
counts the lines of code in a C program.
It provides the following information:
.sp 1
.nf
	number of raw lines of code
	number of non-comment, non-blank lines
	number of comments
and optionally:
	number of statement separators
.fi
The output is by default generated in
Unix-style, giving the three or four fields
defined above per line, similar to the output from
.IR wc(1) .
.LP
If you specify no files,
.I ncsl
reads from stdin.
If you specify more than one file on the command line,
.I ncsl
will print the total for each category.
.TP
.B \-n
Show the stripped output, and number the lines.
.B \-s
Show the stripped output.
.B -m
Check for compliance with 18 simple misra rules.
.B -u
Turn off Unix-style output.
Produce only cumulative output for all files, with
one annotated field per line.
.B -v
Add a count of all semicolons and commas as a fourth field.
.SH SEE ALSO
.IR wc(1)
