#!/bin/sh -e

math_component=../docs/Tutorials/MathComponent

cp $math_component/CMakeLists.txt .

dirs="
MathPorts
MathReceiver
MathSender
MathTypes
"

for dir in $dirs
do
  rm -rf $dir
  cp -R $math_component/$dir .
done

for file in instances topology
do
  cp $math_component/Top/$file.fpp Top
done
