#!/bin/sh

export FPRIME_ROOT=`cd ../..; echo $PWD`

fpp-to-xml -p $FPRIME_ROOT \
  -i $FPRIME_ROOT/config/FpConfig.fpp,$FPRIME_ROOT/Fw/Time/Time.fpp \
  LogPort.fpp
# Suppress header file import for FwEventIdType
awk '/FwEventIdType\.hpp/ { next } { print }' < LogPortAi.xml > tmp.xml
mv tmp.xml LogPortAi.xml
