#!/bin/sh

export FPRIME_ROOT=`cd ../..; echo $PWD`

fpp-to-xml -p $FPRIME_ROOT \
  -i $FPRIME_ROOT/config/FpConfig.fpp,$FPRIME_ROOT/Fw/Time/Time.fpp \
  LogPort.fpp LogTextPort.fpp
# Suppress header file import for FwEventIdType
for name in Log LogText
do
  xml_file=$name'PortAi.xml'
  awk '/FwEventIdType\.hpp/ { next } { print }' < $xml_file > tmp.xml
  mv tmp.xml $xml_file
done
