name: 'F prime CI'
description: 'Runs continuous integration testing on F prime'
inputs:
  test:
    description: Test number to run
    required: true
    default: ''
runs:
  using: 'docker'
  image: 'Dockerfile'
  # args:
  #   - ${{ inputs.test }}
  entrypoint: '${{ inputs.test }}.bash'
