name: 'F prime CI'
description: 'Runs continuous integration testing on F prime'
inputs:
  test_type:
    description: Test number to run
    required: true
    default: 1
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.test_type }}
