gov::nasa::jpl::componentaction::LoadIDConfig
Project gov.nasa.jpl.componentaction.LoadIDConfig.project
gov.nasa.jpl.componentaction.LoadIDConfig.LoadIDConfig()
static void gov.nasa.jpl.componentaction.LoadIDConfig.process(Project proj, File pluginDir)
process handles all the phases of this methodology. proj Project object pluginDir Directory to generate documents into IOException
References gov.nasa.jpl.componentaction.Utils.printToAll, gov.nasa.jpl.componentaction.LoadIDConfig.getConfigFile, gov.nasa.jpl.componentaction.LoadIDConfig.validateAndProcessConfig, gov.nasa.jpl.componentaction.LoadIDConfig.changeModel.
Referenced by gov.nasa.jpl.componentaction.LoadIDConfigAction.actionPerformed.
static void gov.nasa.jpl.componentaction.LoadIDConfig.changeModel(Element root, Project proj, Map< String, configItem > configMap)
This function goes through the model and matches each component with its respective instance within the configMap.If there isn't any discrepancies between the model and the config files, baseIDs and window ranges are set to the values from the config file.All subsystems have their base IDs set to zero. root proj configMap LoadIDException
References gov.nasa.jpl.componentaction.LoadIDConfig.configItem.baseID, gov.nasa.jpl.componentaction.LoadIDConfig.configItem.windowRange.
Referenced by gov.nasa.jpl.componentaction.LoadIDConfig.process.
static Map<String , configItem> gov.nasa.jpl.componentaction.LoadIDConfig.validateAndProcessConfig(File config)
Validates and processes the input config file.Checks if the file is valid, is a .CSV, and has four items per row.This also constructs a map where the key is an instance name and the value is a configItem that holds the associated names and IDs. config LoadIDException
References gov.nasa.jpl.componentaction.LoadIDConfig.configItem.instanceName, gov.nasa.jpl.componentaction.LoadIDConfig.configItem.baseID, gov.nasa.jpl.componentaction.LoadIDConfig.configItem.windowRange, gov.nasa.jpl.componentaction.Utils.notifyWarning, gov.nasa.jpl.componentaction.LoadIDConfig.configItem.configItem.
Referenced by gov.nasa.jpl.componentaction.LoadIDConfig.process.
static File gov.nasa.jpl.componentaction.LoadIDConfig.getConfigFile(File projectFile)
Opens up a file chooser box for the user to select what config CSV file to choose.The input argument projectFile is used to specify a starting path. projectFile A config file object LoadIDException
Referenced by gov.nasa.jpl.componentaction.LoadIDConfig.process.