gov::nasa::jpl::componentaction::ProcessISFProject
Project gov.nasa.jpl.componentaction.ProcessISFProject.project
List<ISFComponent> gov.nasa.jpl.componentaction.ProcessISFProject.componentList
List<ISFPort> gov.nasa.jpl.componentaction.ProcessISFProject.portList
gov.nasa.jpl.componentaction.ProcessISFProject.ProcessISFProject()
static void gov.nasa.jpl.componentaction.ProcessISFProject.process(Project proj, File pluginDir)
Main function to process the project. Creates a directory to output XML files into if it does not already exist. Processes all the components in the model and generates an XML file for each of them. Processes all the ports in the model and generates an XML file to store all the port data. proj Project object pluginDir Folder to create XML folder in IOException
References gov.nasa.jpl.componentaction.ProcessISFProject.getElementsOfStereotype, gov.nasa.jpl.componentaction.ProcessISFProject.processComponents, gov.nasa.jpl.componentaction.ProcessISFProject.processPorts, gov.nasa.jpl.componentaction.isfxmlwriter.IsfCompXmlWriter.write, gov.nasa.jpl.componentaction.isfxmlwriter.IsfPortXmlWriter.write.
Referenced by gov.nasa.jpl.componentaction.IsfCommandLine.execute, gov.nasa.jpl.componentaction.IsfComponentAction.actionPerformed, gov.nasa.jpl.componentaction.IsfXmlAction.actionPerformed, gov.nasa.jpl.componentaction.TestISFExceptions.testPortException, gov.nasa.jpl.componentaction.TestISFExceptions.testPassiveComponent, gov.nasa.jpl.componentaction.TestISFExceptions.testProcessProject.
static void gov.nasa.jpl.componentaction.ProcessISFProject.process(Project proj, File pluginDir, String processPackage)
Function to process the project, except restricts component search to the processPackage. Creates a directory to output XML files into if it does not already exist. Processes all the components in the processPackage and generates an XML file for each of them. Processes all the ports in the processPackage and generates an XML file to store all the port data. proj Project object pluginDir Folder to create XML folder in processPackage String of the process package IOException
References gov.nasa.jpl.componentaction.ProcessISFProject.getElementsOfStereotypeAndPackage, gov.nasa.jpl.componentaction.ProcessISFProject.processComponents, gov.nasa.jpl.componentaction.ProcessISFProject.processPorts, gov.nasa.jpl.componentaction.isfxmlwriter.IsfCompXmlWriter.write, gov.nasa.jpl.componentaction.isfxmlwriter.IsfPortXmlWriter.write.
static void gov.nasa.jpl.componentaction.ProcessISFProject.processPorts(List< Element > portElementList)
Converts ports to ISFPort objects with associated data and return elements and adds it to the portList. portElementList List of ports PortException
References gov.nasa.jpl.componentaction.ISFPort.addData, gov.nasa.jpl.componentaction.ISFPort.addReturn.
Referenced by gov.nasa.jpl.componentaction.ProcessISFProject.process.
static void gov.nasa.jpl.componentaction.ProcessISFProject.processComponents(List< Element > compElementList, String stereotype)
Creates ISFComponent objects for all components with associated ports and adds them toe the componentList. compElementList stereotype PortException
References gov.nasa.jpl.componentaction.ISFComponent.setStereoType, gov.nasa.jpl.componentaction.ISFComponent.getPortStereotype, gov.nasa.jpl.componentaction.ISFComponent.newAddPort, gov.nasa.jpl.componentaction.ISFComponent.newRolePort, gov.nasa.jpl.componentaction.ISFComponent.getName, gov.nasa.jpl.componentaction.ISFComponent.checkComponent.
Referenced by gov.nasa.jpl.componentaction.ProcessISFProject.process.
static List<Element> gov.nasa.jpl.componentaction.ProcessISFProject.getElementsOfStereotype(String stereotype)
Returns a list of elements with specified input stereotype string. stereotype stereotype string to look for list of Elements
Referenced by gov.nasa.jpl.componentaction.ProcessISFProject.process.
static List<Element> gov.nasa.jpl.componentaction.ProcessISFProject.getElementsOfStereotypeAndPackage(String stereotype, String processPackage)
Returns a list of elements with specified input stereotype string and within the processPackage. stereotype stereotype string to look for processPackage package string to look for list of Elements
Referenced by gov.nasa.jpl.componentaction.ProcessISFProject.process.