gov::nasa::jpl::componentaction::TestISFExceptions
String gov.nasa.jpl.componentaction.TestISFExceptions.pluginDir
static void gov.nasa.jpl.componentaction.TestISFExceptions.main(String[] args)
References gov.nasa.jpl.componentaction.TestISFExceptions.suite.
static Test gov.nasa.jpl.componentaction.TestISFExceptions.suite()
Organizes the order in which tests run.
References gov.nasa.jpl.componentaction.TestISFExceptions.TestISFExceptions.
Referenced by gov.nasa.jpl.componentaction.TestISFExceptions.main.
gov.nasa.jpl.componentaction.TestISFExceptions.TestISFExceptions(String testMethodToRun, String testName)
Referenced by gov.nasa.jpl.componentaction.TestISFExceptions.suite.
gov.nasa.jpl.componentaction.TestISFExceptions.TestISFExceptions(String testMethodToRun)
void gov.nasa.jpl.componentaction.TestISFExceptions.testComponentNoConnections()
References gov.nasa.jpl.componentaction.ProcessISFTopology.process.
void gov.nasa.jpl.componentaction.TestISFExceptions.testPortException()
Checks if ports without types throw exceptions IOException
References gov.nasa.jpl.componentaction.ProcessISFProject.process.
void gov.nasa.jpl.componentaction.TestISFExceptions.testMismatchedType()
Checks if connections with types that do not match throw exceptions IOException
References gov.nasa.jpl.componentaction.ProcessISFTopology.process.
void gov.nasa.jpl.componentaction.TestISFExceptions.testMismatchedDirections()
Checks if connections with directions that do not match throw exceptions IOException
References gov.nasa.jpl.componentaction.ProcessISFTopology.process.
void gov.nasa.jpl.componentaction.TestISFExceptions.testDoubleMultiplicity()
Checks if connections originating from the same output port throws exceptions IOException
References gov.nasa.jpl.componentaction.ProcessISFTopology.process.
void gov.nasa.jpl.componentaction.TestISFExceptions.testPassiveComponent()
Checks if passive components with async inputs throw exceptions IOException
References gov.nasa.jpl.componentaction.ProcessISFProject.process.
ISFComponent gov.nasa.jpl.componentaction.TestISFExceptions.getCompForTesting(String projectName, String compType)
assumes that there is exactly one component in the project projectName compType
References gov.nasa.jpl.componentaction.TestISFExceptions.getElementsOfStereotype, gov.nasa.jpl.componentaction.ISFComponent.setStereoType, gov.nasa.jpl.componentaction.ISFComponent.getPortStereotype, gov.nasa.jpl.componentaction.ISFComponent.newAddPort.
Referenced by gov.nasa.jpl.componentaction.TestISFExceptions.testActiveComponent, gov.nasa.jpl.componentaction.TestISFExceptions.testQueuedComponentAsync, gov.nasa.jpl.componentaction.TestISFExceptions.testQueuedComponentSync.
void gov.nasa.jpl.componentaction.TestISFExceptions.testActiveComponent()
Checks if active component without async ports gives warnings IOException
References gov.nasa.jpl.componentaction.TestISFExceptions.getCompForTesting, gov.nasa.jpl.componentaction.ISFComponent.isValid.
void gov.nasa.jpl.componentaction.TestISFExceptions.testQueuedComponentAsync()
Checks if queued component without async ports gives warnings IOException
References gov.nasa.jpl.componentaction.TestISFExceptions.getCompForTesting, gov.nasa.jpl.componentaction.ISFComponent.isValid.
void gov.nasa.jpl.componentaction.TestISFExceptions.testQueuedComponentSync()
Checks if queued component without sync ports gives warnings IOException
References gov.nasa.jpl.componentaction.TestISFExceptions.getCompForTesting, gov.nasa.jpl.componentaction.ISFComponent.isValid.
void gov.nasa.jpl.componentaction.TestISFExceptions.testProcessTopology()
Checks if topology is generated correctly IOException
References gov.nasa.jpl.componentaction.ProcessISFTopology.process.
void gov.nasa.jpl.componentaction.TestISFExceptions.testAbout()
References gov.nasa.jpl.componentaction.IsfAbout.actionPerformed.
void gov.nasa.jpl.componentaction.TestISFExceptions.testProcessProject()
References gov.nasa.jpl.componentaction.ProcessISFProject.process, gov.nasa.jpl.componentaction.ProcessISFTopology.process.
void gov.nasa.jpl.componentaction.TestISFExceptions.testNoSource()
References gov.nasa.jpl.componentaction.ProcessISFTopology.process.
void gov.nasa.jpl.componentaction.TestISFExceptions.testNoTarget()
References gov.nasa.jpl.componentaction.ProcessISFTopology.process.
void gov.nasa.jpl.componentaction.TestISFExceptions.testMultipleSubsystems()
Tests both subsystems within subsystems, as well as multiple instances of one subsystem.Note: The input file fails parsing for ports and components. IOException
References gov.nasa.jpl.componentaction.ProcessISFTopology.process.
void gov.nasa.jpl.componentaction.TestISFExceptions.testCommandLine()
void gov.nasa.jpl.componentaction.TestISFExceptions.setUpTest()
void gov.nasa.jpl.componentaction.TestISFExceptions.tearDownTest()
static List<Element> gov.nasa.jpl.componentaction.TestISFExceptions.getElementsOfStereotype(String stereotype, Project project)
Referenced by gov.nasa.jpl.componentaction.TestISFExceptions.getCompForTesting.