gov::nasa::jpl::componentaction::ISFPort
Element gov.nasa.jpl.componentaction.ISFPort.portElement
Referenced by gov.nasa.jpl.componentaction.ISFPort.ISFPort.
List<Element> gov.nasa.jpl.componentaction.ISFPort.dataList
Referenced by gov.nasa.jpl.componentaction.ISFPort.getDataList.
Element gov.nasa.jpl.componentaction.ISFPort.returnVal
Referenced by gov.nasa.jpl.componentaction.ISFPort.getReturn.
List<String> gov.nasa.jpl.componentaction.ISFPort.includeList
Referenced by gov.nasa.jpl.componentaction.ISFPort.getIncludeList.
gov.nasa.jpl.componentaction.ISFPort.ISFPort(Element portElement)
Creates an ISFPort object portElement Element of port type to be used in the creation of the object
References gov.nasa.jpl.componentaction.ISFPort.portElement.
String gov.nasa.jpl.componentaction.ISFPort.getNamespace()
Return the port element's namespace namespace string
References gov.nasa.jpl.componentaction.ISFPort.getPortTypeProperty.
void gov.nasa.jpl.componentaction.ISFPort.addData(Element dataElement)
Adds Element to the dataList and checks to make sure the datatype is not empty before adding it to the includeList. dataElement Element to be added
References gov.nasa.jpl.componentaction.ISFPort.getDataTypeProperty.
Referenced by gov.nasa.jpl.componentaction.ProcessISFProject.processPorts.
void gov.nasa.jpl.componentaction.ISFPort.addReturn(Element dataElement)
Adds Element to the includeList if the datatype is not empty. dataElement
References gov.nasa.jpl.componentaction.ISFPort.getDataTypeProperty.
Referenced by gov.nasa.jpl.componentaction.ProcessISFProject.processPorts.
boolean gov.nasa.jpl.componentaction.ISFPort.isReturnEnumeration(Element dataElement)
Checks if the Element object is an instance of Enumeration. dataElement Object to be checked True if the Element is an instance of Enumeration
boolean gov.nasa.jpl.componentaction.ISFPort.hasReturn()
Checks if the returnVal is null. True if the ISFPort has a returnValue
Element gov.nasa.jpl.componentaction.ISFPort.getReturn()
Returns the returnVal. returnVal
References gov.nasa.jpl.componentaction.ISFPort.returnVal.
String gov.nasa.jpl.componentaction.ISFPort.getReturnType(Element dataElement)
Returns String based off the dataElement. dataElement Input Element ReturnType
References gov.nasa.jpl.componentaction.ISFPort.getDataTypeProperty.
String gov.nasa.jpl.componentaction.ISFPort.getName()
Returns the last part of the object name. String name
Referenced by gov.nasa.jpl.componentaction.ISFPort.print, gov.nasa.jpl.componentaction.isfxmlwriter.IsfPortXmlWriter.write.
String [] gov.nasa.jpl.componentaction.ISFPort.getDataName(Element dataElement)
Checks if the dataElement is a reference or pointer and returns a list of Strings where the first value is the pass type and the second value is the name of the dataElement. dataElement List of Strings
String gov.nasa.jpl.componentaction.ISFPort.getDataType(Element dataElement)
Returns the data type with the namespace property prepended to it. dataElement namespace String
References gov.nasa.jpl.componentaction.ISFPort.getDataTypeProperty.
List<Element> gov.nasa.jpl.componentaction.ISFPort.getDataList()
Returns the dataLIst List of Elements
References gov.nasa.jpl.componentaction.ISFPort.dataList.
List<String> gov.nasa.jpl.componentaction.ISFPort.getIncludeList()
Returns the includeList List of Strings
References gov.nasa.jpl.componentaction.ISFPort.includeList.
List<EnumerationLiteral> gov.nasa.jpl.componentaction.ISFPort.getEnumItems(Element dataElement)
Returns the enumerated items of the datatype. dataElement List of Enumeration Literal objects
List<EnumerationLiteral> gov.nasa.jpl.componentaction.ISFPort.getReturnEnumItems(Element dataElement)
Get enumeration items from a Port's Enumeration return type dataElement
boolean gov.nasa.jpl.componentaction.ISFPort.isEnumeration(Element dataElement)
Checks if the Type of the dataElement is an instance of Enumeration. dataElement boolean
String gov.nasa.jpl.componentaction.ISFPort.getPortTypeProperty(Element dataElement, String property)
Returns the property value of the PortType's stereotype of the input element argument. dataElement The Element in question. property The parameter that is being accessed within the PortType stereotype the associated value of the property in the PortType stereotype
Referenced by gov.nasa.jpl.componentaction.ISFPort.getNamespace.
String gov.nasa.jpl.componentaction.ISFPort.getDataTypeProperty(Element portElement, String property)
Returns the property value of DataType stereotype of the input element argument. dataElement The Element in question. property The parameter that is being accessed within the DataType stereotype the associated value of the property in the DataType stereotype
Referenced by gov.nasa.jpl.componentaction.ISFPort.addData, gov.nasa.jpl.componentaction.ISFPort.addReturn, gov.nasa.jpl.componentaction.ISFPort.getReturnType, gov.nasa.jpl.componentaction.ISFPort.getDataType.
void gov.nasa.jpl.componentaction.ISFPort.print()
Prints the name of the ISPort object.
References gov.nasa.jpl.componentaction.ISFPort.getName.