gov::nasa::jpl::componentaction::ISFSubsystem
static componentType gov.nasa.jpl.componentaction.ISFSubsystem.createComponent(String name, String nameSpace, String type, String baseID, String instanceWindow, String xmlPath)
Creates and returns new componentType name Component name nameSpace Component name space type Component Type baseID Base ID instanceWindow Instance Window ID componentType
References gov.nasa.jpl.componentaction.ISFSubsystem.componentType.name, gov.nasa.jpl.componentaction.ISFSubsystem.topologyModel.name, gov.nasa.jpl.componentaction.ISFSubsystem.componentType.nameSpace, gov.nasa.jpl.componentaction.ISFSubsystem.componentType.type, gov.nasa.jpl.componentaction.ISFSubsystem.componentType.baseID, gov.nasa.jpl.componentaction.ISFSubsystem.topologyModel.baseID, gov.nasa.jpl.componentaction.ISFSubsystem.componentType.instanceWindow, gov.nasa.jpl.componentaction.ISFSubsystem.topologyModel.instanceWindow, gov.nasa.jpl.componentaction.ISFSubsystem.componentType.XMLLocation.
Referenced by gov.nasa.jpl.componentaction.ProcessISFTopology.processSubsystem.
static int gov.nasa.jpl.componentaction.ISFSubsystem.getSourceIndex(Connector conn)
Returns the multiplicity of the source end of the connector. conn Connector multiplicity ConnectorException
References gov.nasa.jpl.componentaction.ISFSubsystem.getSourceConnEnd.
Referenced by gov.nasa.jpl.componentaction.ProcessISFTopology.generateNewMultiplicity.
static int gov.nasa.jpl.componentaction.ISFSubsystem.getTargetIndex(Connector conn)
Returns the multiplicity of the target end of the connector. conn Connector multiplicity ConnectorException
References gov.nasa.jpl.componentaction.ISFSubsystem.getTargetConnEnd.
Referenced by gov.nasa.jpl.componentaction.ProcessISFTopology.generateNewMultiplicity.
static void gov.nasa.jpl.componentaction.ISFSubsystem.print()
static String gov.nasa.jpl.componentaction.ISFSubsystem.getFileLocation(Element instanceElement)
Referenced by gov.nasa.jpl.componentaction.ProcessISFTopology.processSubsystem.
static String gov.nasa.jpl.componentaction.ISFSubsystem.getBaseId(Element instanceElement)
Returns the base ID of the element. instanceElement
Referenced by gov.nasa.jpl.componentaction.ProcessISFTopology.process, gov.nasa.jpl.componentaction.ProcessISFTopology.processSubsystem.
static String gov.nasa.jpl.componentaction.ISFSubsystem.getInstanceWindow(Element instanceElement)
Returns the instance window of the element. instanceElement
Referenced by gov.nasa.jpl.componentaction.ProcessISFTopology.process, gov.nasa.jpl.componentaction.ProcessISFTopology.processSubsystem.
static String gov.nasa.jpl.componentaction.ISFSubsystem.getSourceComp(Connector c)
Returns the source name off the attached component. c Connector Component Name ConnectorException Will raise an exception if the target component does not exist (IE the source is connected to the outside of the subsystem)
References gov.nasa.jpl.componentaction.ISFSubsystem.getSourceConnEnd, gov.nasa.jpl.componentaction.ISFSubsystem.getCompName.
static String gov.nasa.jpl.componentaction.ISFSubsystem.getTargetComp(Connector c)
Returns the target name off the attached component. c Connector Component Name ConnectorException Will raise an exception if the target component does not exist (IE the target is connected to the outside of the subsystem)
References gov.nasa.jpl.componentaction.ISFSubsystem.getTargetConnEnd, gov.nasa.jpl.componentaction.ISFSubsystem.getCompName.
static String gov.nasa.jpl.componentaction.ISFSubsystem.getCompName(ConnectorEnd conn)
Returns the component name of the connectorEnd. conn ConnectorException
Referenced by gov.nasa.jpl.componentaction.ISFSubsystem.getSourceComp, gov.nasa.jpl.componentaction.ISFSubsystem.getTargetComp.
static String gov.nasa.jpl.componentaction.ISFSubsystem.getIDSourcePort(Connector c)
Returns the generic ID of the source port on this Connector. This ID is not unique among different instances of the same module. c Connector ID String ConnectorException
References gov.nasa.jpl.componentaction.ISFSubsystem.getSourceConnEnd.
static String gov.nasa.jpl.componentaction.ISFSubsystem.getIDTargetPort(Connector c)
Returns the generic ID of the target port on this Connector. This ID is not unique among different instances of the same module. c Connector ID String ConnectorException
References gov.nasa.jpl.componentaction.ISFSubsystem.getTargetConnEnd.
static String gov.nasa.jpl.componentaction.ISFSubsystem.getSourcePort(Connector c)
Returns the generic name of source port on this Connector. c Connector Name ConnectorException
References gov.nasa.jpl.componentaction.ISFSubsystem.getPortName, gov.nasa.jpl.componentaction.ISFSubsystem.getSourceConnEnd.
static String gov.nasa.jpl.componentaction.ISFSubsystem.getTargetPort(Connector c)
Returns the generic name of target port on this Connector. c Connector Name ConnectorException
References gov.nasa.jpl.componentaction.ISFSubsystem.getPortName, gov.nasa.jpl.componentaction.ISFSubsystem.getTargetConnEnd.
static String gov.nasa.jpl.componentaction.ISFSubsystem.getPortName(ConnectorEnd conn)
Returns the generic name of the role of the ConnectorEnd. conn ConnectorEnd Name ConnectorException
Referenced by gov.nasa.jpl.componentaction.ISFSubsystem.getSourcePort, gov.nasa.jpl.componentaction.ISFSubsystem.getTargetPort.
static String gov.nasa.jpl.componentaction.ISFSubsystem.getLastPartOfString(String in)
Splits the in string with ' ' and returns the last values in the array. in
Referenced by gov.nasa.jpl.componentaction.ProcessISFTopology.processModel, gov.nasa.jpl.componentaction.ProcessISFTopology.processSubsystem, gov.nasa.jpl.componentaction.ProcessISFTopology.createConnections.
static String gov.nasa.jpl.componentaction.ISFSubsystem.getQualifiedPort(ConnectorEnd connEnd)
Returns a string with the qualified name of the base port it is attached to, along with the qualified name of the instance of the port (if it exists). This can be used to uniquely identify a port against other ports in a subsystem. connEnd ConnectorEnd String of the combined qualified name.
Referenced by gov.nasa.jpl.componentaction.ISFSubsystem.getQualifiedSourcePort, gov.nasa.jpl.componentaction.ISFSubsystem.getQualifiedTargetPort, gov.nasa.jpl.componentaction.ProcessISFTopology.createConnections.
static String gov.nasa.jpl.componentaction.ISFSubsystem.getQualifiedSourcePort(Connector c)
Returns the qualified name of the source port from the connector. The qualified name describes the port by providing the port's name, the module it is attached to, and the location of the module. c Connector String qualified name ConnectorException
References gov.nasa.jpl.componentaction.ISFSubsystem.getSourceConnEnd, gov.nasa.jpl.componentaction.ISFSubsystem.getQualifiedPort.
Referenced by gov.nasa.jpl.componentaction.ProcessISFTopology.processSubsystem.
static String gov.nasa.jpl.componentaction.ISFSubsystem.getQualifiedTargetPort(Connector c)
Returns the qualified name of the target port from the connector. The qualified name describes the port by providing the port's name, the module it is attached to, and the location of the module. c Connector String qualified name ConnectorException
References gov.nasa.jpl.componentaction.ISFSubsystem.getTargetConnEnd, gov.nasa.jpl.componentaction.ISFSubsystem.getQualifiedPort.
Referenced by gov.nasa.jpl.componentaction.ProcessISFTopology.processSubsystem, gov.nasa.jpl.componentaction.ProcessISFTopology.createConnections.
static String gov.nasa.jpl.componentaction.ISFSubsystem.getSourcePortType(Connector c)
Returns the source port type from the Connector. c Connector Port Type ConnectorException
References gov.nasa.jpl.componentaction.ISFSubsystem.getSourceConnEnd.
static String gov.nasa.jpl.componentaction.ISFSubsystem.getTargetPortType(Connector c)
Returns the target port type from the Connector. c Connector Port Type ConnectorException
References gov.nasa.jpl.componentaction.ISFSubsystem.getTargetConnEnd.
static ConnectorEnd gov.nasa.jpl.componentaction.ISFSubsystem.getSourceConnEnd(Connector c)
Checks the connectorEnd roles to match the returned value with the input (source) connector end.This function does not check to see if both ConnectorEnds are different or have the same input/output types. c Connector Source ConnectorEnd
References gov.nasa.jpl.componentaction.ISFSubsystem.getConnEnd.
Referenced by gov.nasa.jpl.componentaction.ISFSubsystem.getSourceIndex, gov.nasa.jpl.componentaction.ISFSubsystem.getSourceComp, gov.nasa.jpl.componentaction.ISFSubsystem.getIDSourcePort, gov.nasa.jpl.componentaction.ISFSubsystem.getSourcePort, gov.nasa.jpl.componentaction.ISFSubsystem.getQualifiedSourcePort, gov.nasa.jpl.componentaction.ISFSubsystem.getSourcePortType, gov.nasa.jpl.componentaction.ProcessISFTopology.createConnections, gov.nasa.jpl.componentaction.ProcessISFTopology.generateNewMultiplicity.
static ConnectorEnd gov.nasa.jpl.componentaction.ISFSubsystem.getTargetConnEnd(Connector c)
Checks the connectorEnd roles to match the returned value with the output (target) connector end.This function does not check to see if both ConnectorEnds are different or have the same input/output types. c Connector Target ConnectorEnd
References gov.nasa.jpl.componentaction.ISFSubsystem.getConnEnd.
Referenced by gov.nasa.jpl.componentaction.ISFSubsystem.getTargetIndex, gov.nasa.jpl.componentaction.ISFSubsystem.getTargetComp, gov.nasa.jpl.componentaction.ISFSubsystem.getIDTargetPort, gov.nasa.jpl.componentaction.ISFSubsystem.getTargetPort, gov.nasa.jpl.componentaction.ISFSubsystem.getQualifiedTargetPort, gov.nasa.jpl.componentaction.ISFSubsystem.getTargetPortType, gov.nasa.jpl.componentaction.ProcessISFTopology.createConnections, gov.nasa.jpl.componentaction.ProcessISFTopology.generateNewMultiplicity.
static ConnectorEnd gov.nasa.jpl.componentaction.ISFSubsystem.getConnEnd(Connector c, boolean isSource)
Both getSourceConnEnd and getTargetConnEnd use this function. Incorporates error handling/checking. The function checks the direction property of the first stereotype found in each port of the connector. Depending on what the connector can see within and around the system, the funcion will return what it sees as the source and what is sees as the target. c Connector isSource true if looking for source end, false if looking for target end Connector End ConnectorException
References gov.nasa.jpl.componentaction.Utils.throwConnectorException.
Referenced by gov.nasa.jpl.componentaction.ISFSubsystem.getSourceConnEnd, gov.nasa.jpl.componentaction.ISFSubsystem.getTargetConnEnd, gov.nasa.jpl.componentaction.ProcessISFTopology.processSubsystem.
static List<Element> gov.nasa.jpl.componentaction.ISFSubsystem.getElementsOfStereotype(String stereotype)
Returns a list of elements with the given stereotype String. stereotype String List of Objects
Referenced by gov.nasa.jpl.componentaction.ProcessISFTopology.checkPorts.
static String gov.nasa.jpl.componentaction.ISFSubsystem.getNamespace(Element componentElement)
Returns the name space of the element. componentElement
Referenced by gov.nasa.jpl.componentaction.ProcessISFTopology.processSubsystem.