gov::nasa::jpl::componentaction::ISFComponent
Element gov.nasa.jpl.componentaction.ISFComponent.componentElement
Referenced by gov.nasa.jpl.componentaction.ISFComponent.ISFComponent.
String gov.nasa.jpl.componentaction.ISFComponent.compStereotype
Referenced by gov.nasa.jpl.componentaction.ISFComponent.setStereoType, gov.nasa.jpl.componentaction.ISFComponent.getStereotype.
String gov.nasa.jpl.componentaction.ISFComponent.URIName
Referenced by gov.nasa.jpl.componentaction.ISFComponent.getURI.
HashMap<String, portObject> gov.nasa.jpl.componentaction.ISFComponent.filtList
Referenced by gov.nasa.jpl.componentaction.ISFComponent.getPortHashList.
String gov.nasa.jpl.componentaction.ISFComponent.IncludeCmdXML
String gov.nasa.jpl.componentaction.ISFComponent.IncludeTlmXML
String gov.nasa.jpl.componentaction.ISFComponent.IncludeEvrXML
String gov.nasa.jpl.componentaction.ISFComponent.IncludeParamXML
String gov.nasa.jpl.componentaction.ISFComponent.IncludeInternalIFXML
String gov.nasa.jpl.componentaction.ISFComponent.IncludeIncludeHdr
gov.nasa.jpl.componentaction.ISFComponent.ISFComponent(Element componentElement)
Instantiation for the ISFComponent. componentElement The element of the component that will be processed.
References gov.nasa.jpl.componentaction.ISFComponent.componentElement, gov.nasa.jpl.componentaction.ISFComponent.getComponentProperty.
void gov.nasa.jpl.componentaction.ISFComponent.setStereoType(String compStereotype)
Sets the component stereotype string value compStereotype Stereotype string
References gov.nasa.jpl.componentaction.ISFComponent.compStereotype.
Referenced by gov.nasa.jpl.componentaction.ProcessISFProject.processComponents, gov.nasa.jpl.componentaction.TestISFExceptions.getCompForTesting.
void gov.nasa.jpl.componentaction.ISFComponent.newAddPort(Element portElement)
Creates a new port object using the port Element inputed. This processes the port and can throw an exception if something in the port is illegal. It also adds the port into fillList. portElement PortException
References gov.nasa.jpl.componentaction.ISFComponent.portObject.portObject, gov.nasa.jpl.componentaction.ISFComponent.portObject.index, gov.nasa.jpl.componentaction.ISFComponent.portObject.datatype, gov.nasa.jpl.componentaction.ISFComponent.getPortDataType, gov.nasa.jpl.componentaction.ISFComponent.portObject.datatypeNamespace, gov.nasa.jpl.componentaction.ISFComponent.getPortDataTypeNamespace, gov.nasa.jpl.componentaction.ISFComponent.portObject.stereotype, gov.nasa.jpl.componentaction.ISFComponent.getPortStereotype, gov.nasa.jpl.componentaction.ISFComponent.portObject.priority, gov.nasa.jpl.componentaction.ISFComponent.getPortProperty, gov.nasa.jpl.componentaction.ISFComponent.portObject.full.
Referenced by gov.nasa.jpl.componentaction.ProcessISFProject.processComponents, gov.nasa.jpl.componentaction.TestISFExceptions.getCompForTesting.
void gov.nasa.jpl.componentaction.ISFComponent.newRolePort(Element portElement)
Creates a new port object using the port Element inputed. This processes the port and can throw an exception if something in the port is illegal. It also adds the port into fillList. portElement PortException
References gov.nasa.jpl.componentaction.ISFComponent.portObject.portObject, gov.nasa.jpl.componentaction.ISFComponent.portObject.index, gov.nasa.jpl.componentaction.ISFComponent.portObject.datatype, gov.nasa.jpl.componentaction.ISFComponent.getPortDataType, gov.nasa.jpl.componentaction.ISFComponent.portObject.datatypeNamespace, gov.nasa.jpl.componentaction.ISFComponent.getPortDataTypeNamespace, gov.nasa.jpl.componentaction.ISFComponent.portObject.stereotype, gov.nasa.jpl.componentaction.ISFComponent.portObject.role, gov.nasa.jpl.componentaction.ISFComponent.getPortStereotype.
Referenced by gov.nasa.jpl.componentaction.ProcessISFProject.processComponents.
String gov.nasa.jpl.componentaction.ISFComponent.getPortName(Element portElement)
Returns the port name. portElement port which the name will be extracted from The name of the port
String gov.nasa.jpl.componentaction.ISFComponent.getPortStereotype(Element portElement)
Returns the port stereotype. portElement port which the stereotype will be extracted from The stereotype of the port
Referenced by gov.nasa.jpl.componentaction.ISFComponent.newAddPort, gov.nasa.jpl.componentaction.ISFComponent.newRolePort, gov.nasa.jpl.componentaction.ProcessISFProject.processComponents, gov.nasa.jpl.componentaction.TestISFExceptions.getCompForTesting.
String gov.nasa.jpl.componentaction.ISFComponent.getPortDataType(Element portElement)
This returns the full path of the data type which includes the directory tree. portElement port data type string PortException
Referenced by gov.nasa.jpl.componentaction.ISFComponent.newAddPort, gov.nasa.jpl.componentaction.ISFComponent.newRolePort.
String gov.nasa.jpl.componentaction.ISFComponent.getPortDataTypeNamespace(Element portElement)
This returns the port data type without the full path. It also tags on the Namespace. portElement data type + '::' + name space
References gov.nasa.jpl.componentaction.ISFComponent.getPortTypeProperty.
Referenced by gov.nasa.jpl.componentaction.ISFComponent.newAddPort, gov.nasa.jpl.componentaction.ISFComponent.newRolePort.
HashMap<String, portObject> gov.nasa.jpl.componentaction.ISFComponent.getPortHashList()
Returns the filtList HashMap, a map with a string associated with a port object. HashMap
References gov.nasa.jpl.componentaction.ISFComponent.filtList.
String gov.nasa.jpl.componentaction.ISFComponent.getURI()
Returns the component's URI, which is the location in the tree hierarchy. string of position in hierarchy
References gov.nasa.jpl.componentaction.ISFComponent.URIName.
String gov.nasa.jpl.componentaction.ISFComponent.getIncludeCmdXML()
Prepends the IncludeCmdXML String with the URI Name address string
References gov.nasa.jpl.componentaction.ISFComponent.getDictionaryString.
String gov.nasa.jpl.componentaction.ISFComponent.getIncludeEvrXML()
Prepends the IncludeEvrXML String with the URI Name address string
References gov.nasa.jpl.componentaction.ISFComponent.getDictionaryString.
String gov.nasa.jpl.componentaction.ISFComponent.getIncludeTlmXML()
Prepends the IncludeTlmXML String with the URI Name address string
References gov.nasa.jpl.componentaction.ISFComponent.getDictionaryString.
String gov.nasa.jpl.componentaction.ISFComponent.getIncludeParamXML()
Prepends the IncludeParamXML String with the URI Name address string
References gov.nasa.jpl.componentaction.ISFComponent.getDictionaryString.
String gov.nasa.jpl.componentaction.ISFComponent.getIncludeInternalIFXML()
Prepends the IncludeInternalIFXML String with the URI Name address string
References gov.nasa.jpl.componentaction.ISFComponent.getDictionaryString.
String gov.nasa.jpl.componentaction.ISFComponent.getIncludeHdrFile()
Prepends the IncludeIncludeHdr String with the URI Name address string
References gov.nasa.jpl.componentaction.ISFComponent.getDictionaryString.
String gov.nasa.jpl.componentaction.ISFComponent.getNamespace()
Get the component stereotype attribute called "Namespace" Namespace string of the componentElement
References gov.nasa.jpl.componentaction.ISFComponent.portObject.getStereotype.
String gov.nasa.jpl.componentaction.ISFComponent.getName()
Returns last part of the componenetElement name name
Referenced by gov.nasa.jpl.componentaction.isfxmlwriter.IsfCompXmlWriter.write, gov.nasa.jpl.componentaction.ProcessISFProject.processComponents.
String gov.nasa.jpl.componentaction.ISFComponent.getStereotype()
Returns compStereotype the stereotype of the object
References gov.nasa.jpl.componentaction.ISFComponent.compStereotype.
List<String> gov.nasa.jpl.componentaction.ISFComponent.getPortDataList()
Creates a list of strings based off the data type from filitList values A list of data type strings
String gov.nasa.jpl.componentaction.ISFComponent.getPortTypeProperty(Element portElement, String property)
Returns the property value of PortType stereotype of the input element argument. portElement Element of the port type property String of value to be looked for in the stereotype PortType The value of the attribute from property
Referenced by gov.nasa.jpl.componentaction.ISFComponent.getPortDataTypeNamespace.
String gov.nasa.jpl.componentaction.ISFComponent.getComponentProperty(Element portElement, String property)
Returns the property value of Component stereotype of the input element argument. portElement Element of the port type property String of value to be looked for in the stereotype Component The value of the attribute from property
Referenced by gov.nasa.jpl.componentaction.ISFComponent.ISFComponent.
String gov.nasa.jpl.componentaction.ISFComponent.getPortProperty(Element portElement, String property)
Returns the property value of async_input stereotype of the input element argument. portElement Element of the port type property String of value to be looked for in the stereotype async_input The value of the attribute from property
Referenced by gov.nasa.jpl.componentaction.ISFComponent.newAddPort.
void gov.nasa.jpl.componentaction.ISFComponent.print()
void gov.nasa.jpl.componentaction.ISFComponent.checkComponent()
All passive components cannot have async_input ports All active components should have sync_input ports All queued components should have sync and async input ports ComponentException
References gov.nasa.jpl.componentaction.ISFComponent.isValid.
Referenced by gov.nasa.jpl.componentaction.ProcessISFProject.processComponents.
void gov.nasa.jpl.componentaction.ISFComponent.warnLog(String errStr)
Prints a warning to the Java standard out as well as the MagicDraw console. errStr Message to be printed
boolean gov.nasa.jpl.componentaction.ISFComponent.isValid(String stereotype, String portType, boolean atLeastOne)
Checks if a component is of a specific stereotype If so, checks if the component satisfies the requirement for a specific port type stereotype the stereotype the component should have portType the port type to check for atLeastOne if the component should have the port type
References gov.nasa.jpl.componentaction.ISFComponent.portObject.stereotype.
Referenced by gov.nasa.jpl.componentaction.ISFComponent.checkComponent, gov.nasa.jpl.componentaction.TestISFExceptions.testActiveComponent, gov.nasa.jpl.componentaction.TestISFExceptions.testQueuedComponentAsync, gov.nasa.jpl.componentaction.TestISFExceptions.testQueuedComponentSync.
String gov.nasa.jpl.componentaction.ISFComponent.getDictionaryString(String includeString)
Return the full dictionary path which includes the URI path specified in the package above the component. includeString input string prepended by URIName
Referenced by gov.nasa.jpl.componentaction.ISFComponent.getIncludeCmdXML, gov.nasa.jpl.componentaction.ISFComponent.getIncludeEvrXML, gov.nasa.jpl.componentaction.ISFComponent.getIncludeTlmXML, gov.nasa.jpl.componentaction.ISFComponent.getIncludeParamXML, gov.nasa.jpl.componentaction.ISFComponent.getIncludeInternalIFXML, gov.nasa.jpl.componentaction.ISFComponent.getIncludeHdrFile.