gov::nasa::jpl::componentaction::ISFComponent::portObject
int gov.nasa.jpl.componentaction.ISFComponent.portObject.index
Referenced by gov.nasa.jpl.componentaction.ISFComponent.portObject.portObject, gov.nasa.jpl.componentaction.ISFComponent.portObject.getIndex, gov.nasa.jpl.componentaction.ISFComponent.newAddPort, gov.nasa.jpl.componentaction.ISFComponent.newRolePort.
String gov.nasa.jpl.componentaction.ISFComponent.portObject.stereotype
Referenced by gov.nasa.jpl.componentaction.ISFComponent.portObject.portObject, gov.nasa.jpl.componentaction.ISFComponent.portObject.getStereotype, gov.nasa.jpl.componentaction.ISFComponent.newAddPort, gov.nasa.jpl.componentaction.ISFComponent.newRolePort, gov.nasa.jpl.componentaction.ISFComponent.isValid.
String gov.nasa.jpl.componentaction.ISFComponent.portObject.datatype
Referenced by gov.nasa.jpl.componentaction.ISFComponent.portObject.portObject, gov.nasa.jpl.componentaction.ISFComponent.portObject.getDatatype, gov.nasa.jpl.componentaction.ISFComponent.newAddPort, gov.nasa.jpl.componentaction.ISFComponent.newRolePort.
String gov.nasa.jpl.componentaction.ISFComponent.portObject.datatypeNamespace
Referenced by gov.nasa.jpl.componentaction.ISFComponent.portObject.portObject, gov.nasa.jpl.componentaction.ISFComponent.portObject.getDatatypeNamespace, gov.nasa.jpl.componentaction.ISFComponent.newAddPort, gov.nasa.jpl.componentaction.ISFComponent.newRolePort.
String gov.nasa.jpl.componentaction.ISFComponent.portObject.role
Referenced by gov.nasa.jpl.componentaction.ISFComponent.portObject.portObject, gov.nasa.jpl.componentaction.ISFComponent.portObject.getRole, gov.nasa.jpl.componentaction.ISFComponent.newRolePort.
String gov.nasa.jpl.componentaction.ISFComponent.portObject.priority
Referenced by gov.nasa.jpl.componentaction.ISFComponent.portObject.portObject, gov.nasa.jpl.componentaction.ISFComponent.portObject.getPriority, gov.nasa.jpl.componentaction.ISFComponent.newAddPort.
String gov.nasa.jpl.componentaction.ISFComponent.portObject.full
Referenced by gov.nasa.jpl.componentaction.ISFComponent.portObject.portObject, gov.nasa.jpl.componentaction.ISFComponent.portObject.getFull, gov.nasa.jpl.componentaction.ISFComponent.newAddPort.
gov.nasa.jpl.componentaction.ISFComponent.portObject.portObject()
References gov.nasa.jpl.componentaction.ISFComponent.portObject.index, gov.nasa.jpl.componentaction.ISFComponent.portObject.stereotype, gov.nasa.jpl.componentaction.ISFComponent.portObject.datatype, gov.nasa.jpl.componentaction.ISFComponent.portObject.datatypeNamespace, gov.nasa.jpl.componentaction.ISFComponent.portObject.role, gov.nasa.jpl.componentaction.ISFComponent.portObject.priority, gov.nasa.jpl.componentaction.ISFComponent.portObject.full.
Referenced by gov.nasa.jpl.componentaction.ISFComponent.newAddPort, gov.nasa.jpl.componentaction.ISFComponent.newRolePort.
int gov.nasa.jpl.componentaction.ISFComponent.portObject.getIndex()
References gov.nasa.jpl.componentaction.ISFComponent.portObject.index.
String gov.nasa.jpl.componentaction.ISFComponent.portObject.getStereotype()
References gov.nasa.jpl.componentaction.ISFComponent.portObject.stereotype.
Referenced by gov.nasa.jpl.componentaction.ISFComponent.getNamespace.
String gov.nasa.jpl.componentaction.ISFComponent.portObject.getDatatype()
References gov.nasa.jpl.componentaction.ISFComponent.portObject.datatype.
String gov.nasa.jpl.componentaction.ISFComponent.portObject.getDatatypeNamespace()
References gov.nasa.jpl.componentaction.ISFComponent.portObject.datatypeNamespace.
String gov.nasa.jpl.componentaction.ISFComponent.portObject.getRole()
References gov.nasa.jpl.componentaction.ISFComponent.portObject.role.
String gov.nasa.jpl.componentaction.ISFComponent.portObject.getPriority()
References gov.nasa.jpl.componentaction.ISFComponent.portObject.priority.
String gov.nasa.jpl.componentaction.ISFComponent.portObject.getFull()
References gov.nasa.jpl.componentaction.ISFComponent.portObject.full.