gov::nasa::jpl::componentaction::Utils
final String gov.nasa.jpl.componentaction.Utils.aadl
static void gov.nasa.jpl.componentaction.Utils.throwConnectorException(String input)
Appends to front "===> FATAL Exception: " to the input then prints and throws Connector Exception input Input String ConnectorException
Referenced by gov.nasa.jpl.componentaction.ISFSubsystem.getConnEnd, gov.nasa.jpl.componentaction.ProcessISFTopology.indexChecking, gov.nasa.jpl.componentaction.ProcessISFTopology.processSubsystem, gov.nasa.jpl.componentaction.ProcessISFTopology.createConnections.
static void gov.nasa.jpl.componentaction.Utils.notifyWarning(String input)
Appends "===> Warning: " to the input then prints the input to standard out and the MagicDraw console input Input String ConnectorException
References gov.nasa.jpl.componentaction.Utils.printToAll.
Referenced by gov.nasa.jpl.componentaction.LoadIDConfig.validateAndProcessConfig, gov.nasa.jpl.componentaction.ProcessISFTopology.process, gov.nasa.jpl.componentaction.ProcessISFTopology.checkPorts, gov.nasa.jpl.componentaction.ProcessISFTopology.processModel, gov.nasa.jpl.componentaction.ProcessISFTopology.createConnections.
static String gov.nasa.jpl.componentaction.Utils.getExtension(File f)
Simple utility method to get the file extension of a file. f File to be checked String value extension of the file
static void gov.nasa.jpl.componentaction.Utils.printToAll(String s)
Combines printing to console out on the Java IDE and MagicDraw s String to be printed
Referenced by gov.nasa.jpl.componentaction.LoadIDConfig.process, gov.nasa.jpl.componentaction.LoadIDConfigAction.actionPerformed, gov.nasa.jpl.componentaction.ProcessISFTopology.process, gov.nasa.jpl.componentaction.ProcessISFTopology.processSubsystem, gov.nasa.jpl.componentaction.ProcessISFTopology.createConnections, gov.nasa.jpl.componentaction.Utils.notifyWarning.