gov::nasa::jpl::componentaction::ProcessISFTopology
Project gov.nasa.jpl.componentaction.ProcessISFTopology.project
Set<String> gov.nasa.jpl.componentaction.ProcessISFTopology.subsystemNameSet
HashMap<String , List<ArrayList<Connector> > > gov.nasa.jpl.componentaction.ProcessISFTopology.subsystemMap
Set<ConnectorEnd> gov.nasa.jpl.componentaction.ProcessISFTopology.sourcePorts
Set<ConnectorEnd> gov.nasa.jpl.componentaction.ProcessISFTopology.targetPorts
HashSet<ISFSubsystem.physicalConnectionType> gov.nasa.jpl.componentaction.ProcessISFTopology.physicalConnectionSet
Referenced by gov.nasa.jpl.componentaction.ProcessISFTopology.process, gov.nasa.jpl.componentaction.ProcessISFTopology.createConnections.
HashMap<String , ISFSubsystem.componentType> gov.nasa.jpl.componentaction.ProcessISFTopology.componentMap
Referenced by gov.nasa.jpl.componentaction.ProcessISFTopology.process, gov.nasa.jpl.componentaction.ProcessISFTopology.processSubsystem.
ArrayList<ISFSubsystem.physicalConnectionType> gov.nasa.jpl.componentaction.ProcessISFTopology.physicalConnectionList
Referenced by gov.nasa.jpl.componentaction.ProcessISFTopology.process.
Map<String , ArrayList<String[]> > gov.nasa.jpl.componentaction.ProcessISFTopology.subsystemOwners
Map<String , Integer> gov.nasa.jpl.componentaction.ProcessISFTopology.subsystemInstances
Map<String ,ArrayList<String> > gov.nasa.jpl.componentaction.ProcessISFTopology.uniqueSubsystemInstanceNames
gov.nasa.jpl.componentaction.ProcessISFTopology.ProcessISFTopology()
static void gov.nasa.jpl.componentaction.ProcessISFTopology.process(Project proj, File pluginDir)
process handles all the phases of this methodology. proj Project object pluginDir Directory to generate documents into IOException
References gov.nasa.jpl.componentaction.ProcessISFTopology.physicalConnectionSet, gov.nasa.jpl.componentaction.ProcessISFTopology.componentMap, gov.nasa.jpl.componentaction.ProcessISFTopology.physicalConnectionList, gov.nasa.jpl.componentaction.Utils.printToAll, gov.nasa.jpl.componentaction.ProcessISFTopology.processModel, gov.nasa.jpl.componentaction.ProcessISFTopology.processSubsystem, gov.nasa.jpl.componentaction.ProcessISFTopology.createConnections, gov.nasa.jpl.componentaction.ProcessISFTopology.checkPorts, gov.nasa.jpl.componentaction.ProcessISFTopology.indexChecking, gov.nasa.jpl.componentaction.ISFSubsystem.topologyModel.baseID, gov.nasa.jpl.componentaction.ISFSubsystem.getBaseId, gov.nasa.jpl.componentaction.ISFSubsystem.getInstanceWindow, gov.nasa.jpl.componentaction.isfxmlwriter.IsfSubXmlWriter.write, gov.nasa.jpl.componentaction.Utils.notifyWarning.
Referenced by gov.nasa.jpl.componentaction.IsfCommandLine.execute, gov.nasa.jpl.componentaction.IsfTopAction.actionPerformed, gov.nasa.jpl.componentaction.IsfXmlAction.actionPerformed, gov.nasa.jpl.componentaction.TestISFExceptions.testComponentNoConnections, gov.nasa.jpl.componentaction.TestISFExceptions.testMismatchedType, gov.nasa.jpl.componentaction.TestISFExceptions.testMismatchedDirections, gov.nasa.jpl.componentaction.TestISFExceptions.testDoubleMultiplicity, gov.nasa.jpl.componentaction.TestISFExceptions.testProcessTopology, gov.nasa.jpl.componentaction.TestISFExceptions.testProcessProject, gov.nasa.jpl.componentaction.TestISFExceptions.testNoSource, gov.nasa.jpl.componentaction.TestISFExceptions.testNoTarget, gov.nasa.jpl.componentaction.TestISFExceptions.testMultipleSubsystems.
static int gov.nasa.jpl.componentaction.ProcessISFTopology.generateNewMultiplicity(Connector e, int currentMultiplicity, int previousConnectorTargetMult)
PHASE TWO FUNCTION generateMultiplicity is used within createConnections to find the multiplicity of the next connector.The function takes in three arguments: the current Connector, the multiplicity of the source of the connector (calculated from this function in the previous iteration of the loop) and a 'prevousConnectorTargetMult', which is an integer which indicates the 'inorder' position of the target of the Connector by keeping a track of how many connectors have accessed the same end. e Connector element currentMultiplicity The current multiplicity value of the connector previousConnectorTargetMult Multiplicity value based on the position of the connector in the port. New multiplicity value to be used in next iteration ConnectorException Only ISFSubsystem.getConnEnd() will raise the exception in this function.
References gov.nasa.jpl.componentaction.ISFSubsystem.getSourceConnEnd, gov.nasa.jpl.componentaction.ISFSubsystem.getTargetConnEnd, gov.nasa.jpl.componentaction.ISFSubsystem.getSourceIndex, gov.nasa.jpl.componentaction.ISFSubsystem.getTargetIndex.
Referenced by gov.nasa.jpl.componentaction.ProcessISFTopology.createConnections.
static ArrayList<ISFSubsystem.physicalConnectionType> gov.nasa.jpl.componentaction.ProcessISFTopology.indexChecking(HashSet< ISFSubsystem.physicalConnectionType > pctSet)
PHASE THREE FUNCTION This function serves two purposes. The first is to convert the physicalConnectionSet to a physicalConnecitonList. The second is to perform index checking and correction on ports of the cmdReg/cmd or com/cmdResponse type.The index checking/correction is done so multiplicites do not need to be specified for cmd/cmdReg or com/cmdResponse (with port names of seqCmdStatus and seqCmdBuff) blocks. The latter pair has the additinal port name constraint because there are multiple other ports with the same cmdResponse type. Some of these port are not to be auto-indexed. This makes it easier for the user to add and remove these ports without needing to worry about if the indexes of the pairings match.The program redefines the indexes in numerical order. Even if initial indexes are given, for the origin of Cmd and the target of CmdReg, they are overwritten. They target index of Cmd is preserved and also is written to the source of CmdReg.METHODOLOGY Iterate through all items of the physicalConnectionType and add those who have types of Cmd/CmdReg or those who have type of CmdResponse/Com and names of seqCmdStatus/seqCmdBuff to a list in a map where the index is the instance name of the associated cmdDispatch. Iterate through all keys in the dictionary. Iterate through each item in the list and find another item that has the opposite target and source components but is off the same pair. If the associated item does not exist and if the search object is of the type of Cmd or Cmd reg, throw an error. If the item is of the type Com/CmdResponse or there is an associated pair, add the item(s) to the output list. Return a new list of physicalConnectionType objects with auto indexed IDS. pctSet Set of Physical Connection Types List of Physical Connection Types
References gov.nasa.jpl.componentaction.ISFSubsystem.physicalConnectionType.source, gov.nasa.jpl.componentaction.ISFSubsystem.physicalConnectionType.target_index, gov.nasa.jpl.componentaction.Utils.throwConnectorException.
Referenced by gov.nasa.jpl.componentaction.ProcessISFTopology.process.
static void gov.nasa.jpl.componentaction.ProcessISFTopology.checkPorts()
PHASE THREE FUNCTION Checks if ports on leaf modules have any connections. If they do not, a warning is brought up onto the console.This function first generates a Map with a generic leaf module's name as a key to a list of the "qualified name" of each port on the module. The qualified name is used as an identifier for the generic module.The function next iterates through all elements with the "PartProperty" stereotype to find "unique" leaf components. The function now uses the unique leaf components generic name to iterate through each of its' ports.Each port is then checked to see if it exists as a key in the subsystemMap. If it doesn't exist, it means that this port has no connections and a warning flag is immediately notified. ConnectorException
References gov.nasa.jpl.componentaction.ISFSubsystem.getElementsOfStereotype, gov.nasa.jpl.componentaction.Utils.notifyWarning.
Referenced by gov.nasa.jpl.componentaction.ProcessISFTopology.process.
static List<Element> gov.nasa.jpl.componentaction.ProcessISFTopology.processModel(Element root)
PHASE ONE FUNCTION processModel has two main functions: to create a list of subsystems and to create a componentMap.All the elements in the module are iterated through using the Element root.If the element type is Subsystem, the element is added to a list to be returned.If the element is an instance of a subsystem, the subsystemOwners map is updated, where each key (name of subsystem) is associated with an list of two string arrays. The first String corresponds to the instance name and the second corresponds to the name of the owner of the subsystem. root Root of the system List of subsystem elements
References gov.nasa.jpl.componentaction.ISFSubsystem.getLastPartOfString, gov.nasa.jpl.componentaction.Utils.notifyWarning.
Referenced by gov.nasa.jpl.componentaction.ProcessISFTopology.process.
static boolean gov.nasa.jpl.componentaction.ProcessISFTopology.isTopSubsystemNode(String key)
Checks the subsystemInstances map (which is a key string mapped to a value of how many times this class is instantiated. Will return true if it is a singular system, false if the system isn't instantiated or the instances equal one. key
Referenced by gov.nasa.jpl.componentaction.ProcessISFTopology.processSubsystem, gov.nasa.jpl.componentaction.ProcessISFTopology.createConnections.
static void gov.nasa.jpl.componentaction.ProcessISFTopology.processSubsystem(Element subsystem)
PHASE ONE FUNCTION processSubsystem populates both the subsystemMap as well as the sourcePorts/targetPorts list.First, the function's name is used with the subsystemOwners map to create a list tree. This list tree is then used to generate all the different names needed to clarifyThe function iterates through all Connectors associated with the subsystem. The subsystemMap, sourcePorts, and targetPorts are populated through this iteration.The subsystemMap is a Map where the key is the ID of each port with an associated list of input and output connectors.ConnectorEnds of leaf components are also pushed onto sourcePorts and targetPorts lists, respective of what direction they accept data.Using the list of all instances, each internal module (bbd) is added as an ISFSubsystem componentType to the component map, with the new name of the module subsystem Subsystem Element ConnectorException
References gov.nasa.jpl.componentaction.Utils.printToAll, gov.nasa.jpl.componentaction.ISFSubsystem.getLastPartOfString, gov.nasa.jpl.componentaction.ProcessISFTopology.isTopSubsystemNode, gov.nasa.jpl.componentaction.ISFSubsystem.getNamespace, gov.nasa.jpl.componentaction.ISFSubsystem.getBaseId, gov.nasa.jpl.componentaction.ISFSubsystem.getInstanceWindow, gov.nasa.jpl.componentaction.ISFSubsystem.getFileLocation, gov.nasa.jpl.componentaction.ProcessISFTopology.componentMap, gov.nasa.jpl.componentaction.ISFSubsystem.createComponent, gov.nasa.jpl.componentaction.ISFSubsystem.getQualifiedSourcePort, gov.nasa.jpl.componentaction.ISFSubsystem.getQualifiedTargetPort, gov.nasa.jpl.componentaction.ISFSubsystem.getConnEnd, gov.nasa.jpl.componentaction.Utils.throwConnectorException.
Referenced by gov.nasa.jpl.componentaction.ProcessISFTopology.process.
static void gov.nasa.jpl.componentaction.ProcessISFTopology.createConnections()
PHASE TWO FUNCTION Iterates through the list of source ports and tries to find the final destination, while checking for errors.For each source port, the program traces down it's path by accessing the subsystemMap with the port's ID. All connections associated with the port are put onto a list, the multiplicity is reevaluated, and the program moves onto processing the next port on the list. Every time a new connector is accessed, the target is checked to see if is a leaf target with the same type as the source. If it is, an ISFSubsystem physicallyConnectionType object is put onto a list.Additionally, to support multiple instances of ibds, is a a source instance and target instance name is created along side every connection. This name is the the root modules name followed by each subsystem which the connection's path goes through. This name is used if the program detect that target or source subsystem is used more than once.Exceptions are thrown in the instances where Source multiplicity is repeated by the same port onto multiple connectors. A source on a singular branch of travel (no other sources share the same path) has a target port at the end with a different type as the source port. ConnectorException
References gov.nasa.jpl.componentaction.ISFSubsystem.getQualifiedPort, gov.nasa.jpl.componentaction.ISFSubsystem.getSourceConnEnd, gov.nasa.jpl.componentaction.ISFSubsystem.getTargetConnEnd, gov.nasa.jpl.componentaction.Utils.throwConnectorException, gov.nasa.jpl.componentaction.ProcessISFTopology.generateNewMultiplicity, gov.nasa.jpl.componentaction.Utils.notifyWarning, gov.nasa.jpl.componentaction.ISFSubsystem.getQualifiedTargetPort, gov.nasa.jpl.componentaction.ProcessISFTopology.isTopSubsystemNode, gov.nasa.jpl.componentaction.ISFSubsystem.getLastPartOfString, gov.nasa.jpl.componentaction.ProcessISFTopology.physicalConnectionSet, gov.nasa.jpl.componentaction.Utils.printToAll.
Referenced by gov.nasa.jpl.componentaction.ProcessISFTopology.process.