#!/bin/sh

. ./defs.sh

fpp-to-xml -p $FPRIME_ROOT -i $DEPS $FPP_FILES

# Codegen workarounds
for name in Cmd CmdReg CmdResponse
do
  xml_file=$name'PortAi.xml'
  cat $xml_file | \
    # Suppress header for FwOpcodeType
    awk '/FwOpcodeType\.hpp/ { next } { print }' > tmp.xml
  mv tmp.xml $xml_file
done
