# Makefile to run global make.
DEPLOYMENT := Somedir
BUILD_ROOT ?= $(subst /$(DEPLOYMENT),,$(CURDIR))

export BUILD_ROOT

SCRUB_BUILD: all

SCRUB_CLEAN: LINUX_bin_clean

include $(BUILD_ROOT)/mk/makefiles/deployment_makefile.mk

