
@startuml
title Component Class Hierarchy
note right of Fw::ObjBase : Framework Class
note right of Fw::PassiveComponentBase : Framework Class
note right of Fw::QueuedComponentBase : Framework Class
note right of Fw::ActiveComponentBase : Framework Class
Fw::PassiveComponentBase -up-|> Fw::ObjBase
Fw::QueuedComponentBase -up--|> Fw::PassiveComponentBase
Fw::ActiveComponentBase -up--|> Fw::QueuedComponentBase
note top of SomeComponentBase : Autocoded Class
SomeComponentBase -right-|> Fw::PassiveComponentBase
SomeComponentBase *-down- "many" SomePorts
note top of SomeComponentImpl : Developer Written Class
SomeComponentImpl -right-|> SomeComponentBase
AnotherComponentBase -right-|> Fw::QueuedComponentBase
AnotherComponentBase *-down- "many" MorePorts
AnotherComponentImpl -right-|> AnotherComponentBase
ThirdComponentBase -right-|> Fw::ActiveComponentBase
ThirdComponentBase *-down- "many" OtherPorts
ThirdComponentImpl -right-|> ThirdComponentBase

@enduml