#ifndef __BUFFERMANAGERCOMPONENTIMPLCFG_HPP__
#define __BUFFERMANAGERCOMPONENTIMPLCFG_HPP__

#include <Fw/Types/BasicTypes.hpp>

namespace Svc {
    static const NATIVE_UINT_TYPE BUFFERMGR_MAX_NUM_BINS = 10;
}


#endif // __BUFFERMANAGERCOMPONENTIMPLCFG_HPP__