/*
 * UdpReceiverComponentImplCfg.hpp
 *
 *  Created on: Nov 11, 2017
 *      Author: tim
 */

#ifndef SVC_UDPRECEIVER_UDPRECEIVERCOMPONENTIMPLCFG_HPP_
#define SVC_UDPRECEIVER_UDPRECEIVERCOMPONENTIMPLCFG_HPP_

namespace Svc {
    const static NATIVE_UINT_TYPE UDP_RECEIVER_MSG_SIZE = 256;
}

#endif /* SVC_UDPRECEIVER_UDPRECEIVERCOMPONENTIMPLCFG_HPP_ */
