// ======================================================================
// \title  FppTestTopologyAc.hpp
// \author Generated by fpp-to-cpp
// \brief  hpp file for FppTest topology
// ======================================================================

#ifndef FppTest_FppTestTopologyAc_HPP
#define FppTest_FppTestTopologyAc_HPP

#include "FppTest/topology/components/A/A.hpp"
#include "FppTest/topology/components/B/B.hpp"
#include "FppTest/topology/deployment/topology/FppTestTopologyDefs.hpp"

// ----------------------------------------------------------------------
// Component instances
// ----------------------------------------------------------------------

namespace FppTest {

//! a1
extern FppTest::A a1;

}  // namespace FppTest

namespace FppTest {

//! a2
extern FppTest::A a2;

}  // namespace FppTest

namespace FppTest {

//! b1
extern FppTest::B b1;

}  // namespace FppTest

namespace FppTest {

//! b2
extern FppTest::B b2;

}  // namespace FppTest

namespace FppTest {

// ----------------------------------------------------------------------
// Constants
// ----------------------------------------------------------------------

namespace BaseIds {
enum {
    FppTest_a1 = 0x1000,
    FppTest_a2 = 0x1100,
    FppTest_b1 = 0x1200,
    FppTest_b2 = 0x1300,
};
}

namespace InstanceIds {
enum {
    FppTest_a1,
    FppTest_a2,
    FppTest_b1,
    FppTest_b2,
};
}

namespace Priorities {
enum {
    FppTest_b1 = 20,
    FppTest_b2 = 20,
};
}

namespace QueueSizes {
enum {
    FppTest_b1 = 10,
    FppTest_b2 = 10,
};
}

namespace StackSizes {
enum {
    FppTest_b1 = 65536,
    FppTest_b2 = 65536,
};
}

namespace TaskIds {
enum {
    FppTest_b1,
    FppTest_b2,
};
}

// ----------------------------------------------------------------------
// Helper functions
// ----------------------------------------------------------------------

//! Initialize components
void initComponents(const TopologyState& state  //!< The topology state
);

//! Configure components
void configComponents(const TopologyState& state  //!< The topology state
);

//! Set component base Ids
void setBaseIds();

//! Connect components
void connectComponents();

//! Register commands
void regCommands();

//! Read parameters
void readParameters();

//! Load parameters
void loadParameters();

//! Start tasks
void startTasks(const TopologyState& state  //!< The topology state
);

//! Stop tasks
void stopTasks(const TopologyState& state  //!< The topology state
);

//! Free threads
void freeThreads(const TopologyState& state  //!< The topology state
);

//! Tear down components
void tearDownComponents(const TopologyState& state  //!< The topology state
);

// ----------------------------------------------------------------------
// Setup and teardown functions
// ----------------------------------------------------------------------

//! Set up the topology
void setup(const TopologyState& state  //!< The topology state
);

//! Tear down the topology
void teardown(const TopologyState& state  //!< The topology state
);

}  // namespace FppTest

#endif
