@startuml

participant activeComm order 1
participant deframer order 2
participant buffMgr order 3
participant fileUplink order 4

activate activeComm

activeComm -> buffMgr: Allocate frame buffer FB
activeComm -> activeComm: Fill FB with framed data
activeComm -> deframer: Send FB [framedIn]

deframer -> buffMgr: Allocate packet buffer PB [bufferAllocate]
deframer -> deframer: Deframe FB into PB
deframer ->> fileUplink: Send PB [bufferOut]
deframer -> buffMgr: Deallocate FB [framedDeallocate]

deactivate activeComm

activate fileUplink
fileUplink -> buffMgr: Deallocate PB
deactivate fileUplink

@enduml
