@startuml

participant "Drv::ByteStreamDriverModel (Active)" order 1
participant "Svc::Deframer" order 2
participant "Svc::BufferManager" order 3
participant "Svc::FileUplink" order 4

activate "Drv::ByteStreamDriverModel (Active)"

"Drv::ByteStreamDriverModel (Active)" -> "Svc::BufferManager": Allocate buffer F
"Drv::ByteStreamDriverModel (Active)" -> "Drv::ByteStreamDriverModel (Active)": Fill F with framed data
"Drv::ByteStreamDriverModel (Active)" -> "Svc::Deframer": Send F [framedIn]

"Svc::Deframer" -> "Svc::BufferManager": Allocate buffer B [bufferAllocate]
"Svc::Deframer" -> "Svc::Deframer": Deframe F into B
"Svc::Deframer" ->> "Svc::FileUplink": Send B [bufferOut]
"Svc::Deframer" -> "Svc::BufferManager": Deallocate F [framedDeallocate]

deactivate "Drv::ByteStreamDriverModel (Active)"

activate "Svc::FileUplink"
"Svc::FileUplink" -> "Svc::BufferManager": Deallocate B
deactivate "Svc::FileUplink"

@enduml
