@startuml

participant passiveComm order 1
participant deframer order 2
participant buffMgr order 3
participant fileUplink order 4

activate passiveComm

passiveComm -> buffMgr: Allocate buffer F
passiveComm -> passiveComm: Fill F with framed data
passiveComm -> deframer: Send F [framedIn]

deframer -> buffMgr: Allocate buffer B [bufferAllocate]
deframer -> deframer: Deframe F into B
deframer ->> fileUplink: Send B [bufferOut]
deframer -> buffMgr: Deallocate F [framedDeallocate]

deactivate passiveComm

activate fileUplink
fileUplink -> buffMgr: Deallocate B
deactivate fileUplink

@enduml
