@startuml

participant rateGroup order 1
participant passiveComm order 2
participant deframer order 3
participant buffMgr order 4
participant fileUplink order 5

activate rateGroup

rateGroup -> deframer: Send schedule tick [schedIn]

deframer -> passiveComm: Poll for data [framedPoll]

alt Data available

  deframer -> buffMgr: Allocate packet buffer PB [bufferAllocate]
  deframer -> deframer: Deframe data into PB
  deframer ->> fileUplink: Send PB [bufferOut]

deactivate rateGroup

  activate fileUplink
  fileUplink -> buffMgr: Deallocate PB
  deactivate fileUplink

end

@enduml
