// ======================================================================
// \title  AGTestBase.hpp
// \author Generated by fpp-to-cpp
// \brief  hpp file for A component Google Test harness base class
// ======================================================================

#ifndef FppTest_AGTestBase_HPP
#define FppTest_AGTestBase_HPP

#include "FppTest/topology/components/A/ATesterBase.hpp"
#include "gtest/gtest.h"

// ----------------------------------------------------------------------
// Macros for typed user from port history assertions
// ----------------------------------------------------------------------

#define ASSERT_FROM_PORT_HISTORY_SIZE(size) \
  this->assertFromPortHistory_size(__FILE__, __LINE__, size)

#define ASSERT_from_dataOut_SIZE(size) \
  this->assert_from_dataOut_size(__FILE__, __LINE__, size)

#define ASSERT_from_dataOut(index, _data) \
  { \
    ASSERT_GT(this->fromPortHistory_dataOut->size(), static_cast<U32>(index)) \
      << "\n" \
      << __FILE__ << ":" << __LINE__ << "\n" \
      << "  Value:    Index into history of dataOut\n" \
      << "  Expected: Less than size of history (" \
      << this->fromPortHistory_dataOut->size() << ")\n" \
      << "  Actual:   " << index << "\n"; \
      const FromPortEntry_dataOut& _e = \
        this->fromPortHistory_dataOut->at(index); \
    ASSERT_EQ(_data, _e.data) \
      << "\n" \
      << __FILE__ << ":" << __LINE__ << "\n" \
      << "  Value:    Value of argument data at index " \
      << index \
      << " in history of dataOut\n" \
      << "  Expected: " << _data << "\n" \
      << "  Actual:   " << _e.data << "\n"; \
  }

namespace FppTest {

  //! \class AGTestBase
  //! \brief Auto-generated base for A component Google Test harness
  class AGTestBase :
    public ATesterBase
  {

    protected:

      // ----------------------------------------------------------------------
      // Construction and destruction
      // ----------------------------------------------------------------------

      //! Construct object AGTestBase
      AGTestBase(
          const char* const compName, //!< The component name
          const U32 maxHistorySize //!< The maximum size of each history
      );

      //! Destroy object AGTestBase
      ~AGTestBase();

    protected:

      // ----------------------------------------------------------------------
      // From ports
      // ----------------------------------------------------------------------

      //! From ports
      void assertFromPortHistory_size(
          const char* const __callSiteFileName, //!< The name of the file containing the call site
          const U32 __callSiteLineNumber, //!< The line number of the call site
          const U32 size //!< The asserted size
      ) const;

      //! From port: dataOut
      void assert_from_dataOut_size(
          const char* const __callSiteFileName, //!< The name of the file containing the call site
          const U32 __callSiteLineNumber, //!< The line number of the call site
          const U32 size //!< The asserted size
      ) const;

  };

}

#endif
