// ======================================================================
// \title  ATesterBase.hpp
// \author Generated by fpp-to-cpp
// \brief  hpp file for A component test harness base class
// ======================================================================

#ifndef FppTest_ATesterBase_HPP
#define FppTest_ATesterBase_HPP

#include <cstdio>

#include "Fw/Comp/PassiveComponentBase.hpp"
#include "Fw/Port/InputSerializePort.hpp"
#include "Fw/Types/Assert.hpp"
#include "Fw/Types/ExternalString.hpp"
#include "FppTest/topology/components/A/AComponentAc.hpp"
#include "FppTest/topology/ports/DataPortAc.hpp"

namespace FppTest {

  //! \class ATesterBase
  //! \brief Auto-generated base for A component test harness
  class ATesterBase :
    public Fw::PassiveComponentBase
  {

    protected:

      // ----------------------------------------------------------------------
      // History class
      // ----------------------------------------------------------------------

      //! \class History
      //! \brief A history of port inputs
      //!
      template<typename T>
      class History
      {

        public:

          //! Create a History
          History(
             const U32 maxSize //!< The maximum history size
          ) :
            m_numEntries(0),
            m_maxSize(maxSize)
          {
            this->m_entries = new T[maxSize];
          }

          //! Destroy a History
          ~History()
          {
            delete[] this->m_entries;
          }

          //! Clear the history
          //!
          void clear()
          {
            this->m_numEntries = 0;
          }

          //! Push an item onto the history
          //!
          void push_back(
              const T& entry //!< The item
          )
          {
            FW_ASSERT(this->m_numEntries < this->m_maxSize);
            this->m_entries[this->m_numEntries++] = entry;
          }

          //! Get an item at an index
          //!
          //! \return The item at index i
          const T& at(
              const U32 i //!< The index
          ) const
          {
            FW_ASSERT(i < this->m_numEntries);
            return this->m_entries[i];
          }

          //! Get the number of entries in the history
          //!
          //! \return The number of entries in the history
          U32 size() const
          {
            return this->m_numEntries;
          }

        private:

          //! The number of entries in the history
          U32 m_numEntries;

          //! The maximum history size
          const U32 m_maxSize;

          //! The entries
          T* m_entries;

      };

    protected:

      // ----------------------------------------------------------------------
      // History types
      // ----------------------------------------------------------------------

      //! A history entry for port from_dataOut
      struct FromPortEntry_dataOut {
        FromPortEntry_dataOut() :
          data()
        {}
        U32 data;
      };

    public:

      // ----------------------------------------------------------------------
      // Component initialization
      // ----------------------------------------------------------------------

      //! Initialize object ATesterBase
      virtual void init(
          FwEnumStoreType instance = 0 //!< The instance number
      );

    public:

      // ----------------------------------------------------------------------
      // Connectors for to ports
      // ----------------------------------------------------------------------

      //! Connect port to dataIn[portNum]
      void connect_to_dataIn(
          FwIndexType portNum, //!< The port number
          FppTest::InputDataPort* port //!< The input port
      );

    public:

      // ----------------------------------------------------------------------
      // Getters for from ports
      // ----------------------------------------------------------------------

      //! Get from port at index
      //!
      //! \return from_dataOut[portNum]
      FppTest::InputDataPort* get_from_dataOut(
          FwIndexType portNum //!< The port number
      );

    protected:

      // ----------------------------------------------------------------------
      // Component construction and destruction
      // ----------------------------------------------------------------------

      //! Construct object ATesterBase
      ATesterBase(
          const char* const compName, //!< The component name
          const U32 maxHistorySize //!< The maximum size of each history
      );

      //! Destroy object ATesterBase
      virtual ~ATesterBase();

    protected:

      // ----------------------------------------------------------------------
      // Default handler implementations for typed from ports
      // You can override these implementation with more specific behavior
      // ----------------------------------------------------------------------

      //! Default handler implementation for from_dataOut
      virtual void from_dataOut_handler(
          FwIndexType portNum, //!< The port number
          U32 data //!< The data
      );

    protected:

      // ----------------------------------------------------------------------
      // Handler base-class functions for from ports
      // ----------------------------------------------------------------------

      //! Handler base-class function for from_dataOut
      void from_dataOut_handlerBase(
          FwIndexType portNum, //!< The port number
          U32 data //!< The data
      );

    protected:

      // ----------------------------------------------------------------------
      // Invocation functions for to ports
      // ----------------------------------------------------------------------

      //! Invoke the to port connected to dataIn
      void invoke_to_dataIn(
          FwIndexType portNum, //!< The port number
          U32 data //!< The data
      );

    protected:

      // ----------------------------------------------------------------------
      // Getters for port counts
      // ----------------------------------------------------------------------

      //! Get the number of to_dataIn ports
      //!
      //! \return The number of to_dataIn ports
      FwIndexType getNum_to_dataIn() const;

      //! Get the number of from_dataOut ports
      //!
      //! \return The number of from_dataOut ports
      FwIndexType getNum_from_dataOut() const;

    protected:

      // ----------------------------------------------------------------------
      // Connection status queries for to ports
      // ----------------------------------------------------------------------

      //! Check whether port to_dataIn is connected
      //!
      //! \return Whether port to_dataIn is connected
      bool isConnected_to_dataIn(
          FwIndexType portNum //!< The port number
      );

    protected:

      // ----------------------------------------------------------------------
      // History functions
      // ----------------------------------------------------------------------

      //! Clear all history
      void clearHistory();

      //! Clear from port history
      void clearFromPortHistory();

      //! Push an entry on the history for from_dataOut
      void pushFromPortEntry_dataOut(
          U32 data //!< The data
      );

    private:

      // ----------------------------------------------------------------------
      // Static functions for output ports
      // ----------------------------------------------------------------------

      //! Static function for port from_dataOut
      static void from_dataOut_static(
          Fw::PassiveComponentBase* const callComp, //!< The component instance
          FwIndexType portNum, //!< The port number
          U32 data //!< The data
      );

    protected:

      // ----------------------------------------------------------------------
      // History member variables
      // ----------------------------------------------------------------------

      //! The total number of port entries
      U32 fromPortHistorySize;

      //! The history for from_dataOut
      History<FromPortEntry_dataOut>* fromPortHistory_dataOut;

    private:

      // ----------------------------------------------------------------------
      // To ports
      // ----------------------------------------------------------------------

      //! To port connected to dataIn
      FppTest::OutputDataPort m_to_dataIn[1];

    private:

      // ----------------------------------------------------------------------
      // From ports
      // ----------------------------------------------------------------------

      //! From port connected to dataOut
      FppTest::InputDataPort m_from_dataOut[1];

  };

}

#endif
