#!/bin/sh

if ! test $# -eq 1
then
  echo 'usage: gen-cov file-base' 1>&2
  exit 1
fi

base=$1
fpp_test=../build-fprime-automatic-native-ut/FppTest
src=`find $fpp_test -name $base.cpp`
gcov -o $base.gcno $src
