[package]
name = "fprime_spacewasm"
version = "0.0.0"
edition = "2024"
publish = false

[lib]
name = "fprime_spacewasm"
crate-type = ["staticlib"]

[dependencies]

# We will provide the panic handler and allocator
# spacewasm_c_api = { git = "https://github.com/nasa/spacewasm.git", branch = "main", default-features = false, features = []}
# spacewasm = { git = "https://github.com/nasa/spacewasm.git", branch = "main" }
spacewasm_c_api = { version = "0.5.1", default-features = false, features = ["provide-panic-handler"] }
spacewasm = "0.5.1"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
panic = "abort"
strip = false

[profile.dev]
panic = "abort"
strip = false
