name: 'Setup External Repository w/ Branch Setup'
description: 'Setup the F´ repository and tools'
inputs:
  target_repository:
    description: "External repository to checkout (<owner>/<repo>)"
    required: true
    type: string
  fprime_location:
    description: "Relative path from the external project root to its F´ submodule"
    required: false
    type: string
    default: "./lib/fprime"
  target_ref:
    description: "Branch on target repository to checkout"
    required: false
    type: string
    default: "devel"
runs:
  using: "composite"
  steps:
    - name: "Checkout target repository"
      uses: actions/checkout@v4
      with:
        submodules: recursive 
      repository: ${{ inputs.target_repository }}
      ref: ${{ inputs.target_ref }}
    - name: "Overlay current F´ revision"
      uses: actions/checkout@v4
      with:
        submodules: true
        path: ${{ inputs.fprime_location }}
    - name: "Install requirements.txt"
      run: |
        pip3 install -r ${{ inputs.fprime_location }}/requirements.txt
        if [ -f ./requirements.txt ]
        then
            pip3 install -r ./requirements.txt
        fi
      shell: bash