== The MathOp Type

In F Prime, a *type definition* defines a kind of data that you can pass
between components or use in commands and telemetry.

For this tutorial, we need one type definition.
It defines an enumeration called `MathOp`, which
represents a mathematical operation.

We will add the specification for the `MathOp` type to the
`Ref` topology.
We will do this in three stages:

. Construct the FPP model.
. Add the model to the project.
. Build the model.

=== Construct the FPP Model

*Create the MathTypes directory:*
Go to the directory `Ref` at the top-level of the
F Prime repository and run `mkdir MathTypes`.
This step creates a new directory `Ref/MathTypes`.
This directory will contain our new type.

*Create the FPP model file:*
Now go into the directory `Ref/MathTypes`.
In that directory, create a file `MathTypes.fpp` with the following contents:

[source,fpp]
----
include::../MathTypes/MathTypes.fpp[]
----

You can do this by typing, or by copy-paste.

This file defines an enumeration or *enum*
with enumerated constants `ADD`, `SUB`, `MUL`, and `DIV`.
These four constants represent the operations
of addition, subtraction, multiplication, and division.
The enum also defines a type `MathOp`; the enumerated
constants are the values of this type.
For more information on enums, see
https://fprime-community.github.io/fpp/fpp-users-guide.html#Defining-Enums[_The FPP User's Guide_].

The enum `MathTypes` resides in an FPP module `Ref`.
An FPP module is like a {cpp} namespace: it encloses
several definitions, each of which is qualified with the
name of the module.
For more information on FPP modules, see
https://fprime-community.github.io/fpp/fpp-users-guide.html#Defining-Modules[_The FPP User's Guide_].

The text following a symbol `@` or `@<` is called an
*annotation*.
These annotations are carried through the parsing and
become comments in the generated code.
For more information, see
https://fprime-community.github.io/fpp/fpp-users-guide.html#Writing-Comments-and-Annotations[_The FPP User's Guide_].


[[types_add]]
=== Add the Model to the Project

*Create Ref/MathTypes/CMakeLists.txt:*
Create a file `Ref/MathTypes/CMakeLists.txt` with the following contents:

[source,cmake]
----
set(SOURCE_FILES
  "${CMAKE_CURRENT_LIST_DIR}/MathTypes.fpp"
)

register_fprime_module()
----

This code will tell the build system how to build the FPP model.

*Update Ref/CMakeLists.txt:*
Now we need to add the new directory to the `Ref` project.
To do that, open the file `Ref/CMakeLists.txt`.
This file should already exist; it was put there by the developers
of the `Ref` topology.
In this file, you should see several lines starting with `add_fprime_subdirectory`.
Immediately after the last of those lines, add the following new line:

[source,cmake]
----
add_fprime_subdirectory("${CMAKE_CURRENT_LIST_DIR}/MathTypes/")
----

[[types_build]]
=== Build the Model

*Run the build:*
Do the following:

. Go to the directory `Ref/MathTypes`.
. If you have not already run `fprime-util generate`, then do so now.
. Run the command `fprime-util build`.

The output should indicate that the model built without any errors.
If not, try to identify and correct what is wrong,
either by deciphering the error output, or by going over the steps again.
If you get stuck, you can look at the <<types_ref,reference implementation>>.

*Inspect the generated code:*
Now go to the directory `Ref/build-fprime-automatic-native/Ref/MathTypes`
(you may want to use `pushd`, or do this in a separate shell).
The directory `build-fprime-automatic-native` is where all the
generated code lives for the "automatic native" build of the `Ref`
project.
Within that directory is a directory tree that mirrors the project
structure.
In particular, `Ref/build-fprime-automatic-native/Ref/MathTypes`
contains the generated code for `Ref/MathTypes`.

Run `ls`.
You should see something like this:

[source,bash]
----
CMakeFiles            MathOpEnumAc.cpp      MathOpEnumAi.xml.prev cmake_install.cmake
Makefile              MathOpEnumAc.hpp      autocoder
----

The files `MathOpEnumAc.hpp` and
`MathOpEnumAc.cpp` are the auto-generated {cpp} files
corresponding to the `MathOp` enum.
You may wish to study the file `MathOpEnumAc.hpp`.
This file gives the interface to the {cpp} class `Ref::MathOp`.
All enum types have a similar auto-generated class
interface.

[[types_ref]]
=== Reference Implementation

A reference implementation for this section is available at
`docs/Tutorials/MathTutorial/MathTypes`.
To build this implementation from a clean repostiory,
do the following:

. Go to the `Ref` directory.

. Run `cp -R docs/Tutorials/MathTutorial/MathTypes .`

. Update `Ref/CMakeLists.txt` as stated
<<types_add,above>>.

. Follow the steps for <<types_build,building the model>>.

If you have modified the repo, revise the steps accordingly.
For example, switch git branches, use `git stash` to stash
your changes, or move `MathTypes` to another directory such
as `MathTypes-saved`.
