== The MathReceiver Component

Now we build and test the `MathReceiver` component.
We use the same five steps as for the
<<math-sender,`MathSender` component>>.

=== Construct the FPP Model

*Create the MathReceiver directory:*
Create the directory `Ref/MathReceiver`.

*Create the FPP model file:*
In directory `Ref/MathReceiver`, create a file
`MathReceiver.fpp` with the following contents:

[source,fpp]
----
include::../../../../Ref/MathReceiver/MathReceiver.fpp[]
----

This code defines a component `Ref.MathReceiver`.
The component is *queued*, which means it has a queue
but no thread.
Work occurs when the thread of another component invokes
the `schedIn` port of this component.

We have divided the specifiers of this component into six groups:

. *General ports:* There are three ports:
an input port `mathOpIn` for receiving a math operation,
an output port `mathResultOut` for sending a math result, and
an input port `schedIn` for receiving invocations from the scheduler.
`mathOpIn` is asynchronous.
That means invocations of `mathOpIn` put messages on a queue.
`schedIn` is synchronous.
That means invocations of `schedIn` immediately call the
handler function to do work.

. *Special ports:* 
As before, there are special ports for commands, events, telemetry,
and time.
There are also special ports for getting and setting parameters.
We will explain the function of these ports below.

. *Parameters:* There is one *parameter*.
A parameter is a constant that is configurable by command.
In this case there is one parameter `FACTOR`.
It has the default value 1.0 until its value is changed by command.
When doing math, the `MathReceiver` component performs the requested
operation and then multiplies by this factor.
For example, if the arguments of the `mathOpIn` port
are _v1_, `ADD`, and _v2_, and the factor is _f_,
then the result sent on `mathResultOut` is
_(v1 + v2) f_.

. *Events:* There are three event reports:

.. `FACTOR_UPDATED`: Emitted when the `FACTOR` parameter
is updated by command.
This event is *throttled* to a limit of three.
That means that after the event is emitted three times
it will not be emitted any more, until the throttling
is cleared by command (see below).

.. `OPERATION_PERFORMED`: Emitted when this component
performs a math operation.

.. `THROTTLE_CLEARED`: Emitted when the event throttling
is cleared.

. *Commands:* There is one command for clearing
the event throttle.

. *Telemetry:* 
There two telemetry channels: one for reporting
the last operation received and one for reporting
the factor parameter.

For the parameters, events, commands, and telemetry, we chose
to put in all the opcodes and identifiers explicitly.
These can also be left implicit, as in the `MathSender`
component example.
For more information, see
https://fprime-community.github.io/fpp/fpp-users-guide.html#Defining-Components[_The FPP User's Guide_].

=== Add the Model to the Project

Follow the same steps as for the
<<math-sender_add-model,`MathSender` component>>.

=== Build the Stub Implementation

Follow the same steps as for the
<<math-sender_build-stub,`MathSender` component>>.

=== Complete the Implementation

TODO

=== Write and Run Unit Tests

TODO
