// ======================================================================
// \title  BTesterBase.cpp
// \author Generated by fpp-to-cpp
// \brief  cpp file for B component test harness base class
// ======================================================================

#include <cstdlib>
#include <cstring>

#include "FppTest/topology/components/B/BTesterBase.hpp"

namespace FppTest {

  // ----------------------------------------------------------------------
  // Component initialization
  // ----------------------------------------------------------------------

  void BTesterBase ::
    init(FwEnumStoreType instance)
  {
    // Initialize base class
    Fw::PassiveComponentBase::init(instance);

    // Connect input port dataOut
    for (
      FwIndexType port = 0;
      port < static_cast<FwIndexType>(this->getNum_from_dataOut());
      port++
    ) {
      this->m_from_dataOut[port].init();
      this->m_from_dataOut[port].addCallComp(
        this,
        from_dataOut_static
      );
      this->m_from_dataOut[port].setPortNum(port);

#if FW_OBJECT_NAMES == 1
      Fw::ObjectName portName;
      portName.format(
        "%s_from_dataOut[%" PRI_FwIndexType "]",
        this->m_objName.toChar(),
        port
      );
      this->m_from_dataOut[port].setObjName(portName.toChar());
#endif
    }

    // Connect output port dataIn
    for (
      FwIndexType port = 0;
      port < static_cast<FwIndexType>(this->getNum_to_dataIn());
      port++
    ) {
      this->m_to_dataIn[port].init();

#if FW_OBJECT_NAMES == 1
      Fw::ObjectName portName;
      portName.format(
        "%s_to_dataIn[%" PRI_FwIndexType "]",
        this->m_objName.toChar(),
        port
      );
      this->m_to_dataIn[port].setObjName(portName.toChar());
#endif
    }
  }

  // ----------------------------------------------------------------------
  // Connectors for to ports
  // ----------------------------------------------------------------------

  void BTesterBase ::
    connect_to_dataIn(
        FwIndexType portNum,
        FppTest::InputDataPort* port
    )
  {
    FW_ASSERT(
      (0 <= portNum) && (portNum < this->getNum_to_dataIn()),
      static_cast<FwAssertArgType>(portNum)
    );

    this->m_to_dataIn[portNum].addCallPort(port);
  }

  // ----------------------------------------------------------------------
  // Getters for from ports
  // ----------------------------------------------------------------------

  FppTest::InputDataPort* BTesterBase ::
    get_from_dataOut(FwIndexType portNum)
  {
    FW_ASSERT(
      (0 <= portNum) && (portNum < this->getNum_from_dataOut()),
      static_cast<FwAssertArgType>(portNum)
    );

    return &this->m_from_dataOut[portNum];
  }

  // ----------------------------------------------------------------------
  // Component construction and destruction
  // ----------------------------------------------------------------------

  BTesterBase ::
    BTesterBase(
        const char* const compName,
        const U32 maxHistorySize
    ) :
      Fw::PassiveComponentBase(compName)
  {
    // Initialize port histories
    this->fromPortHistory_dataOut = new History<FromPortEntry_dataOut>(maxHistorySize);

    // Clear history
    this->clearHistory();
  }

  BTesterBase ::
    ~BTesterBase()
  {
    // Destroy port histories
    delete this->fromPortHistory_dataOut;
  }

  // ----------------------------------------------------------------------
  // Default handler implementations for typed from ports
  // You can override these implementation with more specific behavior
  // ----------------------------------------------------------------------

  void BTesterBase ::
    from_dataOut_handler(
        FwIndexType portNum,
        U32 data
    )
  {
    this->pushFromPortEntry_dataOut(data);
  }

  // ----------------------------------------------------------------------
  // Handler base-class functions for from ports
  // ----------------------------------------------------------------------

  void BTesterBase ::
    from_dataOut_handlerBase(
        FwIndexType portNum,
        U32 data
    )
  {
    // Make sure port number is valid
    FW_ASSERT(
      (0 <= portNum) && (portNum < this->getNum_from_dataOut()),
      static_cast<FwAssertArgType>(portNum)
    );
    this->from_dataOut_handler(
      portNum,
      data
    );
  }

  // ----------------------------------------------------------------------
  // Invocation functions for to ports
  // ----------------------------------------------------------------------

  void BTesterBase ::
    invoke_to_dataIn(
        FwIndexType portNum,
        U32 data
    )
  {
    // Make sure port number is valid
    FW_ASSERT(
      (0 <= portNum) && (portNum < this->getNum_to_dataIn()),
      static_cast<FwAssertArgType>(portNum)
    );
    this->m_to_dataIn[portNum].invoke(
      data
    );
  }

  // ----------------------------------------------------------------------
  // Getters for port counts
  // ----------------------------------------------------------------------

  FwIndexType BTesterBase ::
    getNum_to_dataIn() const
  {
    return static_cast<FwIndexType>(FW_NUM_ARRAY_ELEMENTS(this->m_to_dataIn));
  }

  FwIndexType BTesterBase ::
    getNum_from_dataOut() const
  {
    return static_cast<FwIndexType>(FW_NUM_ARRAY_ELEMENTS(this->m_from_dataOut));
  }

  // ----------------------------------------------------------------------
  // Connection status queries for to ports
  // ----------------------------------------------------------------------

  bool BTesterBase ::
    isConnected_to_dataIn(FwIndexType portNum)
  {
    FW_ASSERT(
      (0 <= portNum) && (portNum < this->getNum_to_dataIn()),
      static_cast<FwAssertArgType>(portNum)
    );

    return this->m_to_dataIn[portNum].isConnected();
  }

  // ----------------------------------------------------------------------
  // History functions
  // ----------------------------------------------------------------------

  void BTesterBase ::
    clearHistory()
  {
    this->clearFromPortHistory();
  }

  void BTesterBase ::
    clearFromPortHistory()
  {
    this->fromPortHistorySize = 0;
    this->fromPortHistory_dataOut->clear();
  }

  void BTesterBase ::
    pushFromPortEntry_dataOut(U32 data)
  {
    FromPortEntry_dataOut _e;
    _e.data = data;
    this->fromPortHistory_dataOut->push_back(_e);
    this->fromPortHistorySize++;
  }

  // ----------------------------------------------------------------------
  // Dispatching helper functions
  // ----------------------------------------------------------------------

  BComponentBase::MsgDispatchStatus BTesterBase ::
    dispatchOne(BComponentBase& component)
  {
        // Dispatch one message returning status
        return component.doDispatch();
  }

  BComponentBase::MsgDispatchStatus BTesterBase ::
    dispatchCurrentMessages(BComponentBase& component)
  {
        // Dispatch all current messages unless ERROR or EXIT occur
        const FwSizeType currentMessageCount = component.m_queue.getMessagesAvailable();
        BComponentBase::MsgDispatchStatus messageStatus = BComponentBase::MsgDispatchStatus::MSG_DISPATCH_EMPTY;
        for (FwSizeType i = 0; i < currentMessageCount; i++) {
            messageStatus = component.doDispatch();
            if (messageStatus != BComponentBase::MSG_DISPATCH_OK) {
                break;
            }
        }
        return messageStatus;
  }

  // ----------------------------------------------------------------------
  // Static functions for output ports
  // ----------------------------------------------------------------------

  void BTesterBase ::
    from_dataOut_static(
        Fw::PassiveComponentBase* const callComp,
        FwIndexType portNum,
        U32 data
    )
  {
    FW_ASSERT(callComp != nullptr);
    BTesterBase* _testerBase = static_cast<BTesterBase*>(callComp);
    _testerBase->from_dataOut_handlerBase(
      portNum,
      data
    );
  }

}
