// ======================================================================
// \title  BTesterHelpers.cpp
// \author Generated by fpp-to-cpp
// \brief  cpp file for B component test harness helper functions
// ======================================================================

#include "BTester.hpp"

namespace FppTest {

  // ----------------------------------------------------------------------
  // Helper functions
  // ----------------------------------------------------------------------

  void BTester ::
    connectPorts()
  {
    // Connect typed input ports

    this->connect_to_dataIn(
      0,
      this->component.get_dataIn_InputPort(0)
    );

    // Connect typed output ports

    this->component.set_dataOut_OutputPort(
      0,
      this->get_from_dataOut(0)
    );
  }

  void BTester ::
    initComponents()
  {
    this->init();
    this->component.init(BTester::TEST_INSTANCE_QUEUE_DEPTH, BTester::TEST_INSTANCE_ID);
  }

}
