@ The number of Load commands executed
telemetry CS_LoadCommands: U32 id 0

@ The number of Cancel commands executed
telemetry CS_CancelCommands: U32 id 1

@ The number of errors that have occurred
telemetry CS_Errors: U32 id 2

@ The number of commands executed across all sequences.
telemetry CS_CommandsExecuted: U32 id 3

@ The number of sequences completed.
telemetry CS_SequencesCompleted: U32 id 4
