#!/bin/sh -e

dir=`dirname $0`
cd $dir

build_cache=../build-fprime-automatic-native-ut

./build-ut
dp_exe_base=FppTest_dp_ut_exe
dp_exe=`find $build_cache/bin -name $dp_exe_base`
cp $dp_exe .
./$dp_exe_base
