#!/bin/sh -e

dir=`dirname $0`
cd $dir

# Clear the build cache
build_cache=../build-fprime-automatic-native-ut/FppTest/dp
for file in `find $build_cache -name '*.hpp' -or -name '*.cpp'`
do
  rm $file
done
