#!/bin/sh

export FPRIME_ROOT=`cd ../..; echo $PWD`

fpp-to-xml -p $FPRIME_ROOT \
  -i $FPRIME_ROOT/config/FpConfig.fpp \
  Prm.fpp
# Codegen workarounds
for name in PrmGet PrmSet
do
  xml_file=$name'PortAi.xml'
  cat $xml_file | \
    # Suppress header for FwPrmIdType
    awk '/FwPrmIdType\.hpp/ { next } { print }' | \
    # Fix return type
    sed 's/return type="ParamValid"/return type="Fw::ParamValid"/' > tmp.xml
  mv tmp.xml $xml_file
done
