#!/bin/sh

export FPRIME_ROOT=`cd ../..; echo $PWD`

fpp-to-xml -p $FPRIME_ROOT \
  -i $FPRIME_ROOT/config/FpConfig.fpp \
  Prm.fpp
# Suppress header file import for FwPrmIdType
for name in PrmGet PrmSet
do
  xml_file=$name'PortAi.xml'
  awk '/FwPrmIdType\.hpp/ { next } { print }' < $xml_file > tmp.xml
  mv tmp.xml $xml_file
done
