/*
    This file has been autogenerated using [generate_version_info.py].
    This file may be overwritten.
*/
#include "versions/version.hpp"

namespace Project {

    const char* const Version::FRAMEWORK_VERSION = "v3.4.3-107-gf80da30ba";
    const char* const Version::PROJECT_VERSION = "v3.4.3-107-gf80da30ba";
    const FwIndexType Version::LIBRARY_VERSIONS_COUNT = 12; 
    const char* const Version::LIBRARY_VERSIONS[] = { 
        "blah0 @ blah0", "blah1 @ blah1", "blah2 @ blah2", "blah3 @ blah3", "blah4 @ blah4",   "blah5 @ blah5",
        "blah6 @ blah6", "blah7 @ blah7", "blah8 @ blah8", "blah9 @ blah9", "blah10 @ blah10", "blah11 @ blah11",
    };
}  // namespace Project
