.TH "gov.nasa.jpl.componentaction.LoadIDConfig" 3 "Tue Aug 9 2016" "Version 4.3" "MagicDrawCompPlugin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gov.nasa.jpl.componentaction.LoadIDConfig \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBconfigItem\fP"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBprocess\fP (Project proj, File pluginDir)  throws IOException "
.br
.ti -1c
.RI "static void \fBchangeModel\fP (Element root, Project proj, Map< String, \fBconfigItem\fP > configMap)  throws LoadIDException"
.br
.ti -1c
.RI "static Map< String, \fBconfigItem\fP > \fBvalidateAndProcessConfig\fP (File config)  throws LoadIDException"
.br
.ti -1c
.RI "static File \fBgetConfigFile\fP (File projectFile)  throws LoadIDException"
.br
.in -1c
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "\fBLoadIDConfig\fP ()"
.br
.in -1c
.SS "Static Private Attributes"

.in +1c
.ti -1c
.RI "static Project \fBproject\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBLoadIDConfig\fP allows the user to specify a config CSV that will modify all the baseIDs and window ranges within the model\&. This allows users to have isfgen generate IDs and use them in the future by adding them into the models\&.
.PP
Exceptions are generated when anything does not conform to what is expected, including file types, file column amounts, and mismatches between the config file and the model\&.
.PP
The format of the config file is so: 
.PP
component,instance,base_id,base_window_range 
.PP
SignalGen,SG1,10,15 
.PP
\&.\&.\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "gov\&.nasa\&.jpl\&.componentaction\&.LoadIDConfig\&.LoadIDConfig ()\fC [private]\fP"

.SH "Member Function Documentation"
.PP 
.SS "static void gov\&.nasa\&.jpl\&.componentaction\&.LoadIDConfig\&.changeModel (Element root, Project proj, Map< String, \fBconfigItem\fP > configMap) throws \fBLoadIDException\fP\fC [static]\fP"
This function goes through the model and matches each component with its respective instance within the configMap\&.
.PP
If there isn't any discrepancies between the model and the config files, baseIDs and window ranges are set to the values from the config file\&.
.PP
All subsystems have their base IDs set to zero\&.
.PP
\fBParameters:\fP
.RS 4
\fIroot\fP 
.br
\fIproj\fP 
.br
\fIconfigMap\fP 
.RE
.PP
\fBExceptions:\fP
.RS 4
\fI\fBLoadIDException\fP\fP 
.RE
.PP

.SS "static File gov\&.nasa\&.jpl\&.componentaction\&.LoadIDConfig\&.getConfigFile (File projectFile) throws \fBLoadIDException\fP\fC [static]\fP"
Opens up a file chooser box for the user to select what config CSV file to choose\&.
.PP
The input argument projectFile is used to specify a starting path\&.
.PP
\fBParameters:\fP
.RS 4
\fIprojectFile\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
A config file object 
.RE
.PP
\fBExceptions:\fP
.RS 4
\fI\fBLoadIDException\fP\fP 
.RE
.PP

.SS "static void gov\&.nasa\&.jpl\&.componentaction\&.LoadIDConfig\&.process (Project proj, File pluginDir) throws IOException\fC [static]\fP"
process handles all the phases of this methodology\&.
.PP
\fBParameters:\fP
.RS 4
\fIproj\fP Project object 
.br
\fIpluginDir\fP Directory to generate documents into 
.RE
.PP
\fBExceptions:\fP
.RS 4
\fIIOException\fP 
.RE
.PP

.SS "static Map<String , \fBconfigItem\fP> gov\&.nasa\&.jpl\&.componentaction\&.LoadIDConfig\&.validateAndProcessConfig (File config) throws \fBLoadIDException\fP\fC [static]\fP"
Validates and processes the input config file\&.
.PP
Checks if the file is valid, is a \&.CSV, and has four items per row\&.
.PP
This also constructs a map where the key is an instance name and the value is a \fBconfigItem\fP that holds the associated names and IDs\&.
.PP
\fBParameters:\fP
.RS 4
\fIconfig\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
.RE
.PP
\fBExceptions:\fP
.RS 4
\fI\fBLoadIDException\fP\fP 
.RE
.PP

.SH "Member Data Documentation"
.PP 
.SS "Project gov\&.nasa\&.jpl\&.componentaction\&.LoadIDConfig\&.project\fC [static]\fP, \fC [private]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for MagicDrawCompPlugin from the source code\&.
