.TH "gov.nasa.jpl.componentaction.MainMenuConfigurator" 3 "Tue Aug 9 2016" "Version 4.3" "MagicDrawCompPlugin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gov.nasa.jpl.componentaction.MainMenuConfigurator \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits AMConfigurator\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMainMenuConfigurator\fP (NMAction \fBaction\fP)"
.br
.ti -1c
.RI "void \fBconfigure\fP (ActionsManager mngr)"
.br
.ti -1c
.RI "int \fBgetPriority\fP ()"
.br
.in -1c
.SS "Package Attributes"

.in +1c
.ti -1c
.RI "String \fBMPMCS\fP ='Component Autocoder'"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "NMAction \fBaction\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Class for configuring main menu and adding new submenu\&. 
.PP
\fBVersion:\fP
.RS 4

.RE
.PP
\fBDate\fP
.RS 4
2007-10-05 09:51:43 +0300 (Fri, 05 Oct 2007) 
.RE
.PP
\fBRevision\fP
.RS 4
52410 
.RE
.PP
\fBAuthor:\fP
.RS 4
Donatas Simkunas 
.RE
.PP

.SH "Constructor & Destructor Documentation"
.PP 
.SS "gov\&.nasa\&.jpl\&.componentaction\&.MainMenuConfigurator\&.MainMenuConfigurator (NMAction action)"
Creates configurator\&. 
.PP
\fBParameters:\fP
.RS 4
\fIaction\fP action to be added to main menu\&. 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "void gov\&.nasa\&.jpl\&.componentaction\&.MainMenuConfigurator\&.configure (ActionsManager mngr)"

.PP
\fBSee also:\fP
.RS 4
com\&.nomagic\&.actions\&.AMConfigurator::configure(ActionsManager) Methods adds \fBaction\fP to given manager Examples category\&. 
.RE
.PP

.SS "int gov\&.nasa\&.jpl\&.componentaction\&.MainMenuConfigurator\&.getPriority ()"

.SH "Member Data Documentation"
.PP 
.SS "NMAction gov\&.nasa\&.jpl\&.componentaction\&.MainMenuConfigurator\&.action\fC [private]\fP"
Action will be added to manager\&. 
.SS "String gov\&.nasa\&.jpl\&.componentaction\&.MainMenuConfigurator\&.MPMCS ='Component Autocoder'\fC [package]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for MagicDrawCompPlugin from the source code\&.
