.TH "gov.nasa.jpl.componentaction.IsfXmlAction" 3 "Tue Aug 9 2016" "Version 4.3" "MagicDrawCompPlugin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gov.nasa.jpl.componentaction.IsfXmlAction \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits MDAction\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBIsfXmlAction\fP (String id, String name, File \fBpluginDir\fP)"
.br
.ti -1c
.RI "void \fBactionPerformed\fP (ActionEvent e)"
.br
.in -1c
.SS "Package Attributes"

.in +1c
.ti -1c
.RI "File \fBpluginDir\fP"
.br
.in -1c
.SS "Static Private Attributes"

.in +1c
.ti -1c
.RI "static final long \fBserialVersionUID\fP = \-6790954285526957354L"
.br
.in -1c
.SH "Detailed Description"
.PP 
Used to generate component, port, and topology XML files\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "gov\&.nasa\&.jpl\&.componentaction\&.IsfXmlAction\&.IsfXmlAction (String id, String name, File pluginDir)"

.SH "Member Function Documentation"
.PP 
.SS "void gov\&.nasa\&.jpl\&.componentaction\&.IsfXmlAction\&.actionPerformed (ActionEvent e)"
Runs the \fBProcessISFProject\&.process\fP and the \fBProcessISFTopology\&.process\fP functions\&.
.PP
\fBSee also:\fP
.RS 4
java\&.awt\&.event\&.ActionListener::actionPerformed(java\&.awt\&.event\&.ActionEvent) 
.RE
.PP

.SH "Member Data Documentation"
.PP 
.SS "File gov\&.nasa\&.jpl\&.componentaction\&.IsfXmlAction\&.pluginDir\fC [package]\fP"

.SS "final long gov\&.nasa\&.jpl\&.componentaction\&.IsfXmlAction\&.serialVersionUID = \-6790954285526957354L\fC [static]\fP, \fC [private]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for MagicDrawCompPlugin from the source code\&.
