.TH "gov.nasa.jpl.componentaction.LoadIDConfig.configItem" 3 "Tue Aug 9 2016" "Version 4.3" "MagicDrawCompPlugin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gov.nasa.jpl.componentaction.LoadIDConfig.configItem \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBconfigItem\fP (String compType, String instName, int bID, int wRange)"
.br
.ti -1c
.RI "int \fBhashCode\fP ()"
.br
.ti -1c
.RI "boolean \fBequals\fP (Object obj)"
.br
.ti -1c
.RI "String \fBtoString\fP ()"
.br
.in -1c
.SS "Package Attributes"

.in +1c
.ti -1c
.RI "String \fBcomponentType\fP"
.br
.ti -1c
.RI "String \fBinstanceName\fP"
.br
.ti -1c
.RI "int \fBbaseID\fP"
.br
.ti -1c
.RI "int \fBwindowRange\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Used to store information for each configuration item from the config file\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "gov\&.nasa\&.jpl\&.componentaction\&.LoadIDConfig\&.configItem\&.configItem (String compType, String instName, int bID, int wRange)"

.SH "Member Function Documentation"
.PP 
.SS "boolean gov\&.nasa\&.jpl\&.componentaction\&.LoadIDConfig\&.configItem\&.equals (Object obj)"

.SS "int gov\&.nasa\&.jpl\&.componentaction\&.LoadIDConfig\&.configItem\&.hashCode ()"

.SS "String gov\&.nasa\&.jpl\&.componentaction\&.LoadIDConfig\&.configItem\&.toString ()"

.SH "Member Data Documentation"
.PP 
.SS "int gov\&.nasa\&.jpl\&.componentaction\&.LoadIDConfig\&.configItem\&.baseID\fC [package]\fP"

.SS "String gov\&.nasa\&.jpl\&.componentaction\&.LoadIDConfig\&.configItem\&.componentType\fC [package]\fP"

.SS "String gov\&.nasa\&.jpl\&.componentaction\&.LoadIDConfig\&.configItem\&.instanceName\fC [package]\fP"

.SS "int gov\&.nasa\&.jpl\&.componentaction\&.LoadIDConfig\&.configItem\&.windowRange\fC [package]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for MagicDrawCompPlugin from the source code\&.
