.TH "gov.nasa.jpl.componentaction.ISFPort" 3 "Tue Aug 9 2016" "Version 4.3" "MagicDrawCompPlugin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gov.nasa.jpl.componentaction.ISFPort \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBISFPort\fP (Element \fBportElement\fP)"
.br
.ti -1c
.RI "String \fBgetNamespace\fP ()"
.br
.ti -1c
.RI "void \fBaddData\fP (Element dataElement)"
.br
.ti -1c
.RI "void \fBaddReturn\fP (Element dataElement)"
.br
.ti -1c
.RI "boolean \fBisReturnEnumeration\fP (Element dataElement)"
.br
.ti -1c
.RI "boolean \fBhasReturn\fP ()"
.br
.ti -1c
.RI "Element \fBgetReturn\fP ()"
.br
.ti -1c
.RI "String \fBgetReturnType\fP (Element dataElement)"
.br
.ti -1c
.RI "String \fBgetName\fP ()"
.br
.ti -1c
.RI "String[] \fBgetDataName\fP (Element dataElement)"
.br
.ti -1c
.RI "String \fBgetDataType\fP (Element dataElement)"
.br
.ti -1c
.RI "List< Element > \fBgetDataList\fP ()"
.br
.ti -1c
.RI "List< String > \fBgetIncludeList\fP ()"
.br
.ti -1c
.RI "List< EnumerationLiteral > \fBgetEnumItems\fP (Element dataElement)"
.br
.ti -1c
.RI "List< EnumerationLiteral > \fBgetReturnEnumItems\fP (Element dataElement)"
.br
.ti -1c
.RI "boolean \fBisEnumeration\fP (Element dataElement)"
.br
.ti -1c
.RI "String \fBgetPortTypeProperty\fP (Element dataElement, String property)"
.br
.ti -1c
.RI "String \fBgetDataTypeProperty\fP (Element \fBportElement\fP, String property)"
.br
.ti -1c
.RI "void \fBprint\fP ()"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "Element \fBportElement\fP"
.br
.ti -1c
.RI "List< Element > \fBdataList\fP"
.br
.ti -1c
.RI "Element \fBreturnVal\fP"
.br
.ti -1c
.RI "List< String > \fBincludeList\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "gov\&.nasa\&.jpl\&.componentaction\&.ISFPort\&.ISFPort (Element portElement)"
Creates an \fBISFPort\fP object 
.PP
\fBParameters:\fP
.RS 4
\fIportElement\fP Element of port type to be used in the creation of the object 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "void gov\&.nasa\&.jpl\&.componentaction\&.ISFPort\&.addData (Element dataElement)"
Adds Element to the dataList and checks to make sure the datatype is not empty before adding it to the includeList\&. 
.PP
\fBParameters:\fP
.RS 4
\fIdataElement\fP Element to be added 
.RE
.PP

.SS "void gov\&.nasa\&.jpl\&.componentaction\&.ISFPort\&.addReturn (Element dataElement)"
Adds Element to the includeList if the datatype is not empty\&. 
.PP
\fBParameters:\fP
.RS 4
\fIdataElement\fP 
.RE
.PP

.SS "List<Element> gov\&.nasa\&.jpl\&.componentaction\&.ISFPort\&.getDataList ()"
Returns the dataLIst 
.PP
\fBReturns:\fP
.RS 4
List of Elements 
.RE
.PP

.SS "String [] gov\&.nasa\&.jpl\&.componentaction\&.ISFPort\&.getDataName (Element dataElement)"
Checks if the dataElement is a reference or pointer and returns a list of Strings where the first value is the pass type and the second value is the name of the dataElement\&. 
.PP
\fBParameters:\fP
.RS 4
\fIdataElement\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
List of Strings 
.RE
.PP

.SS "String gov\&.nasa\&.jpl\&.componentaction\&.ISFPort\&.getDataType (Element dataElement)"
Returns the data type with the namespace property prepended to it\&. 
.PP
\fBParameters:\fP
.RS 4
\fIdataElement\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
namespace String 
.RE
.PP

.SS "String gov\&.nasa\&.jpl\&.componentaction\&.ISFPort\&.getDataTypeProperty (Element portElement, String property)"
Returns the property value of DataType stereotype of the input element argument\&.
.PP
\fBParameters:\fP
.RS 4
\fIdataElement\fP The Element in question\&. 
.br
\fIproperty\fP The parameter that is being accessed within the DataType stereotype 
.RE
.PP
\fBReturns:\fP
.RS 4
the associated value of the property in the DataType stereotype 
.RE
.PP

.SS "List<EnumerationLiteral> gov\&.nasa\&.jpl\&.componentaction\&.ISFPort\&.getEnumItems (Element dataElement)"
Returns the enumerated items of the datatype\&. 
.PP
\fBParameters:\fP
.RS 4
\fIdataElement\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
List of Enumeration Literal objects 
.RE
.PP

.SS "List<String> gov\&.nasa\&.jpl\&.componentaction\&.ISFPort\&.getIncludeList ()"
Returns the includeList 
.PP
\fBReturns:\fP
.RS 4
List of Strings 
.RE
.PP

.SS "String gov\&.nasa\&.jpl\&.componentaction\&.ISFPort\&.getName ()"
Returns the last part of the object name\&. 
.PP
\fBReturns:\fP
.RS 4
String name 
.RE
.PP

.SS "String gov\&.nasa\&.jpl\&.componentaction\&.ISFPort\&.getNamespace ()"
Return the port element's namespace 
.PP
\fBReturns:\fP
.RS 4
namespace string 
.RE
.PP

.SS "String gov\&.nasa\&.jpl\&.componentaction\&.ISFPort\&.getPortTypeProperty (Element dataElement, String property)"
Returns the property value of the PortType's stereotype of the input element argument\&.
.PP
\fBParameters:\fP
.RS 4
\fIdataElement\fP The Element in question\&. 
.br
\fIproperty\fP The parameter that is being accessed within the PortType stereotype 
.RE
.PP
\fBReturns:\fP
.RS 4
the associated value of the property in the PortType stereotype 
.RE
.PP

.SS "Element gov\&.nasa\&.jpl\&.componentaction\&.ISFPort\&.getReturn ()"
Returns the returnVal\&. 
.PP
\fBReturns:\fP
.RS 4
returnVal 
.RE
.PP

.SS "List<EnumerationLiteral> gov\&.nasa\&.jpl\&.componentaction\&.ISFPort\&.getReturnEnumItems (Element dataElement)"
Get enumeration items from a Port's Enumeration return type 
.PP
\fBParameters:\fP
.RS 4
\fIdataElement\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
.RE
.PP

.SS "String gov\&.nasa\&.jpl\&.componentaction\&.ISFPort\&.getReturnType (Element dataElement)"
Returns String based off the dataElement\&. 
.PP
\fBParameters:\fP
.RS 4
\fIdataElement\fP Input Element 
.RE
.PP
\fBReturns:\fP
.RS 4
ReturnType 
.RE
.PP

.SS "boolean gov\&.nasa\&.jpl\&.componentaction\&.ISFPort\&.hasReturn ()"
Checks if the returnVal is null\&. 
.PP
\fBReturns:\fP
.RS 4
True if the \fBISFPort\fP has a returnValue 
.RE
.PP

.SS "boolean gov\&.nasa\&.jpl\&.componentaction\&.ISFPort\&.isEnumeration (Element dataElement)"
Checks if the Type of the dataElement is an instance of Enumeration\&. 
.PP
\fBParameters:\fP
.RS 4
\fIdataElement\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
boolean 
.RE
.PP

.SS "boolean gov\&.nasa\&.jpl\&.componentaction\&.ISFPort\&.isReturnEnumeration (Element dataElement)"
Checks if the Element object is an instance of Enumeration\&. 
.PP
\fBParameters:\fP
.RS 4
\fIdataElement\fP Object to be checked 
.RE
.PP
\fBReturns:\fP
.RS 4
True if the Element is an instance of Enumeration 
.RE
.PP

.SS "void gov\&.nasa\&.jpl\&.componentaction\&.ISFPort\&.print ()"
Prints the name of the ISPort object\&. 
.SH "Member Data Documentation"
.PP 
.SS "List<Element> gov\&.nasa\&.jpl\&.componentaction\&.ISFPort\&.dataList\fC [private]\fP"

.SS "List<String> gov\&.nasa\&.jpl\&.componentaction\&.ISFPort\&.includeList\fC [private]\fP"

.SS "Element gov\&.nasa\&.jpl\&.componentaction\&.ISFPort\&.portElement\fC [private]\fP"

.SS "Element gov\&.nasa\&.jpl\&.componentaction\&.ISFPort\&.returnVal\fC [private]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for MagicDrawCompPlugin from the source code\&.
