.TH "gov.nasa.jpl.componentaction.ProcessISFProject" 3 "Tue Aug 9 2016" "Version 4.3" "MagicDrawCompPlugin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gov.nasa.jpl.componentaction.ProcessISFProject \- 
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBprocess\fP (Project proj, File pluginDir)  throws IOException "
.br
.ti -1c
.RI "static void \fBprocess\fP (Project proj, File pluginDir, String processPackage)  throws IOException "
.br
.in -1c
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "\fBProcessISFProject\fP ()"
.br
.in -1c
.SS "Static Private Member Functions"

.in +1c
.ti -1c
.RI "static void \fBprocessPorts\fP (List< Element > portElementList)  throws PortException "
.br
.ti -1c
.RI "static void \fBprocessComponents\fP (List< Element > compElementList, String stereotype)  throws PortException "
.br
.ti -1c
.RI "static List< Element > \fBgetElementsOfStereotype\fP (String stereotype)"
.br
.ti -1c
.RI "static List< Element > \fBgetElementsOfStereotypeAndPackage\fP (String stereotype, String processPackage)"
.br
.in -1c
.SS "Static Private Attributes"

.in +1c
.ti -1c
.RI "static Project \fBproject\fP"
.br
.ti -1c
.RI "static List< \fBISFComponent\fP > \fBcomponentList\fP"
.br
.ti -1c
.RI "static List< \fBISFPort\fP > \fBportList\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
This singleton class will process an ISF Project\&.
.PP
\fBAuthor:\fP
.RS 4
Garth Watney 
.RE
.PP

.SH "Constructor & Destructor Documentation"
.PP 
.SS "gov\&.nasa\&.jpl\&.componentaction\&.ProcessISFProject\&.ProcessISFProject ()\fC [private]\fP"

.SH "Member Function Documentation"
.PP 
.SS "static List<Element> gov\&.nasa\&.jpl\&.componentaction\&.ProcessISFProject\&.getElementsOfStereotype (String stereotype)\fC [static]\fP, \fC [private]\fP"
Returns a list of elements with specified input stereotype string\&. 
.PP
\fBParameters:\fP
.RS 4
\fIstereotype\fP stereotype string to look for 
.RE
.PP
\fBReturns:\fP
.RS 4
list of Elements 
.RE
.PP

.SS "static List<Element> gov\&.nasa\&.jpl\&.componentaction\&.ProcessISFProject\&.getElementsOfStereotypeAndPackage (String stereotype, String processPackage)\fC [static]\fP, \fC [private]\fP"
Returns a list of elements with specified input stereotype string and within the processPackage\&. 
.PP
\fBParameters:\fP
.RS 4
\fIstereotype\fP stereotype string to look for 
.br
\fIprocessPackage\fP package string to look for 
.RE
.PP
\fBReturns:\fP
.RS 4
list of Elements 
.RE
.PP

.SS "static void gov\&.nasa\&.jpl\&.componentaction\&.ProcessISFProject\&.process (Project proj, File pluginDir) throws IOException\fC [static]\fP"
Main function to process the project\&.
.PP
.PD 0
.IP "\(bu" 2
Creates a directory to output XML files into if it does not already exist\&.  
.IP "\(bu" 2
Processes all the components in the model and generates an XML file for each of them\&.  
.IP "\(bu" 2
Processes all the ports in the model and generates an XML file to store all the port data\&.  
.PP
.PP
\fBParameters:\fP
.RS 4
\fIproj\fP Project object 
.br
\fIpluginDir\fP Folder to create XML folder in 
.RE
.PP
\fBExceptions:\fP
.RS 4
\fIIOException\fP 
.RE
.PP

.SS "static void gov\&.nasa\&.jpl\&.componentaction\&.ProcessISFProject\&.process (Project proj, File pluginDir, String processPackage) throws IOException\fC [static]\fP"
Function to process the project, except restricts component search to the processPackage\&.
.PP
.PD 0
.IP "\(bu" 2
Creates a directory to output XML files into if it does not already exist\&.  
.IP "\(bu" 2
Processes all the components in the processPackage and generates an XML file for each of them\&.  
.IP "\(bu" 2
Processes all the ports in the processPackage and generates an XML file to store all the port data\&.  
.PP
.PP
\fBParameters:\fP
.RS 4
\fIproj\fP Project object 
.br
\fIpluginDir\fP Folder to create XML folder in 
.br
\fIprocessPackage\fP String of the process package 
.RE
.PP
\fBExceptions:\fP
.RS 4
\fIIOException\fP 
.RE
.PP

.SS "static void gov\&.nasa\&.jpl\&.componentaction\&.ProcessISFProject\&.processComponents (List< Element > compElementList, String stereotype) throws \fBPortException\fP\fC [static]\fP, \fC [private]\fP"
Creates \fBISFComponent\fP objects for all components with associated ports and adds them toe the componentList\&. 
.PP
\fBParameters:\fP
.RS 4
\fIcompElementList\fP 
.br
\fIstereotype\fP 
.RE
.PP
\fBExceptions:\fP
.RS 4
\fI\fBPortException\fP\fP 
.RE
.PP

.SS "static void gov\&.nasa\&.jpl\&.componentaction\&.ProcessISFProject\&.processPorts (List< Element > portElementList) throws \fBPortException\fP\fC [static]\fP, \fC [private]\fP"
Converts ports to \fBISFPort\fP objects with associated data and return elements and adds it to the portList\&. 
.PP
\fBParameters:\fP
.RS 4
\fIportElementList\fP List of ports 
.RE
.PP
\fBExceptions:\fP
.RS 4
\fI\fBPortException\fP\fP 
.RE
.PP

.SH "Member Data Documentation"
.PP 
.SS "List<\fBISFComponent\fP> gov\&.nasa\&.jpl\&.componentaction\&.ProcessISFProject\&.componentList\fC [static]\fP, \fC [private]\fP"

.SS "List<\fBISFPort\fP> gov\&.nasa\&.jpl\&.componentaction\&.ProcessISFProject\&.portList\fC [static]\fP, \fC [private]\fP"

.SS "Project gov\&.nasa\&.jpl\&.componentaction\&.ProcessISFProject\&.project\fC [static]\fP, \fC [private]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for MagicDrawCompPlugin from the source code\&.
