.TH "gov.nasa.jpl.componentaction.IsfXmlAutocoderAction" 3 "Tue Aug 9 2016" "Version 4.3" "MagicDrawCompPlugin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gov.nasa.jpl.componentaction.IsfXmlAutocoderAction \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits Plugin\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBinit\fP ()"
.br
.ti -1c
.RI "boolean \fBclose\fP ()"
.br
.ti -1c
.RI "boolean \fBisSupported\fP ()"
.br
.in -1c
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "NMAction \fBgetSeparatedActions\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Used to create generation/about tabs within MagicDraw\&. Buttons are attached to different action object\&. 
.SH "Member Function Documentation"
.PP 
.SS "boolean gov\&.nasa\&.jpl\&.componentaction\&.IsfXmlAutocoderAction\&.close ()"

.PP
\fBSee also:\fP
.RS 4
com\&.nomagic\&.magicdraw\&.plugins\&.Plugin::close() 
.RE
.PP

.SS "NMAction gov\&.nasa\&.jpl\&.componentaction\&.IsfXmlAutocoderAction\&.getSeparatedActions ()\fC [private]\fP"
Creates group of actions\&. This group is separated from others using menu separator (when it represented in menu)\&. Separator is added for group of actions in one actions category\&. 
.SS "void gov\&.nasa\&.jpl\&.componentaction\&.IsfXmlAutocoderAction\&.init ()"

.PP
\fBSee also:\fP
.RS 4
com\&.nomagic\&.magicdraw\&.plugins\&.Plugin::init() 
.RE
.PP

.SS "boolean gov\&.nasa\&.jpl\&.componentaction\&.IsfXmlAutocoderAction\&.isSupported ()"

.PP
\fBSee also:\fP
.RS 4
com\&.nomagic\&.magicdraw\&.plugins\&.Plugin::isSupported() 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for MagicDrawCompPlugin from the source code\&.
