.TH "gov.nasa.jpl.componentaction.TestISFExceptions" 3 "Tue Aug 9 2016" "Version 4.3" "MagicDrawCompPlugin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gov.nasa.jpl.componentaction.TestISFExceptions \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits MagicDrawTestCase\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTestISFExceptions\fP (String testMethodToRun, String testName)"
.br
.ti -1c
.RI "\fBTestISFExceptions\fP (String testMethodToRun)"
.br
.ti -1c
.RI "void \fBtestComponentNoConnections\fP ()  throws IOException "
.br
.ti -1c
.RI "void \fBtestPortException\fP ()  throws IOException "
.br
.ti -1c
.RI "void \fBtestMismatchedType\fP ()  throws IOException "
.br
.ti -1c
.RI "void \fBtestMismatchedDirections\fP ()  throws IOException "
.br
.ti -1c
.RI "void \fBtestDoubleMultiplicity\fP ()  throws IOException "
.br
.ti -1c
.RI "void \fBtestPassiveComponent\fP ()  throws IOException "
.br
.ti -1c
.RI "\fBISFComponent\fP \fBgetCompForTesting\fP (String projectName, String compType)"
.br
.ti -1c
.RI "void \fBtestActiveComponent\fP ()"
.br
.ti -1c
.RI "void \fBtestQueuedComponentAsync\fP ()  throws IOException "
.br
.ti -1c
.RI "void \fBtestQueuedComponentSync\fP ()  throws IOException "
.br
.ti -1c
.RI "void \fBtestProcessTopology\fP ()  throws IOException "
.br
.ti -1c
.RI "void \fBtestAbout\fP ()"
.br
.ti -1c
.RI "void \fBtestProcessProject\fP ()  throws IOException "
.br
.ti -1c
.RI "void \fBtestNoSource\fP ()  throws IOException "
.br
.ti -1c
.RI "void \fBtestNoTarget\fP ()  throws IOException "
.br
.ti -1c
.RI "void \fBtestMultipleSubsystems\fP ()  throws IOException "
.br
.ti -1c
.RI "void \fBtestCommandLine\fP ()"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBmain\fP (String[] args)"
.br
.ti -1c
.RI "static Test \fBsuite\fP ()"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "void \fBsetUpTest\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtearDownTest\fP ()  throws Exception "
.br
.in -1c
.SS "Static Private Member Functions"

.in +1c
.ti -1c
.RI "static List< Element > \fBgetElementsOfStereotype\fP (String stereotype, Project project)"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "String \fBpluginDir\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
JUnit test suite to check that exception handling works\&.
.PP
Most tests involve three parts:
.PP
.PD 0
.IP "\(bu" 2
Load the Magic Draw file\&.  
.IP "\(bu" 2
Run the plugin function that will be tested (IE, process from \fBProcessISFTopology\fP will only test the processing of the topology models, and so on)\&.  
.IP "\(bu" 2
Check if an exception is thrown with the correct error message, or if a pass test is being run, check if the appropriate files have been generated\&.  
.PD 0

.IP "  \(bu" 4

.PP

.PP

.SH "Constructor & Destructor Documentation"
.PP 
.SS "gov\&.nasa\&.jpl\&.componentaction\&.TestISFExceptions\&.TestISFExceptions (String testMethodToRun, String testName)"

.SS "gov\&.nasa\&.jpl\&.componentaction\&.TestISFExceptions\&.TestISFExceptions (String testMethodToRun)"

.SH "Member Function Documentation"
.PP 
.SS "\fBISFComponent\fP gov\&.nasa\&.jpl\&.componentaction\&.TestISFExceptions\&.getCompForTesting (String projectName, String compType)"
assumes that there is exactly one component in the project 
.PP
\fBParameters:\fP
.RS 4
\fIprojectName\fP 
.br
\fIcompType\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
.RE
.PP

.SS "static List<Element> gov\&.nasa\&.jpl\&.componentaction\&.TestISFExceptions\&.getElementsOfStereotype (String stereotype, Project project)\fC [static]\fP, \fC [private]\fP"

.SS "static void gov\&.nasa\&.jpl\&.componentaction\&.TestISFExceptions\&.main (String[] args)\fC [static]\fP"

.SS "void gov\&.nasa\&.jpl\&.componentaction\&.TestISFExceptions\&.setUpTest () throws Exception\fC [protected]\fP"

.SS "static Test gov\&.nasa\&.jpl\&.componentaction\&.TestISFExceptions\&.suite ()\fC [static]\fP"
Organizes the order in which tests run\&. 
.PP
\fBReturns:\fP
.RS 4

.RE
.PP

.SS "void gov\&.nasa\&.jpl\&.componentaction\&.TestISFExceptions\&.tearDownTest () throws Exception\fC [protected]\fP"

.SS "void gov\&.nasa\&.jpl\&.componentaction\&.TestISFExceptions\&.testAbout ()"

.SS "void gov\&.nasa\&.jpl\&.componentaction\&.TestISFExceptions\&.testActiveComponent ()"
Checks if active component without async ports gives warnings 
.PP
\fBExceptions:\fP
.RS 4
\fIIOException\fP 
.RE
.PP

.SS "void gov\&.nasa\&.jpl\&.componentaction\&.TestISFExceptions\&.testCommandLine ()"

.SS "void gov\&.nasa\&.jpl\&.componentaction\&.TestISFExceptions\&.testComponentNoConnections () throws IOException"

.SS "void gov\&.nasa\&.jpl\&.componentaction\&.TestISFExceptions\&.testDoubleMultiplicity () throws IOException"
Checks if connections originating from the same output port throws exceptions 
.PP
\fBExceptions:\fP
.RS 4
\fIIOException\fP 
.RE
.PP

.SS "void gov\&.nasa\&.jpl\&.componentaction\&.TestISFExceptions\&.testMismatchedDirections () throws IOException"
Checks if connections with directions that do not match throw exceptions 
.PP
\fBExceptions:\fP
.RS 4
\fIIOException\fP 
.RE
.PP

.SS "void gov\&.nasa\&.jpl\&.componentaction\&.TestISFExceptions\&.testMismatchedType () throws IOException"
Checks if connections with types that do not match throw exceptions 
.PP
\fBExceptions:\fP
.RS 4
\fIIOException\fP 
.RE
.PP

.SS "void gov\&.nasa\&.jpl\&.componentaction\&.TestISFExceptions\&.testMultipleSubsystems () throws IOException"
Tests both subsystems within subsystems, as well as multiple instances of one subsystem\&.
.PP
Note: The input file fails parsing for ports and components\&. 
.PP
\fBExceptions:\fP
.RS 4
\fIIOException\fP 
.RE
.PP

.SS "void gov\&.nasa\&.jpl\&.componentaction\&.TestISFExceptions\&.testNoSource () throws IOException"

.SS "void gov\&.nasa\&.jpl\&.componentaction\&.TestISFExceptions\&.testNoTarget () throws IOException"

.SS "void gov\&.nasa\&.jpl\&.componentaction\&.TestISFExceptions\&.testPassiveComponent () throws IOException"
Checks if passive components with async inputs throw exceptions 
.PP
\fBExceptions:\fP
.RS 4
\fIIOException\fP 
.RE
.PP

.SS "void gov\&.nasa\&.jpl\&.componentaction\&.TestISFExceptions\&.testPortException () throws IOException"
Checks if ports without types throw exceptions 
.PP
\fBExceptions:\fP
.RS 4
\fIIOException\fP 
.RE
.PP

.SS "void gov\&.nasa\&.jpl\&.componentaction\&.TestISFExceptions\&.testProcessProject () throws IOException"

.SS "void gov\&.nasa\&.jpl\&.componentaction\&.TestISFExceptions\&.testProcessTopology () throws IOException"
Checks if topology is generated correctly 
.PP
\fBExceptions:\fP
.RS 4
\fIIOException\fP 
.RE
.PP

.SS "void gov\&.nasa\&.jpl\&.componentaction\&.TestISFExceptions\&.testQueuedComponentAsync () throws IOException"
Checks if queued component without async ports gives warnings 
.PP
\fBExceptions:\fP
.RS 4
\fIIOException\fP 
.RE
.PP

.SS "void gov\&.nasa\&.jpl\&.componentaction\&.TestISFExceptions\&.testQueuedComponentSync () throws IOException"
Checks if queued component without sync ports gives warnings 
.PP
\fBExceptions:\fP
.RS 4
\fIIOException\fP 
.RE
.PP

.SH "Member Data Documentation"
.PP 
.SS "String gov\&.nasa\&.jpl\&.componentaction\&.TestISFExceptions\&.pluginDir\fC [private]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for MagicDrawCompPlugin from the source code\&.
