.TH "gov.nasa.jpl.componentaction.LoadIDException" 3 "Tue Aug 9 2016" "Version 4.3" "MagicDrawCompPlugin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gov.nasa.jpl.componentaction.LoadIDException \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits Exception\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBLoadIDException\fP (String message)"
.br
.in -1c
.SS "Static Private Attributes"

.in +1c
.ti -1c
.RI "static final long \fBserialVersionUID\fP = 1L"
.br
.in -1c
.SH "Detailed Description"
.PP 
Shell exception for the \fBLoadIDConfig\fP class\&. This just serves as a wrapper that can be used to differentiate between where an error happens\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "gov\&.nasa\&.jpl\&.componentaction\&.LoadIDException\&.LoadIDException (String message)"

.SH "Member Data Documentation"
.PP 
.SS "final long gov\&.nasa\&.jpl\&.componentaction\&.LoadIDException\&.serialVersionUID = 1L\fC [static]\fP, \fC [private]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for MagicDrawCompPlugin from the source code\&.
