.TH "gov.nasa.jpl.componentaction.Partition" 3 "Tue Aug 9 2016" "Version 4.3" "MagicDrawCompPlugin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gov.nasa.jpl.componentaction.Partition \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPartition\fP (Element \fBpartitionElement\fP)"
.br
.ti -1c
.RI "String \fBgetName\fP ()"
.br
.ti -1c
.RI "String \fBgetDataName\fP (Element dataElement)"
.br
.ti -1c
.RI "String \fBgetDataType\fP (Element dataElement)"
.br
.ti -1c
.RI "void \fBprint\fP ()"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "Element \fBpartitionElement\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Creates the partition object\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "gov\&.nasa\&.jpl\&.componentaction\&.Partition\&.Partition (Element partitionElement)"
Assigns the input partitionElement to the instance variable partitionElement\&. 
.PP
\fBParameters:\fP
.RS 4
\fIpartitionElement\fP 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "String gov\&.nasa\&.jpl\&.componentaction\&.Partition\&.getDataName (Element dataElement)"
Returns the third word in the name of the dataElement if the name was divided by spaces\&. 
.PP
\fBParameters:\fP
.RS 4
\fIdataElement\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
the name of the dataElement 
.RE
.PP

.SS "String gov\&.nasa\&.jpl\&.componentaction\&.Partition\&.getDataType (Element dataElement)"
Returns the third word in the type of the dataElement if the type was divided by spaces\&. 
.PP
\fBParameters:\fP
.RS 4
\fIdataElement\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
the type of the dataElement 
.RE
.PP

.SS "String gov\&.nasa\&.jpl\&.componentaction\&.Partition\&.getName ()"
Returns the name of the partitionElement\&. 
.PP
\fBReturns:\fP
.RS 4
name string 
.RE
.PP

.SS "void gov\&.nasa\&.jpl\&.componentaction\&.Partition\&.print ()"
Prints the partition name to Java standard out and the MagicDraw console\&. 
.SH "Member Data Documentation"
.PP 
.SS "Element gov\&.nasa\&.jpl\&.componentaction\&.Partition\&.partitionElement\fC [private]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for MagicDrawCompPlugin from the source code\&.
