.TH "gov.nasa.jpl.componentaction.Utils.Pair< A, B >" 3 "Tue Aug 9 2016" "Version 4.3" "MagicDrawCompPlugin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gov.nasa.jpl.componentaction.Utils.Pair< A, B > \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPair\fP (final A firstObj, final B secondObj)"
.br
.ti -1c
.RI "int \fBhashCode\fP ()"
.br
.ti -1c
.RI "boolean \fBequals\fP (Object obj)"
.br
.ti -1c
.RI "A \fBgetFirst\fP ()"
.br
.ti -1c
.RI "B \fBgetSecond\fP ()"
.br
.ti -1c
.RI "void \fBsetFirst\fP (A \fBfirst\fP)"
.br
.ti -1c
.RI "void \fBsetSecond\fP (B \fBsecond\fP)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "A \fBfirst\fP"
.br
.ti -1c
.RI "B \fBsecond\fP"
.br
.in -1c
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "\fBUtils\fP \fBgetOuterType\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Generic \fBPair\fP class that can be used to hold two items of separate types
.PP
\fBParameters:\fP
.RS 4
\fI<A>\fP 
.br
\fI<B>\fP 
.RE
.PP

.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBgov\&.nasa\&.jpl\&.componentaction\&.Utils\&.Pair\fP< A, B >\&.\fBPair\fP (final A firstObj, final B secondObj)"

.SH "Member Function Documentation"
.PP 
.SS "boolean \fBgov\&.nasa\&.jpl\&.componentaction\&.Utils\&.Pair\fP< A, B >\&.equals (Object obj)"

.SS "A \fBgov\&.nasa\&.jpl\&.componentaction\&.Utils\&.Pair\fP< A, B >\&.getFirst ()"

.SS "\fBUtils\fP \fBgov\&.nasa\&.jpl\&.componentaction\&.Utils\&.Pair\fP< A, B >\&.getOuterType ()\fC [private]\fP"

.SS "B \fBgov\&.nasa\&.jpl\&.componentaction\&.Utils\&.Pair\fP< A, B >\&.getSecond ()"

.SS "int \fBgov\&.nasa\&.jpl\&.componentaction\&.Utils\&.Pair\fP< A, B >\&.hashCode ()"

.SS "void \fBgov\&.nasa\&.jpl\&.componentaction\&.Utils\&.Pair\fP< A, B >\&.setFirst (A first)"

.SS "void \fBgov\&.nasa\&.jpl\&.componentaction\&.Utils\&.Pair\fP< A, B >\&.setSecond (B second)"

.SH "Member Data Documentation"
.PP 
.SS "A \fBgov\&.nasa\&.jpl\&.componentaction\&.Utils\&.Pair\fP< A, B >\&.first"

.SS "B \fBgov\&.nasa\&.jpl\&.componentaction\&.Utils\&.Pair\fP< A, B >\&.second"


.SH "Author"
.PP 
Generated automatically by Doxygen for MagicDrawCompPlugin from the source code\&.
