.TH "gov.nasa.jpl.componentaction.ISFSubsystem" 3 "Tue Aug 9 2016" "Version 4.3" "MagicDrawCompPlugin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gov.nasa.jpl.componentaction.ISFSubsystem \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBcomponentType\fP"
.br
.ti -1c
.RI "class \fBphysicalConnectionType\fP"
.br
.ti -1c
.RI "class \fBtopologyModel\fP"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBcomponentType\fP \fBcreateComponent\fP (String name, String nameSpace, String type, String baseID, String instanceWindow, String xmlPath)"
.br
.ti -1c
.RI "static int \fBgetSourceIndex\fP (Connector conn)  throws ConnectorException "
.br
.ti -1c
.RI "static int \fBgetTargetIndex\fP (Connector conn)  throws ConnectorException "
.br
.ti -1c
.RI "static void \fBprint\fP ()"
.br
.ti -1c
.RI "static String \fBgetFileLocation\fP (Element instanceElement)"
.br
.ti -1c
.RI "static String \fBgetBaseId\fP (Element instanceElement)"
.br
.ti -1c
.RI "static String \fBgetInstanceWindow\fP (Element instanceElement)"
.br
.ti -1c
.RI "static String \fBgetSourceComp\fP (Connector c)  throws ConnectorException "
.br
.ti -1c
.RI "static String \fBgetTargetComp\fP (Connector c)  throws ConnectorException "
.br
.ti -1c
.RI "static String \fBgetCompName\fP (ConnectorEnd conn)  throws ConnectorException "
.br
.ti -1c
.RI "static String \fBgetIDSourcePort\fP (Connector c)  throws ConnectorException "
.br
.ti -1c
.RI "static String \fBgetIDTargetPort\fP (Connector c)  throws ConnectorException "
.br
.ti -1c
.RI "static String \fBgetSourcePort\fP (Connector c)  throws ConnectorException "
.br
.ti -1c
.RI "static String \fBgetTargetPort\fP (Connector c)  throws ConnectorException "
.br
.ti -1c
.RI "static String \fBgetPortName\fP (ConnectorEnd conn)  throws ConnectorException "
.br
.ti -1c
.RI "static String \fBgetLastPartOfString\fP (String in)"
.br
.ti -1c
.RI "static String \fBgetQualifiedPort\fP (ConnectorEnd connEnd)"
.br
.ti -1c
.RI "static String \fBgetQualifiedSourcePort\fP (Connector c)  throws ConnectorException "
.br
.ti -1c
.RI "static String \fBgetQualifiedTargetPort\fP (Connector c)  throws ConnectorException "
.br
.ti -1c
.RI "static String \fBgetSourcePortType\fP (Connector c)  throws ConnectorException "
.br
.ti -1c
.RI "static String \fBgetTargetPortType\fP (Connector c)  throws ConnectorException "
.br
.ti -1c
.RI "static ConnectorEnd \fBgetSourceConnEnd\fP (Connector c)  throws ConnectorException "
.br
.ti -1c
.RI "static ConnectorEnd \fBgetTargetConnEnd\fP (Connector c)  throws ConnectorException"
.br
.ti -1c
.RI "static ConnectorEnd \fBgetConnEnd\fP (Connector c, boolean isSource)  throws ConnectorException "
.br
.ti -1c
.RI "static List< Element > \fBgetElementsOfStereotype\fP (String stereotype)"
.br
.ti -1c
.RI "static String \fBgetNamespace\fP (Element componentElement)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Helper class for \fBProcessISFTopology\fP 
.SH "Member Function Documentation"
.PP 
.SS "static \fBcomponentType\fP gov\&.nasa\&.jpl\&.componentaction\&.ISFSubsystem\&.createComponent (String name, String nameSpace, String type, String baseID, String instanceWindow, String xmlPath)\fC [static]\fP"
Creates and returns new \fBcomponentType\fP
.PP
\fBParameters:\fP
.RS 4
\fIname\fP Component name 
.br
\fInameSpace\fP Component name space 
.br
\fItype\fP Component Type 
.br
\fIbaseID\fP Base ID 
.br
\fIinstanceWindow\fP Instance Window ID 
.RE
.PP
\fBReturns:\fP
.RS 4
\fBcomponentType\fP 
.RE
.PP

.SS "static String gov\&.nasa\&.jpl\&.componentaction\&.ISFSubsystem\&.getBaseId (Element instanceElement)\fC [static]\fP"
Returns the base ID of the element\&.
.PP
\fBParameters:\fP
.RS 4
\fIinstanceElement\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
.RE
.PP

.SS "static String gov\&.nasa\&.jpl\&.componentaction\&.ISFSubsystem\&.getCompName (ConnectorEnd conn) throws \fBConnectorException\fP\fC [static]\fP"
Returns the component name of the connectorEnd\&. 
.PP
\fBParameters:\fP
.RS 4
\fIconn\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
.RE
.PP
\fBExceptions:\fP
.RS 4
\fI\fBConnectorException\fP\fP 
.RE
.PP

.SS "static ConnectorEnd gov\&.nasa\&.jpl\&.componentaction\&.ISFSubsystem\&.getConnEnd (Connector c, boolean isSource) throws \fBConnectorException\fP\fC [static]\fP"
Both getSourceConnEnd and getTargetConnEnd use this function\&. Incorporates error handling/checking\&. 
.PP
The function checks the direction property of the first stereotype found in each port of the connector\&. Depending on what the connector can see within and around the system, the function will return what it sees as the source and what is sees as the target\&.
.PP
\fBParameters:\fP
.RS 4
\fIc\fP Connector 
.br
\fIisSource\fP true if looking for source end, false if looking for target end 
.RE
.PP
\fBReturns:\fP
.RS 4
Connector End 
.RE
.PP
\fBExceptions:\fP
.RS 4
\fI\fBConnectorException\fP\fP 
.RE
.PP

.SS "static List<Element> gov\&.nasa\&.jpl\&.componentaction\&.ISFSubsystem\&.getElementsOfStereotype (String stereotype)\fC [static]\fP"
Returns a list of elements with the given stereotype String\&.
.PP
\fBParameters:\fP
.RS 4
\fIstereotype\fP String 
.RE
.PP
\fBReturns:\fP
.RS 4
List of Objects 
.RE
.PP

.SS "static String gov\&.nasa\&.jpl\&.componentaction\&.ISFSubsystem\&.getFileLocation (Element instanceElement)\fC [static]\fP"

.SS "static String gov\&.nasa\&.jpl\&.componentaction\&.ISFSubsystem\&.getIDSourcePort (Connector c) throws \fBConnectorException\fP\fC [static]\fP"
Returns the generic ID of the source port on this Connector\&. 
.PP
This ID is not unique among different instances of the same module\&. 
.PP
\fBParameters:\fP
.RS 4
\fIc\fP Connector 
.RE
.PP
\fBReturns:\fP
.RS 4
ID String 
.RE
.PP
\fBExceptions:\fP
.RS 4
\fI\fBConnectorException\fP\fP 
.RE
.PP

.SS "static String gov\&.nasa\&.jpl\&.componentaction\&.ISFSubsystem\&.getIDTargetPort (Connector c) throws \fBConnectorException\fP\fC [static]\fP"
Returns the generic ID of the target port on this Connector\&. 
.PP
This ID is not unique among different instances of the same module\&. 
.PP
\fBParameters:\fP
.RS 4
\fIc\fP Connector 
.RE
.PP
\fBReturns:\fP
.RS 4
ID String 
.RE
.PP
\fBExceptions:\fP
.RS 4
\fI\fBConnectorException\fP\fP 
.RE
.PP

.SS "static String gov\&.nasa\&.jpl\&.componentaction\&.ISFSubsystem\&.getInstanceWindow (Element instanceElement)\fC [static]\fP"
Returns the instance window of the element\&.
.PP
\fBParameters:\fP
.RS 4
\fIinstanceElement\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
.RE
.PP

.SS "static String gov\&.nasa\&.jpl\&.componentaction\&.ISFSubsystem\&.getLastPartOfString (String in)\fC [static]\fP"
Splits the in string with ' ' and returns the last values in the array\&.
.PP
\fBParameters:\fP
.RS 4
\fIin\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
.RE
.PP

.SS "static String gov\&.nasa\&.jpl\&.componentaction\&.ISFSubsystem\&.getNamespace (Element componentElement)\fC [static]\fP"
Returns the name space of the element\&.
.PP
\fBParameters:\fP
.RS 4
\fIcomponentElement\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
.RE
.PP

.SS "static String gov\&.nasa\&.jpl\&.componentaction\&.ISFSubsystem\&.getPortName (ConnectorEnd conn) throws \fBConnectorException\fP\fC [static]\fP"
Returns the generic name of the role of the ConnectorEnd\&.
.PP
\fBParameters:\fP
.RS 4
\fIconn\fP ConnectorEnd 
.RE
.PP
\fBReturns:\fP
.RS 4
Name 
.RE
.PP
\fBExceptions:\fP
.RS 4
\fI\fBConnectorException\fP\fP 
.RE
.PP

.SS "static String gov\&.nasa\&.jpl\&.componentaction\&.ISFSubsystem\&.getQualifiedPort (ConnectorEnd connEnd)\fC [static]\fP"
Returns a string with the qualified name of the base port it is attached to, along with the qualified name of the instance of the port (if it exists)\&. 
.PP
This can be used to uniquely identify a port against other ports in a subsystem\&.
.PP
\fBParameters:\fP
.RS 4
\fIconnEnd\fP ConnectorEnd 
.RE
.PP
\fBReturns:\fP
.RS 4
String of the combined qualified name\&. 
.RE
.PP

.SS "static String gov\&.nasa\&.jpl\&.componentaction\&.ISFSubsystem\&.getQualifiedSourcePort (Connector c) throws \fBConnectorException\fP\fC [static]\fP"
Returns the qualified name of the source port from the connector\&. 
.PP
The qualified name describes the port by providing the port's name, the module it is attached to, and the location of the module\&.
.PP
\fBParameters:\fP
.RS 4
\fIc\fP Connector 
.RE
.PP
\fBReturns:\fP
.RS 4
String qualified name 
.RE
.PP
\fBExceptions:\fP
.RS 4
\fI\fBConnectorException\fP\fP 
.RE
.PP

.SS "static String gov\&.nasa\&.jpl\&.componentaction\&.ISFSubsystem\&.getQualifiedTargetPort (Connector c) throws \fBConnectorException\fP\fC [static]\fP"
Returns the qualified name of the target port from the connector\&. 
.PP
The qualified name describes the port by providing the port's name, the module it is attached to, and the location of the module\&.
.PP
\fBParameters:\fP
.RS 4
\fIc\fP Connector 
.RE
.PP
\fBReturns:\fP
.RS 4
String qualified name 
.RE
.PP
\fBExceptions:\fP
.RS 4
\fI\fBConnectorException\fP\fP 
.RE
.PP

.SS "static String gov\&.nasa\&.jpl\&.componentaction\&.ISFSubsystem\&.getSourceComp (Connector c) throws \fBConnectorException\fP\fC [static]\fP"
Returns the source name off the attached component\&.
.PP
\fBParameters:\fP
.RS 4
\fIc\fP Connector 
.RE
.PP
\fBReturns:\fP
.RS 4
Component Name 
.RE
.PP
\fBExceptions:\fP
.RS 4
\fI\fBConnectorException\fP\fP Will raise an exception if the target component does not exist (IE the source is connected to the outside of the subsystem) 
.RE
.PP

.SS "static ConnectorEnd gov\&.nasa\&.jpl\&.componentaction\&.ISFSubsystem\&.getSourceConnEnd (Connector c) throws \fBConnectorException\fP\fC [static]\fP"
Checks the connectorEnd roles to match the returned value with the input (source) connector end\&.
.PP
This function does not check to see if both ConnectorEnds are different or have the same input/output types\&.
.PP
\fBParameters:\fP
.RS 4
\fIc\fP Connector 
.RE
.PP
\fBReturns:\fP
.RS 4
Source ConnectorEnd 
.RE
.PP

.SS "static int gov\&.nasa\&.jpl\&.componentaction\&.ISFSubsystem\&.getSourceIndex (Connector conn) throws \fBConnectorException\fP\fC [static]\fP"
Returns the multiplicity of the source end of the connector\&.
.PP
\fBParameters:\fP
.RS 4
\fIconn\fP Connector 
.RE
.PP
\fBReturns:\fP
.RS 4
multiplicity 
.RE
.PP
\fBExceptions:\fP
.RS 4
\fI\fBConnectorException\fP\fP 
.RE
.PP

.SS "static String gov\&.nasa\&.jpl\&.componentaction\&.ISFSubsystem\&.getSourcePort (Connector c) throws \fBConnectorException\fP\fC [static]\fP"
Returns the generic name of source port on this Connector\&.
.PP
\fBParameters:\fP
.RS 4
\fIc\fP Connector 
.RE
.PP
\fBReturns:\fP
.RS 4
Name 
.RE
.PP
\fBExceptions:\fP
.RS 4
\fI\fBConnectorException\fP\fP 
.RE
.PP

.SS "static String gov\&.nasa\&.jpl\&.componentaction\&.ISFSubsystem\&.getSourcePortType (Connector c) throws \fBConnectorException\fP\fC [static]\fP"
Returns the source port type from the Connector\&.
.PP
\fBParameters:\fP
.RS 4
\fIc\fP Connector 
.RE
.PP
\fBReturns:\fP
.RS 4
Port Type 
.RE
.PP
\fBExceptions:\fP
.RS 4
\fI\fBConnectorException\fP\fP 
.RE
.PP

.SS "static String gov\&.nasa\&.jpl\&.componentaction\&.ISFSubsystem\&.getTargetComp (Connector c) throws \fBConnectorException\fP\fC [static]\fP"
Returns the target name off the attached component\&.
.PP
\fBParameters:\fP
.RS 4
\fIc\fP Connector 
.RE
.PP
\fBReturns:\fP
.RS 4
Component Name 
.RE
.PP
\fBExceptions:\fP
.RS 4
\fI\fBConnectorException\fP\fP Will raise an exception if the target component does not exist (IE the target is connected to the outside of the subsystem) 
.RE
.PP

.SS "static ConnectorEnd gov\&.nasa\&.jpl\&.componentaction\&.ISFSubsystem\&.getTargetConnEnd (Connector c) throws \fBConnectorException\fP\fC [static]\fP"
Checks the connectorEnd roles to match the returned value with the output (target) connector end\&.
.PP
This function does not check to see if both ConnectorEnds are different or have the same input/output types\&.
.PP
\fBParameters:\fP
.RS 4
\fIc\fP Connector 
.RE
.PP
\fBReturns:\fP
.RS 4
Target ConnectorEnd 
.RE
.PP

.SS "static int gov\&.nasa\&.jpl\&.componentaction\&.ISFSubsystem\&.getTargetIndex (Connector conn) throws \fBConnectorException\fP\fC [static]\fP"
Returns the multiplicity of the target end of the connector\&.
.PP
\fBParameters:\fP
.RS 4
\fIconn\fP Connector 
.RE
.PP
\fBReturns:\fP
.RS 4
multiplicity 
.RE
.PP
\fBExceptions:\fP
.RS 4
\fI\fBConnectorException\fP\fP 
.RE
.PP

.SS "static String gov\&.nasa\&.jpl\&.componentaction\&.ISFSubsystem\&.getTargetPort (Connector c) throws \fBConnectorException\fP\fC [static]\fP"
Returns the generic name of target port on this Connector\&.
.PP
\fBParameters:\fP
.RS 4
\fIc\fP Connector 
.RE
.PP
\fBReturns:\fP
.RS 4
Name 
.RE
.PP
\fBExceptions:\fP
.RS 4
\fI\fBConnectorException\fP\fP 
.RE
.PP

.SS "static String gov\&.nasa\&.jpl\&.componentaction\&.ISFSubsystem\&.getTargetPortType (Connector c) throws \fBConnectorException\fP\fC [static]\fP"
Returns the target port type from the Connector\&.
.PP
\fBParameters:\fP
.RS 4
\fIc\fP Connector 
.RE
.PP
\fBReturns:\fP
.RS 4
Port Type 
.RE
.PP
\fBExceptions:\fP
.RS 4
\fI\fBConnectorException\fP\fP 
.RE
.PP

.SS "static void gov\&.nasa\&.jpl\&.componentaction\&.ISFSubsystem\&.print ()\fC [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for MagicDrawCompPlugin from the source code\&.
