.TH "gov.nasa.jpl.componentaction.isfxmlwriter.IsfSubXmlWriter" 3 "Tue Aug 9 2016" "Version 4.3" "MagicDrawCompPlugin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gov.nasa.jpl.componentaction.isfxmlwriter.IsfSubXmlWriter \- 
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBwrite\fP (ISFSubsystem\&.topologyModel top, String deployment, String fileName, String outDir, File pluginDir)"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "static void gov\&.nasa\&.jpl\&.componentaction\&.isfxmlwriter\&.IsfSubXmlWriter\&.write (ISFSubsystem\&.topologyModel top, String deployment, String fileName, String outDir, File pluginDir)\fC [static]\fP"
Writes the subsystem topology XML file\&. 
.PP
\fBParameters:\fP
.RS 4
\fItop\fP 
.br
\fIdeployment\fP 
.br
\fIfileName\fP 
.br
\fIoutDir\fP 
.br
\fIpluginDir\fP 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for MagicDrawCompPlugin from the source code\&.
