.TH "gov.nasa.jpl.componentaction.ISFSubsystem.componentType" 3 "Tue Aug 9 2016" "Version 4.3" "MagicDrawCompPlugin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gov.nasa.jpl.componentaction.ISFSubsystem.componentType \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBcomponentType\fP ()"
.br
.ti -1c
.RI "String \fBgetName\fP ()"
.br
.ti -1c
.RI "String \fBgetNameSpace\fP ()"
.br
.ti -1c
.RI "String \fBgetType\fP ()"
.br
.ti -1c
.RI "String \fBgetBaseID\fP ()"
.br
.ti -1c
.RI "String \fBgetInstanceWindow\fP ()"
.br
.ti -1c
.RI "String \fBgetXMLLocation\fP ()"
.br
.in -1c
.SS "Package Attributes"

.in +1c
.ti -1c
.RI "String \fBname\fP"
.br
.ti -1c
.RI "String \fBnameSpace\fP"
.br
.ti -1c
.RI "String \fBtype\fP"
.br
.ti -1c
.RI "String \fBbaseID\fP"
.br
.ti -1c
.RI "String \fBinstanceWindow\fP"
.br
.ti -1c
.RI "String \fBXMLLocation\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Used as a dataObject within the componentMap\&. The objects within this object are used to describe a leaf component\&. The methods are pretty self-explanatory\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "gov\&.nasa\&.jpl\&.componentaction\&.ISFSubsystem\&.componentType\&.componentType ()"

.SH "Member Function Documentation"
.PP 
.SS "String gov\&.nasa\&.jpl\&.componentaction\&.ISFSubsystem\&.componentType\&.getBaseID ()"

.SS "String gov\&.nasa\&.jpl\&.componentaction\&.ISFSubsystem\&.componentType\&.getInstanceWindow ()"

.SS "String gov\&.nasa\&.jpl\&.componentaction\&.ISFSubsystem\&.componentType\&.getName ()"

.SS "String gov\&.nasa\&.jpl\&.componentaction\&.ISFSubsystem\&.componentType\&.getNameSpace ()"

.SS "String gov\&.nasa\&.jpl\&.componentaction\&.ISFSubsystem\&.componentType\&.getType ()"

.SS "String gov\&.nasa\&.jpl\&.componentaction\&.ISFSubsystem\&.componentType\&.getXMLLocation ()"

.SH "Member Data Documentation"
.PP 
.SS "String gov\&.nasa\&.jpl\&.componentaction\&.ISFSubsystem\&.componentType\&.baseID\fC [package]\fP"

.SS "String gov\&.nasa\&.jpl\&.componentaction\&.ISFSubsystem\&.componentType\&.instanceWindow\fC [package]\fP"

.SS "String gov\&.nasa\&.jpl\&.componentaction\&.ISFSubsystem\&.componentType\&.name\fC [package]\fP"

.SS "String gov\&.nasa\&.jpl\&.componentaction\&.ISFSubsystem\&.componentType\&.nameSpace\fC [package]\fP"

.SS "String gov\&.nasa\&.jpl\&.componentaction\&.ISFSubsystem\&.componentType\&.type\fC [package]\fP"

.SS "String gov\&.nasa\&.jpl\&.componentaction\&.ISFSubsystem\&.componentType\&.XMLLocation\fC [package]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for MagicDrawCompPlugin from the source code\&.
