.TH "gov.nasa.jpl.componentaction.ISFComponent.referencePort" 3 "Tue Aug 9 2016" "Version 4.3" "MagicDrawCompPlugin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gov.nasa.jpl.componentaction.ISFComponent.referencePort \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "String \fBgetReference\fP ()"
.br
.in -1c
.SS "Package Functions"

.in +1c
.ti -1c
.RI "\fBreferencePort\fP ()"
.br
.in -1c
.SS "Package Attributes"

.in +1c
.ti -1c
.RI "String \fBReference\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
A base class for all Ports that do not specify a data type but have a reference to some existing xml data structure 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "gov\&.nasa\&.jpl\&.componentaction\&.ISFComponent\&.referencePort\&.referencePort ()\fC [package]\fP"

.SH "Member Function Documentation"
.PP 
.SS "String gov\&.nasa\&.jpl\&.componentaction\&.ISFComponent\&.referencePort\&.getReference ()"

.SH "Member Data Documentation"
.PP 
.SS "String gov\&.nasa\&.jpl\&.componentaction\&.ISFComponent\&.referencePort\&.Reference\fC [package]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for MagicDrawCompPlugin from the source code\&.
