.TH "gov.nasa.jpl.componentaction.ISFSubsystem.physicalConnectionType" 3 "Tue Aug 9 2016" "Version 4.3" "MagicDrawCompPlugin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gov.nasa.jpl.componentaction.ISFSubsystem.physicalConnectionType \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBphysicalConnectionType\fP (ConnectorEnd \fBsourceEnd\fP, ConnectorEnd \fBtargetEnd\fP, Integer \fBsource_index\fP, Integer \fBtarget_index\fP)"
.br
.ti -1c
.RI "\fBphysicalConnectionType\fP (ConnectorEnd \fBsourceEnd\fP, ConnectorEnd \fBtargetEnd\fP, String sourceName, String targetName, Integer \fBsource_index\fP, Integer \fBtarget_index\fP)"
.br
.ti -1c
.RI "String \fBtoString\fP ()"
.br
.ti -1c
.RI "int \fBhashCode\fP ()"
.br
.ti -1c
.RI "boolean \fBequals\fP (Object obj)"
.br
.ti -1c
.RI "int \fBgetSourcePortIndex\fP ()"
.br
.ti -1c
.RI "int \fBgetTargetPortIndex\fP ()"
.br
.ti -1c
.RI "String \fBgetSource\fP ()"
.br
.ti -1c
.RI "String \fBgetTarget\fP ()"
.br
.ti -1c
.RI "String \fBgetSourcePortName\fP ()"
.br
.ti -1c
.RI "String \fBgetTargetPortName\fP ()"
.br
.ti -1c
.RI "String \fBgetSourcePortType\fP ()"
.br
.ti -1c
.RI "String \fBgetTargetPortType\fP ()"
.br
.in -1c
.SS "Package Attributes"

.in +1c
.ti -1c
.RI "String \fBsource\fP"
.br
.ti -1c
.RI "String \fBtarget\fP"
.br
.ti -1c
.RI "String \fBsourcePortName\fP"
.br
.ti -1c
.RI "String \fBtargetPortName\fP"
.br
.ti -1c
.RI "String \fBsourcePortType\fP"
.br
.ti -1c
.RI "String \fBtargetPortType\fP"
.br
.ti -1c
.RI "String \fBtargetRoleParentName\fP"
.br
.ti -1c
.RI "String \fBsourceRoleParentName\fP"
.br
.ti -1c
.RI "ConnectorEnd \fBsourceEnd\fP"
.br
.ti -1c
.RI "ConnectorEnd \fBtargetEnd\fP"
.br
.ti -1c
.RI "Integer \fBsource_index\fP"
.br
.ti -1c
.RI "Integer \fBtarget_index\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
The \fBphysicalConnectionType\fP is used to describe connections\&. Connector objects can not be re-defined through the API, so when we find a source port with it's final target port, we make one of these objects to describe the connection\&. This includes the names of the ports, the type, the parent name, the multiplicities, and the actual connectorEnd\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "gov\&.nasa\&.jpl\&.componentaction\&.ISFSubsystem\&.physicalConnectionType\&.physicalConnectionType (ConnectorEnd sourceEnd, ConnectorEnd targetEnd, Integer source_index, Integer target_index)"

.SS "gov\&.nasa\&.jpl\&.componentaction\&.ISFSubsystem\&.physicalConnectionType\&.physicalConnectionType (ConnectorEnd sourceEnd, ConnectorEnd targetEnd, String sourceName, String targetName, Integer source_index, Integer target_index)"

.SH "Member Function Documentation"
.PP 
.SS "boolean gov\&.nasa\&.jpl\&.componentaction\&.ISFSubsystem\&.physicalConnectionType\&.equals (Object obj)"

.SS "String gov\&.nasa\&.jpl\&.componentaction\&.ISFSubsystem\&.physicalConnectionType\&.getSource ()"

.SS "int gov\&.nasa\&.jpl\&.componentaction\&.ISFSubsystem\&.physicalConnectionType\&.getSourcePortIndex ()"

.SS "String gov\&.nasa\&.jpl\&.componentaction\&.ISFSubsystem\&.physicalConnectionType\&.getSourcePortName ()"

.SS "String gov\&.nasa\&.jpl\&.componentaction\&.ISFSubsystem\&.physicalConnectionType\&.getSourcePortType ()"

.SS "String gov\&.nasa\&.jpl\&.componentaction\&.ISFSubsystem\&.physicalConnectionType\&.getTarget ()"

.SS "int gov\&.nasa\&.jpl\&.componentaction\&.ISFSubsystem\&.physicalConnectionType\&.getTargetPortIndex ()"

.SS "String gov\&.nasa\&.jpl\&.componentaction\&.ISFSubsystem\&.physicalConnectionType\&.getTargetPortName ()"

.SS "String gov\&.nasa\&.jpl\&.componentaction\&.ISFSubsystem\&.physicalConnectionType\&.getTargetPortType ()"

.SS "int gov\&.nasa\&.jpl\&.componentaction\&.ISFSubsystem\&.physicalConnectionType\&.hashCode ()"

.SS "String gov\&.nasa\&.jpl\&.componentaction\&.ISFSubsystem\&.physicalConnectionType\&.toString ()"

.SH "Member Data Documentation"
.PP 
.SS "String gov\&.nasa\&.jpl\&.componentaction\&.ISFSubsystem\&.physicalConnectionType\&.source\fC [package]\fP"

.SS "Integer gov\&.nasa\&.jpl\&.componentaction\&.ISFSubsystem\&.physicalConnectionType\&.source_index\fC [package]\fP"

.SS "ConnectorEnd gov\&.nasa\&.jpl\&.componentaction\&.ISFSubsystem\&.physicalConnectionType\&.sourceEnd\fC [package]\fP"

.SS "String gov\&.nasa\&.jpl\&.componentaction\&.ISFSubsystem\&.physicalConnectionType\&.sourcePortName\fC [package]\fP"

.SS "String gov\&.nasa\&.jpl\&.componentaction\&.ISFSubsystem\&.physicalConnectionType\&.sourcePortType\fC [package]\fP"

.SS "String gov\&.nasa\&.jpl\&.componentaction\&.ISFSubsystem\&.physicalConnectionType\&.sourceRoleParentName\fC [package]\fP"

.SS "String gov\&.nasa\&.jpl\&.componentaction\&.ISFSubsystem\&.physicalConnectionType\&.target\fC [package]\fP"

.SS "Integer gov\&.nasa\&.jpl\&.componentaction\&.ISFSubsystem\&.physicalConnectionType\&.target_index\fC [package]\fP"

.SS "ConnectorEnd gov\&.nasa\&.jpl\&.componentaction\&.ISFSubsystem\&.physicalConnectionType\&.targetEnd\fC [package]\fP"

.SS "String gov\&.nasa\&.jpl\&.componentaction\&.ISFSubsystem\&.physicalConnectionType\&.targetPortName\fC [package]\fP"

.SS "String gov\&.nasa\&.jpl\&.componentaction\&.ISFSubsystem\&.physicalConnectionType\&.targetPortType\fC [package]\fP"

.SS "String gov\&.nasa\&.jpl\&.componentaction\&.ISFSubsystem\&.physicalConnectionType\&.targetRoleParentName\fC [package]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for MagicDrawCompPlugin from the source code\&.
