.TH "gov.nasa.jpl.componentaction.IsfAbout" 3 "Tue Aug 9 2016" "Version 4.3" "MagicDrawCompPlugin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gov.nasa.jpl.componentaction.IsfAbout \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits MDAction\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBIsfAbout\fP (String id, String name, File \fBpluginDir\fP)"
.br
.ti -1c
.RI "void \fBactionPerformed\fP (ActionEvent e)"
.br
.in -1c
.SS "Package Attributes"

.in +1c
.ti -1c
.RI "File \fBpluginDir\fP"
.br
.in -1c
.SS "Static Private Attributes"

.in +1c
.ti -1c
.RI "static final long \fBserialVersionUID\fP = \-6790954285526957354L"
.br
.in -1c
.SH "Detailed Description"
.PP 
Action class for information regarding the plugin 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "gov\&.nasa\&.jpl\&.componentaction\&.IsfAbout\&.IsfAbout (String id, String name, File pluginDir)"

.SH "Member Function Documentation"
.PP 
.SS "void gov\&.nasa\&.jpl\&.componentaction\&.IsfAbout\&.actionPerformed (ActionEvent e)"
Used to display content in the 'About' tab\&. Edit this for tab changes\&. 
.SH "Member Data Documentation"
.PP 
.SS "File gov\&.nasa\&.jpl\&.componentaction\&.IsfAbout\&.pluginDir\fC [package]\fP"

.SS "final long gov\&.nasa\&.jpl\&.componentaction\&.IsfAbout\&.serialVersionUID = \-6790954285526957354L\fC [static]\fP, \fC [private]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for MagicDrawCompPlugin from the source code\&.
