.TH "gov.nasa.jpl.componentaction.IsfCommandLine" 3 "Tue Aug 9 2016" "Version 4.3" "MagicDrawCompPlugin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gov.nasa.jpl.componentaction.IsfCommandLine \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits CommandLine\&.
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBmain\fP (String[] args)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "byte \fBexecute\fP ()"
.br
.in -1c
.SS "Static Package Attributes"

.in +1c
.ti -1c
.RI "static File \fBpluginDir\fP"
.br
.ti -1c
.RI "static String \fBprojectFile\fP"
.br
.in -1c
.SS "Static Private Attributes"

.in +1c
.ti -1c
.RI "static final String \fBPROJECT\fP = 'project_name'"
.br
.ti -1c
.RI "static final String \fBPACKAGE\fP = 'package'"
.br
.ti -1c
.RI "static final String \fBUSAGE\fP = 'isfpluginexec [options]\\nBefore running on headless environment, use Xvfb to set up a virtual X11 display server\\n/usr/bin/Xvfb :1 \-screen 0 1024x768x24\\nexport DISPLAY=:1'"
.br
.ti -1c
.RI "static final String \fBCOPYRIGHT\fP = 'Copyright 2015 (California Institute of Technology)\\nALL RIGHTS RESERVED\&. U\&.S\&. Government Sponsorship acknowledged\&.'"
.br
.in -1c
.SH "Detailed Description"
.PP 
Class to run MagicDraw plugin from command line
.PP
Before running on headless environment, use Xvfb to set up a virtual X11 display server \fC/usr/bin/Xvfb :1 -screen 0 1024x768x24 export DISPLAY=:1 \fP
.PP
To run the utility, use the script isfpluginexec\&.sh in the MagicDrawCompPlugin directory 
.SH "Member Function Documentation"
.PP 
.SS "byte gov\&.nasa\&.jpl\&.componentaction\&.IsfCommandLine\&.execute ()\fC [protected]\fP"
Runs autocoder on the project specified 
.SS "static void gov\&.nasa\&.jpl\&.componentaction\&.IsfCommandLine\&.main (String[] args)\fC [static]\fP"
Reads the command line arguments and launches the program
.PP
\fBParameters:\fP
.RS 4
\fIargs\fP application arguments\&. 
.RE
.PP

.SH "Member Data Documentation"
.PP 
.SS "final String gov\&.nasa\&.jpl\&.componentaction\&.IsfCommandLine\&.COPYRIGHT = 'Copyright 2015 (California Institute of Technology)\\nALL RIGHTS RESERVED\&. U\&.S\&. Government Sponsorship acknowledged\&.'\fC [static]\fP, \fC [private]\fP"

.SS "final String gov\&.nasa\&.jpl\&.componentaction\&.IsfCommandLine\&.PACKAGE = 'package'\fC [static]\fP, \fC [private]\fP"

.SS "File gov\&.nasa\&.jpl\&.componentaction\&.IsfCommandLine\&.pluginDir\fC [static]\fP, \fC [package]\fP"

.SS "final String gov\&.nasa\&.jpl\&.componentaction\&.IsfCommandLine\&.PROJECT = 'project_name'\fC [static]\fP, \fC [private]\fP"

.SS "String gov\&.nasa\&.jpl\&.componentaction\&.IsfCommandLine\&.projectFile\fC [static]\fP, \fC [package]\fP"

.SS "final String gov\&.nasa\&.jpl\&.componentaction\&.IsfCommandLine\&.USAGE = 'isfpluginexec [options]\\nBefore running on headless environment, use Xvfb to set up a virtual X11 display server\\n/usr/bin/Xvfb :1 \-screen 0 1024x768x24\\nexport DISPLAY=:1'\fC [static]\fP, \fC [private]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for MagicDrawCompPlugin from the source code\&.
