.TH "gov.nasa.jpl.componentaction.ISFComponent.portObject" 3 "Tue Aug 9 2016" "Version 4.3" "MagicDrawCompPlugin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gov.nasa.jpl.componentaction.ISFComponent.portObject \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "int \fBgetIndex\fP ()"
.br
.ti -1c
.RI "String \fBgetStereotype\fP ()"
.br
.ti -1c
.RI "String \fBgetDatatype\fP ()"
.br
.ti -1c
.RI "String \fBgetDatatypeNamespace\fP ()"
.br
.ti -1c
.RI "String \fBgetRole\fP ()"
.br
.ti -1c
.RI "String \fBgetPriority\fP ()"
.br
.ti -1c
.RI "String \fBgetFull\fP ()"
.br
.in -1c
.SS "Package Functions"

.in +1c
.ti -1c
.RI "\fBportObject\fP ()"
.br
.in -1c
.SS "Package Attributes"

.in +1c
.ti -1c
.RI "int \fBindex\fP"
.br
.ti -1c
.RI "String \fBstereotype\fP"
.br
.ti -1c
.RI "String \fBdatatype\fP"
.br
.ti -1c
.RI "String \fBdatatypeNamespace\fP"
.br
.ti -1c
.RI "String \fBrole\fP"
.br
.ti -1c
.RI "String \fBpriority\fP"
.br
.ti -1c
.RI "String \fBfull\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Used to process ports in the component phase\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "gov\&.nasa\&.jpl\&.componentaction\&.ISFComponent\&.portObject\&.portObject ()\fC [package]\fP"

.SH "Member Function Documentation"
.PP 
.SS "String gov\&.nasa\&.jpl\&.componentaction\&.ISFComponent\&.portObject\&.getDatatype ()"

.SS "String gov\&.nasa\&.jpl\&.componentaction\&.ISFComponent\&.portObject\&.getDatatypeNamespace ()"

.SS "String gov\&.nasa\&.jpl\&.componentaction\&.ISFComponent\&.portObject\&.getFull ()"

.SS "int gov\&.nasa\&.jpl\&.componentaction\&.ISFComponent\&.portObject\&.getIndex ()"

.SS "String gov\&.nasa\&.jpl\&.componentaction\&.ISFComponent\&.portObject\&.getPriority ()"

.SS "String gov\&.nasa\&.jpl\&.componentaction\&.ISFComponent\&.portObject\&.getRole ()"

.SS "String gov\&.nasa\&.jpl\&.componentaction\&.ISFComponent\&.portObject\&.getStereotype ()"

.SH "Member Data Documentation"
.PP 
.SS "String gov\&.nasa\&.jpl\&.componentaction\&.ISFComponent\&.portObject\&.datatype\fC [package]\fP"

.SS "String gov\&.nasa\&.jpl\&.componentaction\&.ISFComponent\&.portObject\&.datatypeNamespace\fC [package]\fP"

.SS "String gov\&.nasa\&.jpl\&.componentaction\&.ISFComponent\&.portObject\&.full\fC [package]\fP"

.SS "int gov\&.nasa\&.jpl\&.componentaction\&.ISFComponent\&.portObject\&.index\fC [package]\fP"

.SS "String gov\&.nasa\&.jpl\&.componentaction\&.ISFComponent\&.portObject\&.priority\fC [package]\fP"

.SS "String gov\&.nasa\&.jpl\&.componentaction\&.ISFComponent\&.portObject\&.role\fC [package]\fP"

.SS "String gov\&.nasa\&.jpl\&.componentaction\&.ISFComponent\&.portObject\&.stereotype\fC [package]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for MagicDrawCompPlugin from the source code\&.
