.TH "gov.nasa.jpl.componentaction.ISFComponent" 3 "Tue Aug 9 2016" "Version 4.3" "MagicDrawCompPlugin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gov.nasa.jpl.componentaction.ISFComponent \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBportObject\fP"
.br
.ti -1c
.RI "class \fBreferencePort\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBISFComponent\fP (Element \fBcomponentElement\fP)"
.br
.ti -1c
.RI "void \fBsetStereoType\fP (String \fBcompStereotype\fP)"
.br
.ti -1c
.RI "void \fBnewAddPort\fP (Element portElement)  throws PortException "
.br
.ti -1c
.RI "void \fBnewRolePort\fP (Element portElement)  throws PortException "
.br
.ti -1c
.RI "String \fBgetPortName\fP (Element portElement)"
.br
.ti -1c
.RI "String \fBgetPortStereotype\fP (Element portElement)"
.br
.ti -1c
.RI "String \fBgetPortDataType\fP (Element portElement)  throws PortException "
.br
.ti -1c
.RI "String \fBgetPortDataTypeNamespace\fP (Element portElement)"
.br
.ti -1c
.RI "HashMap< String, \fBportObject\fP > \fBgetPortHashList\fP ()"
.br
.ti -1c
.RI "String \fBgetURI\fP ()"
.br
.ti -1c
.RI "String \fBgetIncludeCmdXML\fP ()"
.br
.ti -1c
.RI "String \fBgetIncludeEvrXML\fP ()"
.br
.ti -1c
.RI "String \fBgetIncludeTlmXML\fP ()"
.br
.ti -1c
.RI "String \fBgetIncludeParamXML\fP ()"
.br
.ti -1c
.RI "String \fBgetIncludeInternalIFXML\fP ()"
.br
.ti -1c
.RI "String \fBgetIncludeHdrFile\fP ()"
.br
.ti -1c
.RI "String \fBgetNamespace\fP ()"
.br
.ti -1c
.RI "String \fBgetName\fP ()"
.br
.ti -1c
.RI "String \fBgetStereotype\fP ()"
.br
.ti -1c
.RI "List< String > \fBgetPortDataList\fP ()"
.br
.ti -1c
.RI "String \fBgetPortTypeProperty\fP (Element portElement, String property)"
.br
.ti -1c
.RI "String \fBgetComponentProperty\fP (Element portElement, String property)"
.br
.ti -1c
.RI "String \fBgetPortProperty\fP (Element portElement, String property)"
.br
.ti -1c
.RI "void \fBprint\fP ()"
.br
.ti -1c
.RI "void \fBcheckComponent\fP ()  throws ComponentException "
.br
.ti -1c
.RI "void \fBwarnLog\fP (String errStr)"
.br
.ti -1c
.RI "boolean \fBisValid\fP (String stereotype, String portType, boolean atLeastOne)"
.br
.in -1c
.SS "Package Attributes"

.in +1c
.ti -1c
.RI "HashMap< String, \fBportObject\fP > \fBfiltList\fP"
.br
.ti -1c
.RI "String \fBIncludeCmdXML\fP"
.br
.ti -1c
.RI "String \fBIncludeTlmXML\fP"
.br
.ti -1c
.RI "String \fBIncludeEvrXML\fP"
.br
.ti -1c
.RI "String \fBIncludeParamXML\fP"
.br
.ti -1c
.RI "String \fBIncludeInternalIFXML\fP"
.br
.ti -1c
.RI "String \fBIncludeIncludeHdr\fP"
.br
.in -1c
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "String \fBgetDictionaryString\fP (String includeString)"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "Element \fBcomponentElement\fP"
.br
.ti -1c
.RI "String \fBcompStereotype\fP"
.br
.ti -1c
.RI "String \fBURIName\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
This class encapsulates information pertaining to the component types and their ports in the MD model - ie active, passive or queued components 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "gov\&.nasa\&.jpl\&.componentaction\&.ISFComponent\&.ISFComponent (Element componentElement)"
Instantiation for the \fBISFComponent\fP\&.
.PP
\fBParameters:\fP
.RS 4
\fIcomponentElement\fP The element of the component that will be processed\&. 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "void gov\&.nasa\&.jpl\&.componentaction\&.ISFComponent\&.checkComponent () throws \fBComponentException\fP"
All passive components cannot have async_input ports All active components should have sync_input ports All queued components should have sync and async input ports 
.PP
\fBExceptions:\fP
.RS 4
\fI\fBComponentException\fP\fP 
.RE
.PP

.SS "String gov\&.nasa\&.jpl\&.componentaction\&.ISFComponent\&.getComponentProperty (Element portElement, String property)"
Returns the property value of Component stereotype of the input element argument\&. 
.PP
\fBParameters:\fP
.RS 4
\fIportElement\fP Element of the port type 
.br
\fIproperty\fP String of value to be looked for in the stereotype Component 
.RE
.PP
\fBReturns:\fP
.RS 4
The value of the attribute from property 
.RE
.PP

.SS "String gov\&.nasa\&.jpl\&.componentaction\&.ISFComponent\&.getDictionaryString (String includeString)\fC [private]\fP"
Return the full dictionary path which includes the URI path specified in the package above the component\&. 
.PP
\fBParameters:\fP
.RS 4
\fIincludeString\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
input string prepended by URIName 
.RE
.PP

.SS "String gov\&.nasa\&.jpl\&.componentaction\&.ISFComponent\&.getIncludeCmdXML ()"
Prepends the IncludeCmdXML String with the URI Name 
.PP
\fBReturns:\fP
.RS 4
address string 
.RE
.PP

.SS "String gov\&.nasa\&.jpl\&.componentaction\&.ISFComponent\&.getIncludeEvrXML ()"
Prepends the IncludeEvrXML String with the URI Name 
.PP
\fBReturns:\fP
.RS 4
address string 
.RE
.PP

.SS "String gov\&.nasa\&.jpl\&.componentaction\&.ISFComponent\&.getIncludeHdrFile ()"
Prepends the IncludeIncludeHdr String with the URI Name 
.PP
\fBReturns:\fP
.RS 4
address string 
.RE
.PP

.SS "String gov\&.nasa\&.jpl\&.componentaction\&.ISFComponent\&.getIncludeInternalIFXML ()"
Prepends the IncludeInternalIFXML String with the URI Name 
.PP
\fBReturns:\fP
.RS 4
address string 
.RE
.PP

.SS "String gov\&.nasa\&.jpl\&.componentaction\&.ISFComponent\&.getIncludeParamXML ()"
Prepends the IncludeParamXML String with the URI Name 
.PP
\fBReturns:\fP
.RS 4
address string 
.RE
.PP

.SS "String gov\&.nasa\&.jpl\&.componentaction\&.ISFComponent\&.getIncludeTlmXML ()"
Prepends the IncludeTlmXML String with the URI Name 
.PP
\fBReturns:\fP
.RS 4
address string 
.RE
.PP

.SS "String gov\&.nasa\&.jpl\&.componentaction\&.ISFComponent\&.getName ()"
Returns last part of the componentElement name 
.PP
\fBReturns:\fP
.RS 4
name 
.RE
.PP

.SS "String gov\&.nasa\&.jpl\&.componentaction\&.ISFComponent\&.getNamespace ()"
Get the component stereotype attribute called 'Namespace' 
.PP
\fBReturns:\fP
.RS 4
Namespace string of the componentElement 
.RE
.PP

.SS "List<String> gov\&.nasa\&.jpl\&.componentaction\&.ISFComponent\&.getPortDataList ()"
Creates a list of strings based off the data type from filtList values 
.PP
\fBReturns:\fP
.RS 4
A list of data type strings 
.RE
.PP

.SS "String gov\&.nasa\&.jpl\&.componentaction\&.ISFComponent\&.getPortDataType (Element portElement) throws \fBPortException\fP"
This returns the full path of the data type which includes the directory tree\&.
.PP
\fBParameters:\fP
.RS 4
\fIportElement\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
port data type string 
.RE
.PP
\fBExceptions:\fP
.RS 4
\fI\fBPortException\fP\fP 
.RE
.PP

.SS "String gov\&.nasa\&.jpl\&.componentaction\&.ISFComponent\&.getPortDataTypeNamespace (Element portElement)"
This returns the port data type without the full path\&. It also tags on the Namespace\&.
.PP
\fBParameters:\fP
.RS 4
\fIportElement\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
data type + '::' + name space 
.RE
.PP

.SS "HashMap<String, \fBportObject\fP> gov\&.nasa\&.jpl\&.componentaction\&.ISFComponent\&.getPortHashList ()"
Returns the filtList HashMap, a map with a string associated with a port object\&. 
.PP
\fBReturns:\fP
.RS 4
HashMap 
.RE
.PP

.SS "String gov\&.nasa\&.jpl\&.componentaction\&.ISFComponent\&.getPortName (Element portElement)"
Returns the port name\&.
.PP
\fBParameters:\fP
.RS 4
\fIportElement\fP port which the name will be extracted from 
.RE
.PP
\fBReturns:\fP
.RS 4
The name of the port 
.RE
.PP

.SS "String gov\&.nasa\&.jpl\&.componentaction\&.ISFComponent\&.getPortProperty (Element portElement, String property)"
Returns the property value of async_input stereotype of the input element argument\&. 
.PP
\fBParameters:\fP
.RS 4
\fIportElement\fP Element of the port type 
.br
\fIproperty\fP String of value to be looked for in the stereotype async_input 
.RE
.PP
\fBReturns:\fP
.RS 4
The value of the attribute from property 
.RE
.PP

.SS "String gov\&.nasa\&.jpl\&.componentaction\&.ISFComponent\&.getPortStereotype (Element portElement)"
Returns the port stereotype\&.
.PP
\fBParameters:\fP
.RS 4
\fIportElement\fP port which the stereotype will be extracted from 
.RE
.PP
\fBReturns:\fP
.RS 4
The stereotype of the port 
.RE
.PP

.SS "String gov\&.nasa\&.jpl\&.componentaction\&.ISFComponent\&.getPortTypeProperty (Element portElement, String property)"
Returns the property value of PortType stereotype of the input element argument\&. 
.PP
\fBParameters:\fP
.RS 4
\fIportElement\fP Element of the port type 
.br
\fIproperty\fP String of value to be looked for in the stereotype PortType 
.RE
.PP
\fBReturns:\fP
.RS 4
The value of the attribute from property 
.RE
.PP

.SS "String gov\&.nasa\&.jpl\&.componentaction\&.ISFComponent\&.getStereotype ()"
Returns compStereotype 
.PP
\fBReturns:\fP
.RS 4
the stereotype of the object 
.RE
.PP

.SS "String gov\&.nasa\&.jpl\&.componentaction\&.ISFComponent\&.getURI ()"
Returns the component's URI, which is the location in the tree hierarchy\&. 
.PP
\fBReturns:\fP
.RS 4
string of position in hierarchy 
.RE
.PP

.SS "boolean gov\&.nasa\&.jpl\&.componentaction\&.ISFComponent\&.isValid (String stereotype, String portType, boolean atLeastOne)"
Checks if a component is of a specific stereotype If so, checks if the component satisfies the requirement for a specific port type 
.PP
\fBParameters:\fP
.RS 4
\fIstereotype\fP the stereotype the component should have 
.br
\fIportType\fP the port type to check for 
.br
\fIatLeastOne\fP if the component should have the port type 
.RE
.PP

.SS "void gov\&.nasa\&.jpl\&.componentaction\&.ISFComponent\&.newAddPort (Element portElement) throws \fBPortException\fP"
Creates a new port object using the port Element inputted\&. This processes the port and can throw an exception if something in the port is illegal\&. It also adds the port into fillList\&.
.PP
\fBParameters:\fP
.RS 4
\fIportElement\fP 
.RE
.PP
\fBExceptions:\fP
.RS 4
\fI\fBPortException\fP\fP 
.RE
.PP

.SS "void gov\&.nasa\&.jpl\&.componentaction\&.ISFComponent\&.newRolePort (Element portElement) throws \fBPortException\fP"
Creates a new port object using the port Element inputted\&. This processes the port and can throw an exception if something in the port is illegal\&. It also adds the port into fillList\&.
.PP
\fBParameters:\fP
.RS 4
\fIportElement\fP 
.RE
.PP
\fBExceptions:\fP
.RS 4
\fI\fBPortException\fP\fP 
.RE
.PP

.SS "void gov\&.nasa\&.jpl\&.componentaction\&.ISFComponent\&.print ()"

.SS "void gov\&.nasa\&.jpl\&.componentaction\&.ISFComponent\&.setStereoType (String compStereotype)"
Sets the component stereotype string value 
.PP
\fBParameters:\fP
.RS 4
\fIcompStereotype\fP Stereotype string 
.RE
.PP

.SS "void gov\&.nasa\&.jpl\&.componentaction\&.ISFComponent\&.warnLog (String errStr)"
Prints a warning to the Java standard out as well as the MagicDraw console\&. 
.PP
\fBParameters:\fP
.RS 4
\fIerrStr\fP Message to be printed 
.RE
.PP

.SH "Member Data Documentation"
.PP 
.SS "Element gov\&.nasa\&.jpl\&.componentaction\&.ISFComponent\&.componentElement\fC [private]\fP"

.SS "String gov\&.nasa\&.jpl\&.componentaction\&.ISFComponent\&.compStereotype\fC [private]\fP"

.SS "HashMap<String, \fBportObject\fP> gov\&.nasa\&.jpl\&.componentaction\&.ISFComponent\&.filtList\fC [package]\fP"

.SS "String gov\&.nasa\&.jpl\&.componentaction\&.ISFComponent\&.IncludeCmdXML\fC [package]\fP"

.SS "String gov\&.nasa\&.jpl\&.componentaction\&.ISFComponent\&.IncludeEvrXML\fC [package]\fP"

.SS "String gov\&.nasa\&.jpl\&.componentaction\&.ISFComponent\&.IncludeIncludeHdr\fC [package]\fP"

.SS "String gov\&.nasa\&.jpl\&.componentaction\&.ISFComponent\&.IncludeInternalIFXML\fC [package]\fP"

.SS "String gov\&.nasa\&.jpl\&.componentaction\&.ISFComponent\&.IncludeParamXML\fC [package]\fP"

.SS "String gov\&.nasa\&.jpl\&.componentaction\&.ISFComponent\&.IncludeTlmXML\fC [package]\fP"

.SS "String gov\&.nasa\&.jpl\&.componentaction\&.ISFComponent\&.URIName\fC [private]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for MagicDrawCompPlugin from the source code\&.
