.TH "gov.nasa.jpl.componentaction.MpmcsErrorStream" 3 "Tue Aug 9 2016" "Version 4.3" "MagicDrawCompPlugin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gov.nasa.jpl.componentaction.MpmcsErrorStream \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits PrintStream\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMpmcsErrorStream\fP (PrintStream out1, PrintStream out2)"
.br
.ti -1c
.RI "\fBMpmcsErrorStream\fP (OutputStream arg0)"
.br
.ti -1c
.RI "\fBMpmcsErrorStream\fP (String arg0)  throws FileNotFoundException "
.br
.ti -1c
.RI "\fBMpmcsErrorStream\fP (File arg0)  throws FileNotFoundException "
.br
.ti -1c
.RI "\fBMpmcsErrorStream\fP (OutputStream arg0, boolean arg1)"
.br
.ti -1c
.RI "\fBMpmcsErrorStream\fP (String arg0, String arg1)  throws FileNotFoundException, UnsupportedEncodingException "
.br
.ti -1c
.RI "\fBMpmcsErrorStream\fP (File arg0, String arg1)  throws FileNotFoundException, UnsupportedEncodingException "
.br
.ti -1c
.RI "\fBMpmcsErrorStream\fP (OutputStream arg0, boolean arg1, String arg2)  throws UnsupportedEncodingException "
.br
.ti -1c
.RI "void \fBwrite\fP (byte buf[], int off, int len)"
.br
.ti -1c
.RI "void \fBflush\fP ()"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "PrintStream \fBout\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "gov\&.nasa\&.jpl\&.componentaction\&.MpmcsErrorStream\&.MpmcsErrorStream (PrintStream out1, PrintStream out2)"

.SS "gov\&.nasa\&.jpl\&.componentaction\&.MpmcsErrorStream\&.MpmcsErrorStream (OutputStream arg0)"

.SS "gov\&.nasa\&.jpl\&.componentaction\&.MpmcsErrorStream\&.MpmcsErrorStream (String arg0) throws FileNotFoundException"

.SS "gov\&.nasa\&.jpl\&.componentaction\&.MpmcsErrorStream\&.MpmcsErrorStream (File arg0) throws FileNotFoundException"

.SS "gov\&.nasa\&.jpl\&.componentaction\&.MpmcsErrorStream\&.MpmcsErrorStream (OutputStream arg0, boolean arg1)"

.SS "gov\&.nasa\&.jpl\&.componentaction\&.MpmcsErrorStream\&.MpmcsErrorStream (String arg0, String arg1) throws FileNotFoundException, UnsupportedEncodingException"

.SS "gov\&.nasa\&.jpl\&.componentaction\&.MpmcsErrorStream\&.MpmcsErrorStream (File arg0, String arg1) throws FileNotFoundException, UnsupportedEncodingException"

.SS "gov\&.nasa\&.jpl\&.componentaction\&.MpmcsErrorStream\&.MpmcsErrorStream (OutputStream arg0, boolean arg1, String arg2) throws UnsupportedEncodingException"

.SH "Member Function Documentation"
.PP 
.SS "void gov\&.nasa\&.jpl\&.componentaction\&.MpmcsErrorStream\&.flush ()"

.SS "void gov\&.nasa\&.jpl\&.componentaction\&.MpmcsErrorStream\&.write (byte buf[], int off, int len)"

.SH "Member Data Documentation"
.PP 
.SS "PrintStream gov\&.nasa\&.jpl\&.componentaction\&.MpmcsErrorStream\&.out\fC [private]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for MagicDrawCompPlugin from the source code\&.
