.TH "gov.nasa.jpl.componentaction.ISFSubsystem.topologyModel" 3 "Tue Aug 9 2016" "Version 4.3" "MagicDrawCompPlugin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gov.nasa.jpl.componentaction.ISFSubsystem.topologyModel \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBtopologyModel\fP (HashMap< String, ISFSubsystem\&.componentType > componentItemsMap, ArrayList< ISFSubsystem\&.physicalConnectionType > physicalConnList)"
.br
.ti -1c
.RI "HashMap< String, ISFSubsystem\&.componentType > \fBgetComponentMap\fP ()"
.br
.ti -1c
.RI "ArrayList< ISFSubsystem\&.physicalConnectionType > \fBgetPhysicalConnectionList\fP ()"
.br
.ti -1c
.RI "String \fBgetBaseID\fP ()"
.br
.ti -1c
.RI "String \fBgetInstanceWindow\fP ()"
.br
.ti -1c
.RI "String \fBgetName\fP ()"
.br
.in -1c
.SS "Package Attributes"

.in +1c
.ti -1c
.RI "HashMap< String, ISFSubsystem\&.componentType > \fBcomponentMap\fP"
.br
.ti -1c
.RI "ArrayList< ISFSubsystem\&.physicalConnectionType > \fBphysicalConnectionList\fP"
.br
.ti -1c
.RI "String \fBbaseID\fP"
.br
.ti -1c
.RI "String \fBinstanceWindow\fP"
.br
.ti -1c
.RI "String \fBname\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Used as a object to store the componentMap, physicalConnectionList, name, baseID, and instanceWindow\&. An object of this type is then sent to IsfSubXmlWriter and is used to write to the XML output file\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "gov\&.nasa\&.jpl\&.componentaction\&.ISFSubsystem\&.topologyModel\&.topologyModel (HashMap< String, ISFSubsystem\&.componentType > componentItemsMap, ArrayList< ISFSubsystem\&.physicalConnectionType > physicalConnList)"

.SH "Member Function Documentation"
.PP 
.SS "String gov\&.nasa\&.jpl\&.componentaction\&.ISFSubsystem\&.topologyModel\&.getBaseID ()"

.SS "HashMap<String , ISFSubsystem\&.componentType> gov\&.nasa\&.jpl\&.componentaction\&.ISFSubsystem\&.topologyModel\&.getComponentMap ()"

.SS "String gov\&.nasa\&.jpl\&.componentaction\&.ISFSubsystem\&.topologyModel\&.getInstanceWindow ()"

.SS "String gov\&.nasa\&.jpl\&.componentaction\&.ISFSubsystem\&.topologyModel\&.getName ()"

.SS "ArrayList<ISFSubsystem\&.physicalConnectionType> gov\&.nasa\&.jpl\&.componentaction\&.ISFSubsystem\&.topologyModel\&.getPhysicalConnectionList ()"

.SH "Member Data Documentation"
.PP 
.SS "String gov\&.nasa\&.jpl\&.componentaction\&.ISFSubsystem\&.topologyModel\&.baseID\fC [package]\fP"

.SS "HashMap<String , ISFSubsystem\&.componentType> gov\&.nasa\&.jpl\&.componentaction\&.ISFSubsystem\&.topologyModel\&.componentMap\fC [package]\fP"

.SS "String gov\&.nasa\&.jpl\&.componentaction\&.ISFSubsystem\&.topologyModel\&.instanceWindow\fC [package]\fP"

.SS "String gov\&.nasa\&.jpl\&.componentaction\&.ISFSubsystem\&.topologyModel\&.name\fC [package]\fP"

.SS "ArrayList<ISFSubsystem\&.physicalConnectionType> gov\&.nasa\&.jpl\&.componentaction\&.ISFSubsystem\&.topologyModel\&.physicalConnectionList\fC [package]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for MagicDrawCompPlugin from the source code\&.
