.TH "gov.nasa.jpl.componentaction.Utils" 3 "Tue Aug 9 2016" "Version 4.3" "MagicDrawCompPlugin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gov.nasa.jpl.componentaction.Utils \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBPair\fP"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBthrowConnectorException\fP (String input)  throws ConnectorException"
.br
.ti -1c
.RI "static void \fBnotifyWarning\fP (String input)  throws ConnectorException"
.br
.ti -1c
.RI "static String \fBgetExtension\fP (File f)"
.br
.ti -1c
.RI "static void \fBprintToAll\fP (String s)"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static final String \fBaadl\fP = 'aadl'"
.br
.in -1c
.SH "Detailed Description"
.PP 
This class is used by the JFileChooser to just list files with the *\&.aadl extension 
.PP
\fBAuthor:\fP
.RS 4
kevensen 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "static String gov\&.nasa\&.jpl\&.componentaction\&.Utils\&.getExtension (File f)\fC [static]\fP"
Simple utility method to get the file extension of a file\&.
.PP
\fBParameters:\fP
.RS 4
\fIf\fP File to be checked 
.RE
.PP
\fBReturns:\fP
.RS 4
String value extension of the file 
.RE
.PP

.SS "static void gov\&.nasa\&.jpl\&.componentaction\&.Utils\&.notifyWarning (String input) throws \fBConnectorException\fP\fC [static]\fP"
Appends '===> Warning: ' to the input then prints the input to standard out and the MagicDraw console 
.PP
\fBParameters:\fP
.RS 4
\fIinput\fP Input String 
.RE
.PP
\fBExceptions:\fP
.RS 4
\fI\fBConnectorException\fP\fP 
.RE
.PP

.SS "static void gov\&.nasa\&.jpl\&.componentaction\&.Utils\&.printToAll (String s)\fC [static]\fP"
Combines printing to console out on the Java IDE and MagicDraw
.PP
\fBParameters:\fP
.RS 4
\fIs\fP String to be printed 
.RE
.PP

.SS "static void gov\&.nasa\&.jpl\&.componentaction\&.Utils\&.throwConnectorException (String input) throws \fBConnectorException\fP\fC [static]\fP"
Appends to front '===> FATAL Exception: ' to the input then prints and throws Connector Exception
.PP
\fBParameters:\fP
.RS 4
\fIinput\fP Input String  
.RE
.PP
\fBExceptions:\fP
.RS 4
\fI\fBConnectorException\fP\fP 
.RE
.PP

.SH "Member Data Documentation"
.PP 
.SS "final String gov\&.nasa\&.jpl\&.componentaction\&.Utils\&.aadl = 'aadl'\fC [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for MagicDrawCompPlugin from the source code\&.
