/**
 * @name Side effect in a Boolean expression
 * @description The evaluation of a Boolean expression shall have no side effects.
 * @kind problem
 * @id cpp/fprime/jpl-c/no-boolean-side-effects
 * @problem.severity warning
 * @tags correctness
 *       readability
 *       external/jpl
 */

import cpp

/*
 * F Prime refinement of the stock JPL Rule 19 query
 * (cpp/jpl-c/no-boolean-side-effects). The stock query trips on three C++
 * constructs that are not side effects in a hand-written boolean expression:
 *
 * 1. Uninstantiated template code: calls whose target is unresolved (e.g.
 *    `e.getKey() == keyOrElement` in a class template) are represented as
 *    `ExprCall`s, which the stock query unconditionally treats as
 *    side-effecting. Instantiations are still checked.
 * 2. Range-based `for` statements: the compiler-generated condition
 *    `__begin != __end` calls iterator operators, which the purity analysis
 *    reports as unsafe. The programmer wrote no boolean expression at all.
 * 3. `constexpr` functions (e.g. `std::numeric_limits<T>::max()`): required
 *    by the language to be evaluable at compile time, hence side-effect free.
 */

/**
 * A whitelist of functions that should be considered
 * side-effect free.
 */
predicate safeFunctionWhitelist(Function f) {
  // constexpr functions are evaluable at compile time and side-effect free
  f.isConstexpr()
}

/**
 * Gets a "pointer type" contained in the given type. This
 * traverses typedefs and derived types, including types of
 * struct or union members, returning each "pointer to X"
 * type encountered on that traversal.
 */
PointerType getAPointerType(Type t) {
  result = t or
  result = getAPointerType(t.getUnderlyingType()) or
  result = getAPointerType(t.(DerivedType).getBaseType()) or
  result = getAPointerType(t.(Class).getAMemberVariable().getType())
}

/**
 * A function is "inherently unsafe" for side effects if it
 * writes a global or static variable, or if it calls another
 * inherently unsafe function.
 */
predicate inherentlyUnsafe(Function f) {
  exists(Variable v | v.getAnAssignedValue().getEnclosingFunction() = f |
    v instanceof GlobalVariable or
    v.isStatic()
  )
  or
  exists(FunctionCall c | c.getEnclosingFunction() = f | inherentlyUnsafe(c.getTarget()))
}

/**
 * Find functions that are "safe to call" without causing a side effect.
 * Being safe to call means that any "pointer type" in an argument type
 * actually refers to a "const" object, and, moreover, the function is
 * not inherently unsafe.
 */
predicate safeToCall(Function f) {
  forall(PointerType paramPointerType |
    paramPointerType = getAPointerType(f.getAParameter().getType())
  |
    paramPointerType.getBaseType().isConst()
  ) and
  not inherentlyUnsafe(f)
}

/**
 * A "Boolean expression" is an expression forbidden from having side effects
 * by this rule. Conditions generated by the compiler for range-based `for`
 * statements are not boolean expressions written by the programmer.
 */
class BooleanExpression extends Expr {
  BooleanExpression() {
    (
      exists(Loop l | l.getControllingExpr() = this) or
      exists(IfStmt i | i.getCondition() = this) or
      exists(ConditionalExpr e | e.getCondition() = this)
    ) and
    not exists(RangeBasedForStmt r | r.getCondition() = this)
  }
}

predicate hasSideEffect(Expr e) {
  e instanceof Assignment
  or
  e instanceof CrementOperation
  or
  e instanceof ExprCall and not e.isFromUninstantiatedTemplate(_)
  or
  exists(Function f | f = e.(FunctionCall).getTarget() and not safeFunctionWhitelist(f) |
    inherentlyUnsafe(f) or not safeToCall(f)
  )
  or
  hasSideEffect(e.getAChild())
}

from BooleanExpression b
where hasSideEffect(b) and not b.isFromUninstantiatedTemplate(_)
select b, "This Boolean expression is not side-effect free."
