/**
 * Extends the standard CodeQL assertion library with support for the F Prime
 * `FW_ASSERT` macro family, so that queries in this pack recognize F Prime
 * assertions.
 */

import cpp
import semmle.code.cpp.commons.Assertions

/**
 * An F Prime assertion: an invocation of an `FW_ASSERT` macro, which expands
 * to a conditional expression of the form
 * `(condition ? (void)0 : Fw::SwAssert(...))`.
 */
class FwAssert extends MacroInvocation, Assertion {
  FwAssert() { this.getMacro().getName() = "FW_ASSERT" }

  override Expr getAsserted() {
    exists(ConditionalExpr ce |
      ce = this.getAGeneratedElement() and
      // Restrict to the outermost conditional generated by this macro
      // invocation (nested FW_ASSERTs are separate macro invocations).
      not exists(ConditionalExpr outer |
        outer = this.getAGeneratedElement() and
        ce.getParent+() = outer
      )
    |
      result = ce.getCondition()
    )
  }
}
