// ======================================================================
// \title  DataPortAc.hpp
// \author Generated by fpp-to-cpp
// \brief  hpp file for Data port
// ======================================================================

#ifndef FppTest_DataPortAc_HPP
#define FppTest_DataPortAc_HPP

#include "Fw/FPrimeBasicTypes.hpp"
#include "Fw/Port/PortBase.hpp"
#if !FW_DIRECT_PORT_CALLS
#include "Fw/Comp/PassiveComponentBase.hpp"
#include "Fw/Port/InputPortBase.hpp"
#include "Fw/Port/OutputPortBase.hpp"
#include "Fw/Types/Serializable.hpp"
#include "Fw/Types/String.hpp"
#endif

namespace FppTest {

//! Data port constants
struct DataPortConstants {
    //! The size of the serial representations of the port arguments
    static constexpr FwSizeType INPUT_SERIALIZED_SIZE = sizeof(U32);
};

#if !FW_DIRECT_PORT_CALLS

//! Input Data port
class InputDataPort : public Fw::InputPortBase {
  public:
    // ----------------------------------------------------------------------
    // Constants
    // ----------------------------------------------------------------------

    enum {
        //! The size of the serial representations of the port arguments
        SERIALIZED_SIZE = DataPortConstants::INPUT_SERIALIZED_SIZE
    };

  public:
    // ----------------------------------------------------------------------
    // Types
    // ----------------------------------------------------------------------

    //! The port callback function type
    typedef void (*CompFuncPtr)(Fw::PassiveComponentBase* callComp, FwIndexType portNum, U32 data);

  public:
    // ----------------------------------------------------------------------
    // Input Port Member functions
    // ----------------------------------------------------------------------

    //! Constructor
    InputDataPort();

    //! Initialization function
    void init();

    //! Register a component
    void addCallComp(Fw::PassiveComponentBase* callComp,  //!< The containing component
                     CompFuncPtr funcPtr                  //!< The port callback function
    );

    //! Invoke a port interface
    void invoke(U32 data  //!< The data
    );

  private:
#if FW_PORT_SERIALIZATION == 1

    //! Invoke the port with serialized arguments
    Fw::SerializeStatus invokeSerial(Fw::SerializeBufferBase& _buffer);

#endif

  private:
    // ----------------------------------------------------------------------
    // Member variables
    // ----------------------------------------------------------------------

    //! The pointer to the port callback function
    CompFuncPtr m_func;
};

//! Output Data port
class OutputDataPort : public Fw::OutputPortBase {
  public:
    // ----------------------------------------------------------------------
    // Output Port Member functions
    // ----------------------------------------------------------------------

    //! Constructor
    OutputDataPort();

    //! Initialization function
    void init();

    //! Register an input port
    void addCallPort(InputDataPort* callPort  //!< The input port
    );

    //! Invoke a port interface
    void invoke(U32 data  //!< The data
    ) const;

  private:
    // ----------------------------------------------------------------------
    // Member variables
    // ----------------------------------------------------------------------

    //! The pointer to the input port
    InputDataPort* m_port;
};

#endif

}  // namespace FppTest

#endif
