name: Autodocs
on:
  push:
    branches:
      - "devel"

jobs:
  build:
    name: Autodocumentation
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2.0.0
    - name: Install fprime tools
      run: pip3 install fprime-tools fprime-gds
    - name: Setup Dependencies
      run: sudo apt-get install doxygen
    - name: Autodocs
      run: .github/actions/autodoc.bash
