name: Autodocs

on:
  push:
    branches: [ devel, release/** ]
  pull_request:
    branches: [ devel, release/** ]
    paths-ignore:
      - '.github/actions/spelling/**'

jobs:
  build:
    name: Autodocumentation
    runs-on: ubuntu-latest
    steps:
    - name: "Checkout F´ Repository"
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        submodules: true
    - uses: ./.github/actions/setup
    - name: Setup Dependencies
      run: |
           sudo apt-get update
           sudo apt-get install -y doxygen
    - name: Autodocs
      run: .github/actions/autodoc.bash
