name: Autodocs
on:
  push:
    branches:
      - "devel"

jobs:
  build:
    name: Autodocumentation
    runs-on: ubuntu-20.04
    steps:
    - name: checkout
      uses: actions/checkout@v2.0.0
      with:
        fetch-depth: 5
    - uses: ./.github/actions/
      id: github-autodocs
