# This is a basic workflow to help you get started with Actions

name: CI [RHEL8]

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ devel, release/**, ci/** ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ devel, release/** ]
    paths-ignore:
      - 'docs/**'
      - '**.md'
      - '.github/actions/spelling/**'
      - '.github/ISSUE_TEMPLATE/**'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  Framework:
    runs-on: ubuntu-latest
    container:
      image: redhat/ubi8:8.10
    steps:
    - name: "Install dependencies"
      run: |
        dnf install -y git python3.12 python3.12-pip llvm-toolset
        git config --global --add safe.directory ${GITHUB_WORKSPACE}
    - name: "Checkout F´ Repository"
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        submodules: true
    - uses: ./.github/actions/setup
    - name: Build Framework
      run: |
        fprime-util generate
        fprime-util build --all -j4

  Ref:
    runs-on: ubuntu-latest
    container:
      image: redhat/ubi8:8.10
    steps:
    - name: "Install dependencies"
      run: |
        dnf install -y git python3.12 python3.12-pip llvm-toolset
        git config --global --add safe.directory ${GITHUB_WORKSPACE}
    - name: "Checkout F´ Repository"
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        submodules: true
    - uses: ./.github/actions/setup
    - name: Build Ref
      run: |
        cd Ref
        fprime-util generate
        fprime-util build -j4

  UTs:
    runs-on: ubuntu-latest
    container:
      image: redhat/ubi8:8.10
    steps:
    - name: "Install dependencies"
      run: |
        dnf install -y git python3.12 python3.12-pip llvm-toolset
        git config --global --add safe.directory ${GITHUB_WORKSPACE}
    - name: "Checkout F´ Repository"
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        submodules: true
    - uses: ./.github/actions/setup
    - name: General UT Build
      run: |
        fprime-util generate --ut
        fprime-util build --all --ut -j4
        fprime-util check --all -j4
