# See https://github.com/fprime-community/fprime-workshop-led-blinker

name: LedBlinker Tests

on: [push, pull_request]

jobs:
  build:
    name: ""
    uses: ./.github/workflows/reusable-builder.yml
    with: 
      target_repository: fprime-community/fprime-workshop-led-blinker
      build_location: LedBlinker
      run_unit_tests: true