# Builds and runs UTs on https://github.com/fprime-community/fprime-tutorial-hello-world

name: "Tutorial: HelloWorld"

on:
  push:
    branches: [ master, devel, issue-2278-testing ]
  pull_request:
    branches: [ master, devel ]
    paths-ignore:
      - 'docs/**'
      - '**.md'
      - '.github/actions/spelling/**'
      - '.github/ISSUE_TEMPLATE/**'

jobs:
  # If the PR that triggered this job has a matching `pr-<number>` branch on inputs.target_repository,
  # then return the name of that branch. Otherwise, return inputs.target_ref.
  # This jobs then passes the target branch to the build/UT job.
  get-branch:
    runs-on: ubuntu-latest
    name: "Get target branch"
    outputs:
      target-branch: ${{ steps.get_target_branch.outputs.TARGET_BRANCH }}
    steps:
      - name: "Get target branch"
        id: get_target_branch
        run: |
          response_code=`curl -w '%{response_code}' https://api.github.com/repos/${{ inputs.target_repository }}/branches/pr-${{ github.event.number }} -o /dev/null`
          if [[ "${{ github.event_name }}" == "pull_request" && "$response_code" == "200" ]]; then
            echo "TARGET_BRANCH=pr-${{ github.event.number }}" >> $GITHUB_OUTPUT
            echo "PR branch found, using pr-${{ github.event.number }}"
          else
            echo "TARGET_BRANCH=${{ inputs.default_target_ref }}" >> $GITHUB_OUTPUT
            echo "PR branch not found, using ${{ inputs.default_target_ref }}"
          fi
        shell: bash

  run:
    needs: get-branch
    name: ""
    uses: ./.github/workflows/reusable-builder.yml
    with:
      target_repository: fprime-community/fprime-tutorial-hello-world
      build_location: HelloWorldDeployment
      run_unit_tests: true
      target_ref: ${{ needs.get-branch.outputs.target-branch }}
