# Builds and runs integration tests on https://github.com/fprime-community/fprime-python-reference

name: "External Repo: fprime-python-reference"

on:
  push:
    branches: [ devel, release/** ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ devel, release/** ]
    paths-ignore:
      - 'docs/**'
      - '**.md'
      - '.github/actions/spelling/**'
      - '.github/ISSUE_TEMPLATE/**'
      - '.github/agents/**'
# Cancel in-progress runs if a newer run is started on a given PR
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: ${{ !contains(github.ref, 'devel') && !contains(github.ref, 'release/')}}

permissions:
  contents: read

jobs:
  get-branch:
    name: "Get target branch"
    uses: ./.github/workflows/reusable-get-pr-branch.yml
    with:
      target_repository: fprime-community/fprime-python-reference
      default_target_ref: main

  build:
    needs: get-branch
    name: ""
    uses: ./.github/workflows/reusable-project-builder.yml
    with:
      target_repository: fprime-community/fprime-python-reference
      fprime_location: lib/fprime
      build_location: "."
      run_unit_tests: false
      # ubuntu-24.04 provides Python 3.12, required by fprime-python-reference
      runs_on: ubuntu-24.04
      target_ref: ${{ needs.get-branch.outputs.target-branch }}
      requirements_location: "."
      upload_artifacts: true
      artifact_name: fprime-python-reference-build-artifacts

  integration-tests:
    needs: [get-branch, build]
    runs-on: ubuntu-24.04
    name: "Integration Tests"
    env:
      FPRIME_LOCATION: lib/fprime
    steps:
      - name: "Checkout target repository"
        uses: actions/checkout@v4
        with:
          submodules: recursive
          repository: fprime-community/fprime-python-reference
          ref: ${{ needs.get-branch.outputs.target-branch }}
      - name: "Overlay current F´ revision"
        uses: actions/checkout@v4
        with:
          submodules: true
          path: lib/fprime
      - name: "Install requirements.txt"
        run: pip3 install -r requirements.txt
        shell: bash
      - name: "Download Build Artifacts"
        uses: actions/download-artifact@v8
        with:
          name: fprime-python-reference-build-artifacts
          path: build-artifacts/
      - name: "Integration Tests"
        uses: nasa/fprime-actions/run-integration-tests@devel
        with:
          gds-working-directory: "."
          test-working-directory: "."
          binary: "python3"
          binary-args: "build-artifacts/python/fsw_main.py"
          gds-args: "--ip-client --dictionary build-artifacts/*/*/dict/ReferenceDeploymentTopologyDictionary.json"
          pytest-args: "test/int --dictionary build-artifacts/*/*/dict/ReferenceDeploymentTopologyDictionary.json --logs gds-logs"
