# Builds and runs UTs on https://github.com/fprime-community/fprime-tutorial-math-component

name: "Tutorial: MathComponent"

on:
  push:
    branches: [ devel, release/** ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ devel, release/** ]
    paths-ignore:
      - 'docs/**'
      - '**.md'
      - '.github/actions/spelling/**'
      - '.github/ISSUE_TEMPLATE/**'

jobs:
  get-branch:
    name: "Get target branch"
    uses: ./.github/workflows/reusable-get-pr-branch.yml
    with:
      target_repository: fprime-community/fprime-tutorial-math-component

  run:
    needs: get-branch
    name: ""
    uses: ./.github/workflows/reusable-project-builder.yml
    with: 
      target_repository: fprime-community/fprime-tutorial-math-component
      build_location: MathDeployment
      run_unit_tests: true
      target_ref: ${{ needs.get-branch.outputs.target-branch }}
