# Cross-compile https://github.com/fprime-community/fprime-sensors-reference

name: "External Repo: F Prime Sensors Reference (RPI5)"

on:
  release:
    types: [published] # triggers when a release is published

jobs:

  cross-compile:
    runs-on: apple-ci

    steps:

      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up F Prime
        uses: nasa/fprime-actions/setup@devel

      - name: Cross compile
        uses: nasa/fprime-actions/build-with-aarch64-toolchain@devel
        with:
          toolchain-url: https://developer.arm.com/-/media/Files/downloads/gnu-a/10.2-2020.11/binrel/gcc-arm-10.2-2020.11-x86_64-aarch64-none-linux-gnu.tar.xz