# Builds and runs integration tests on https://github.com/yvijay99/fprime-yamcs-reference

name: "External Repo: mlpack Reference"

on:
  schedule:
    - cron: "0 21 * * *"  # Nightly at 2:00 PM US/Pacific (PDT)
  push:
    branches: [release/**]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [devel, release/**]
    paths-ignore:
      - 'docs/**'
      - '**.md'
      - '.github/actions/spelling/**'
      - '.github/ISSUE_TEMPLATE/**'
      - '.github/agents/**'

# Cancel in-progress runs if a newer run is started on a given PR
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: ${{ !contains(github.ref, 'devel') && !contains(github.ref, 'release/') && !contains(github.ref, 'YAMCSCI') }}

permissions:
  contents: read

jobs:
  get-branch:
    name: "Get target branch"
    uses: ./.github/workflows/reusable-get-pr-branch.yml
    with:
      target_repository: fprime-community/fprime-mlpack-reference
      default_target_ref: main

  run:
    needs: get-branch
    name: ""
    uses: ./.github/workflows/reusable-project-builder.yml
    with:
      target_repository: fprime-community/fprime-mlpack-reference
      build_location: ExampleDeployment
      run_unit_tests: false  # No UTs; just checking compilation is sufficient.
      target_ref: ${{ needs.get-branch.outputs.target-branch }}
      fprime_location: ./lib/fprime
