# Cross-compile https://github.com/fprime-community/fprime-sensors-reference

name: "External Repo: Soak Testing F Prime Sensors Reference (RPI5)"

on:
  release:
    types: [published] # triggers when a release is published
  push:
    branches: [ devel, release/**, soak-testing ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ devel, release/** ]
    paths-ignore:
      - 'docs/**'
      - '**.md'
      - '.github/actions/spelling/**'
      - '.github/ISSUE_TEMPLATE/**'
  workflow_dispatch:
    inputs:
      service_user:
        description: "Linux user to run services as (default: fprime)"
        required: false
        default: fprime
      gds_service_name:
        description: "Name of service that runs the F Prime GDS"
        required: false
        default: fprime-sensors-reference-soak-gds
      fsw_service_name:
        description: "Name of service that runs the F Prime FSW"
        required: false
        default: fprime-sensors-reference-soak-fsw

# Cancel in-progress runs if a newer run is started on a given PR
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: ${{ !contains(github.ref, 'devel') && !contains(github.ref, 'release/')}}

env:
  FSW_SERVICE_NAME: "fprime-sensors-reference-soak-fsw"
  GDS_SERVICE_NAME: "fprime-sensors-reference-soak-gds"
  INSTALL_DIR: /opt/fprime-sensors-reference-soak
  SERVICE_USER: "fprime"

jobs:

  cross-compile:
    name: "Cross Compilation"
    runs-on: ubuntu-latest

    steps:

      - name: Set up F Prime
        uses: nasa/fprime-actions/external-repository-setup@devel
        with:
          target_repository: fprime-community/fprime-sensors-reference

      - name: Cross compile
        uses: nasa/fprime-actions/build-with-aarch64-toolchain@devel
        with:
          toolchain-url: https://developer.arm.com/-/media/Files/downloads/gnu-a/10.2-2020.11/binrel/gcc-arm-10.2-2020.11-x86_64-aarch64-none-linux-gnu.tar.xz

      - name: Prepare artifacts
        run: |
          mkdir -p build-artifacts-soak
          cp -r ./build-artifacts build-artifacts-soak
          cp ./lib/fprime/.github/actions/soak-test/soak_monitor.py build-artifacts-soak
          cp ./lib/fprime/.github/actions/soak-test/${{ env.GDS_SERVICE_NAME }}.service build-artifacts-soak
          cp ./lib/fprime/.github/actions/soak-test/${{ env.FSW_SERVICE_NAME }}.service build-artifacts-soak

      - name: 'Archive Build Artifacts'
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts-soak
          path: build-artifacts-soak
          retention-days: 1

  deploy-service:
    name: "Deploy as System Service"
    runs-on: [apple-ci]
    needs: cross-compile

    steps:
      - name: "Artifacts Download"
        uses: actions/download-artifact@v5
        with:
          name: build-artifacts-soak

      - name: "Stop Services"
        shell: bash
        run: |
          sudo systemctl stop ${{ env.FSW_SERVICE_NAME }}.service || true
          sudo systemctl disable ${{ env.FSW_SERVICE_NAME }}.service || true
          sudo systemctl stop ${{ env.GDS_SERVICE_NAME }}.service || true
          sudo systemctl disable ${{ env.GDS_SERVICE_NAME }}.service || true

      - name: "Create systemd Service File"
        run: |
          sudo cp ${{ env.FSW_SERVICE_NAME }}.service /etc/systemd/system/${{ env.FSW_SERVICE_NAME }}.service
          sudo sed -i s/\$\{SERVICE_USER\}/}
          sudo cp ${{ env.GDS_SERVICE_NAME }}.service /etc/systemd/system/${{ env.GDS_SERVICE_NAME }}.service

      - name: "Start and enable services"
        run: |
          echo "Starting and enabling services..."
          sudo systemctl daemon-reload

          # start and enable gds service
          sudo systemctl enable ${GDS_SERVICE_NAME}
          sudo systemctl start ${GDS_SERVICE_NAME}

          # start and enable binary
          sudo systemctl start ${FSW_SERVICE_NAME}
          sudo systemctl enable ${FSW_SERVICE_NAME}

          echo "Waiting for services to stabilize..."
          sleep 5 # Wait for services to stabilize

          echo "Checking final service status..."
          sudo systemctl status ${FSW_SERVICE_NAME} --no-pager -l -n 50
          sudo systemctl status ${GDS_SERVICE_NAME} --no-pager -l -n 150
