# Cross-compile https://github.com/fprime-community/fprime-workshop-led-blinker
# Runs integration tests on aarch64-linux

name: "External Repo: AArch64 Linux LedBlinker, Soak Test Setup"

on:
  push:
    branches: [ release/** ]
  workflow_dispatch:
# Cancel in-progress runs if a newer release build is started
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  AARCH64_TOOLCHAIN_DIR: /tmp/aarch64-toolchain
  AARCH64_TOOLCHAIN_URL: https://developer.arm.com/-/media/Files/downloads/gnu-a/10.2-2020.11/binrel/gcc-arm-10.2-2020.11-x86_64-aarch64-none-linux-gnu.tar.xz
  ARM_TOOLS_PATH: /tmp/aarch64-toolchain

jobs:
  get-branch:
    name: "Get target branch"
    uses: ./.github/workflows/reusable-get-pr-branch.yml
    with:
      target_repository: fprime-community/fprime-workshop-led-blinker

  cross-compilation:
    name: "Cross Compilation"
    runs-on: ubuntu-22.04
    needs: get-branch
    steps:
      - name: "Checkout target repository"
        uses: actions/checkout@v4
        with:
          submodules: false
          repository: fprime-community/fprime-workshop-led-blinker
          ref: ${{ needs.get-branch.outputs.target-branch }}
      - name: "Overlay current F´ revision"
        uses: actions/checkout@v4
        with:
          submodules: true
          path: ./fprime
          fetch-depth: 0
      - uses: ./fprime/.github/actions/setup
        with:
          location: ./fprime
      - name: "Download and Setup AArch64 Linux Toolchain"
        run: |
          mkdir -p ${AARCH64_TOOLCHAIN_DIR}
          wget -q ${AARCH64_TOOLCHAIN_URL}
          tar -xf $(basename ${AARCH64_TOOLCHAIN_URL}) -C ${AARCH64_TOOLCHAIN_DIR} --strip-components 1
          echo "${AARCH64_TOOLCHAIN_DIR}/bin" >> $GITHUB_PATH
      - name: "Generate AArch64 Linux Build Cache"
        run: |
          fprime-util generate aarch64-linux
      - name: "Build AArch64 Linux"
        run: |
          fprime-util build aarch64-linux
      - name: "Prepare artifacts"
        run: |
          mkdir -p aarch64-linux-artifacts
          cp -r ./build-artifacts aarch64-linux-artifacts
          cp -r Components/Led/test/int aarch64-linux-artifacts
      - name: 'Archive Build Artifacts'
        uses: actions/upload-artifact@v4
        with:
          name: aarch64-linux-soak-artifacts
          path: aarch64-linux-artifacts
          retention-days: 30
