# Builds and runs integration tests on https://github.com/yvijay99/fprime-yamcs-reference

name: "External Repo: YAMCS Reference"

on:
  schedule:
    - cron: "0 21 * * *"  # Nightly at 2:00 PM US/Pacific (PDT)
  push:
    branches: [release/**]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [devel, release/**]
    paths-ignore:
      - 'docs/**'
      - '**.md'
      - '.github/actions/spelling/**'
      - '.github/ISSUE_TEMPLATE/**'
      - '.github/agents/**'
  workflow_dispatch:

# Cancel in-progress runs if a newer run is started on a given PR
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: ${{ !contains(github.ref, 'devel') && !contains(github.ref, 'release/') && !contains(github.ref, 'YAMCSCI') }}

permissions:
  contents: read

jobs:
  get-branch:
    name: "Get target branch"
    uses: ./.github/workflows/reusable-get-pr-branch.yml
    with:
      target_repository: fprime-community/fprime-yamcs-reference
      default_target_ref: main

  build:
    needs: get-branch
    name: ""
    uses: ./.github/workflows/reusable-project-builder.yml
    with:
      target_repository: fprime-community/fprime-yamcs-reference
      build_location: FprimeYamcsReference/YamcsDeployment
      run_unit_tests: false
      target_ref: ${{ needs.get-branch.outputs.target-branch }}
      fprime_location: ./lib/fprime

  test:
    name: "Test"
    needs: [get-branch, build]
    uses: ./.github/workflows/reusable-integration-tests.yml
    with:
      target_repository: fprime-community/fprime-yamcs-reference
      target_ref: ${{ needs.get-branch.outputs.target-branch }}
      deployment: FprimeYamcsReference_YamcsDeployment
      dictionary: ./build-artifacts/Linux/FprimeYamcsReference_YamcsDeployment/dict/YamcsDeploymentTopologyDictionary.json
      deployment_config: ./FprimeYamcsReference/YamcsDeployment/test/int/int_config.json
      ground_system: fprime-yamcs
      gds_package: fprime-gds==4.2.2a4
      test_paths: >-
        ./FprimeYamcsReference/YamcsDeployment/test/int/test_yamcs_file_transfer.py
        ./lib/fprime/Svc/PrmDb/test/int/test_cmd_PrmDb.py
        ./lib/fprime/Svc/CmdDispatcher/test/int/test_cmd_dispatcher.py
        ./lib/fprime/Svc/DpCatalog/test/int/test_cmd_dpCatalog.py
        ./lib/fprime/Svc/DpManager/test/int/test_cmd_dpMgr.py
        ./lib/fprime/Svc/DpWriter/test/int/test_cmd_dpWriter.py
        ./lib/fprime/Svc/EventManager/test/int/test_cmd_eventManager.py
        ./lib/fprime/Svc/FileDownlink/test/int/test_cmd_fileDownlink.py
        ./lib/fprime/Svc/FileManager/test/int/test_cmd_fileManager.py
        ./lib/fprime/Svc/SystemResources/test/int/test_cmd_systemResources.py
        ./lib/fprime/Svc/CmdSequencer/test/int/test_cmd_sequencer.py
        ./lib/fprime/Svc/FileUplink/test/int/test_cmd_uplink.py
        ./lib/fprime/Svc/Subtopologies/CdhCore/test/int/test_cdh_core.py
        ./lib/fprime/Svc/Subtopologies/FileHandling/test/int/test_file_handling.py
        ./lib/fprime/Svc/Version/test/int/test_cmd_version.py
        ./lib/fprime/Svc/Health/test/int/test_cmd_health.py
