name: "Code Format Check"

on:
  push:
    branches: [ devel, release/**, ci/** ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ devel, release/** ]
    paths-ignore:
      - 'docs/**'
      - '**.md'
      - '.github/actions/spelling/**'
      - '.github/ISSUE_TEMPLATE/**'

jobs:
  cpp-formatting:
    name: C++ Formatting
    runs-on: ubuntu-22.04
    steps:
      - name: "Checkout F´ Repository"
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: true
      - name: "Setup Python"
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - uses: ./.github/actions/setup
      - name: "Check C++ Formatting"
        env:
          # Svc is currently listing all but Svc/FpySequencer
          CHECKED_DIRS: >-
            CFDP
            default
            Drv
            FppTestProject
            Fw
            Os
            Ref
            Svc
            TestUtils
            Utils

        run: |
          fprime-util format --check --dirs $CHECKED_DIRS
        shell: bash

      - name: "Comment on PR in case of Failure"
        if: failure()
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'Formatting checks failed on the submitted code. To fix, you can run this command on your branch:\n\n```bash\ngit diff --name-only devel...HEAD | fprime-util format --stdin\n```'
            })
