name: "Code Format Check"

on:
  push:
    branches: [ devel, release/**, ci/** ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ devel, release/** ]
    paths-ignore:
      - 'docs/**'
      - '**.md'
      - '.github/actions/spelling/**'
      - '.github/ISSUE_TEMPLATE/**'

jobs:
  cpp-formatting:
    name: C++ Formatting
    runs-on: ubuntu-22.04
    steps:
      - name: "Checkout F´ Repository"
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: true
      - uses: ./.github/actions/setup
      - name: "Check C++ Formatting"
        run: |
          pip3 uninstall -y fprime-tools
          pip3 install -U git+https://github.com/thomas-bc/fprime-tools@formatting-ci-improvements
          pip3 freeze
          echo "HELP"
          // fprime-util format --help
          echo "FORMAT"
          // fprime-util format --check --dirs Fw/Buffer Fw/Cmd Fw/Com
        shell: bash
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
