name: Check Markdown links

on: 
  schedule:
    - cron: "0 21 * * *"  # Nightly at 2:00 PM US/Pacific (PDT)
  push:
    branches: [docs/new-website]
  pull_request:
    branches: [devel]
# Cancel in-progress runs if a newer run is started on a given PR
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: ${{ !contains(github.ref, 'devel') && !contains(github.ref, 'release/')}}

permissions:
  contents: read

jobs:
  markdown-link-check:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4

    - uses: ./.github/actions/setup

    - name: 'Generate Doxygen and CMake docs'
      timeout-minutes: 20
      run: |
        sudo apt-get -o Acquire::Retries=3 -o Acquire::http::Timeout=30 -o Acquire::https::Timeout=30 update
        sudo apt-get -o Acquire::Retries=3 -o Acquire::http::Timeout=30 -o Acquire::https::Timeout=30 install -y doxygen
        ./docs/doxygen/generate_docs.bash

    - uses: gaurav-nelson/github-action-markdown-link-check@5c5dfc0ac2e225883c0e5f03a85311ec2830d368 # v1
      with:
          use-quiet-mode: 'yes'
          config-file: ./.github/actions/markdown-check/mlc-config.json
