name: Check Markdown links

on: 
  push:
    branches: [devel]
  pull_request:
    branches: [devel]

jobs:
  markdown-link-check:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - uses: gaurav-nelson/github-action-markdown-link-check@v1
      with:
          use-quiet-mode: 'yes'
          config-file: ./.github/actions/markdown-check/mlc-config.json
