name: Format Python

on:
  push:
    branches: [ devel, release/** ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ devel, release/** ]

jobs:
  format:
      name: Format
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v3
      - name: Setup Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Check formatting
        run: |
          pip install click==8.0.4 black==21.6b0
          black --check --diff ./
