#!/bin/sh -e

dir=`dirname $0`
cd $dir

build_cache=../build-fprime-automatic-native-ut

./build-ut
dpTool_exe_base=FppTest_dpTool_ut_exe
dpTool_exe=`find $build_cache/bin -name $dpTool_exe_base`
cp $dpTool_exe .
./$dpTool_exe_base
