#!/bin/sh -e

build_cache=../build-fprime-automatic-native-ut/FppTest/dp/

files="
DpTestTesterBase
DpTestGTestBase
"

suffixes="hpp cpp"

for file in $files
do
  for suffix in $suffixes
  do
    cp test-modified/$file.$suffix $build_cache
  done
done
